### ISSUE TITLE
Is there a method to export sql script file from db?

### ISSUE THREAD

**Issue by tanbing001** [SOCI/soci#1000]

**Comment by vadz** [comment]
No and I'm not sure this question makes sense, at least not without explaining what exactly do you mean by "SQL script file".

**Comment by tanbing001** [comment]
I want make a copy of a local database before the columns change



---Original---
From: ***@***.***&gt;
Date: Sat, Oct 8, 2022 18:39 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [SOCI/soci] Is there a method to export sql script file from db?(Issue #1000)




 
No and I'm not sure this question makes sense, at least not without explaining what exactly do you mean by "SQL script file".

**Comment by tanbing001** [comment]
just like&nbsp; the database name test.db，how to get a file named test.db.sql script file that contains all data in the test.db



---Original---
From: ***@***.***&gt;
Date: Sat, Oct 8, 2022 18:39 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [SOCI/soci] Is there a method to export sql script file from db?(Issue #1000)




 
No and I'm not sure this question makes sense, at least not without explaining what exactly do you mean by "SQL script file".

**Comment by vadz** [comment]
This is not something that is natively provided by the database, AFAIK, so I don't think SOCI cash reasonably provide anything like this.

A better idea would be to use the database-specific backup format (which could be SQL, as for PostgreSQL, but could also be something completely different as for e.g. SQL Server).

**Comment by tanbing001** [comment]
ok.thanks



---Original---
From: ***@***.***&gt;
Date: Sat, Oct 8, 2022 20:10 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [SOCI/soci] Is there a method to export sql script file from db?(Issue #1000)




 
This is not something that is natively provided by the database, AFAIK, so I don't think SOCI cash reasonably provide anything like this.
 
A better idea would be to use the database-specific backup format (which could be SQL, as for PostgreSQL, but could also be something completely different as for e.g. SQL Server).
