### ISSUE TITLE
Missing git tag for 4.1.0 release?

### ISSUE THREAD

**Issue by Tectu** [SOCI/soci#1002]
There was a commit seemingly pumping out a `4.1.0` release: https://github.com/SOCI/soci/commit/db89eb26e191c244f761655ccb8f06977d250b60
However, a matching git tag seems to be missing. Was this a simple oversight?

**Comment by vadz** [comment]
No, 4.1.0 simply hasn't been released yet.

**Comment by Tectu** [comment]
Reasonable!
Any roadmap/guesstimated ETA on the next release?

**Comment by vadz** [comment]
Sorry, I can't commit to anything right now. Hopefully before the end of the year.

Of course, using the current master is always possible too and is not really different from using a release if you're using it as Git submodule, CMake external or equivalent.
