### ISSUE TITLE
MariaDB backend?

### ISSUE THREAD

**Issue by Tectu** [SOCI/soci#1004]
Is it possible to use soci with a MariaDB database via the existing `mysql` backend?

**Comment by vadz** [comment]
Sorry, I don't know. I think it should be relatively straightforward to use it as it should be API-compatible, but I've never done it myself (and, to be honest, don't plan to).

**Comment by Tectu** [comment]
I was just about to dive into this by first testing whether the MySQL backend is sufficiently compatible and eventually implementing a MariaDB backend. However, the project direction has changed in the meantime...

As I (un)fortunately won't be involved in anything related to SOCI+MariaDB I'll close this issue. Future developers might want to re-open this on demand.
