### ISSUE TITLE
How to escape a "!" present in connection string ? 

### ISSUE THREAD

**Issue by mreis1** [SOCI/soci#1006]
`./soci_firebird_test "service=localhost:DB_ALIAS user=SYSDBA password=masterkey!2"`
will output `bash: !2: event not found` because my password has a exclamation mark. 

How is it suppose to escape it? 
Tried wrapping the value in quotes but had no luck.
`./soci_firebird_test "service=localhost:DB_ALIAS user=SYSDBA password=\"masterkey!2\""`

Any suggestions? 
Thank you

**Comment by zann1x** [comment]
`!` is part of bash's history expansion. Enclosing the whole connection string in single quotes instead of double quotes or turning off history expansion in your shell should fix the problem.

**Comment by vadz** [comment]
This is a shell question, not a SOCI question, but the answer is to use single quotes around the connection string.
