### ISSUE TITLE
Includes are wrong with make-install on Linux Mint

### ISSUE THREAD

**Issue by ghost** [SOCI/soci#101]
Just FYI when you do a make install on linux mint 14 32 bit the mysql back end header includes the soci_core header but does not take into account the path. The include should be:

#include "../soci_core.h"

Currently it is 

#include "soci_core.h"

I realize if I configured my project to have the location of both headers as include directories this would solve the issue but that seems a little silly to me. Nothing serious, just saying! Thanks for the great lib btw.

**Comment by snikulov** [comment]
@mloskot #25 is closed. Should we close this bug?

**Comment by mloskot** [comment]
@snikulov Good catch, thanks!
