### ISSUE TITLE
Wrong deconstruction of connect pool

### ISSUE THREAD

**Issue by xum07** [SOCI/soci#1011]
![image](https://user-images.githubusercontent.com/19642011/198538533-8a3fb1a0-df80-4bcf-a1a5-58c0c17f13c1.png)

You must **close** session first, otherwise a normal database will keep the session alive until its timeout reaches.

**Comment by vadz** [comment]
Sorry, not sure what is the problem exactly, destroying a session should close it too. Which backend exactly do you use where it doesn't happen?

P.S. Please copy paste text and not screenshots for illustrating your point, TIA.

**Comment by xum07** [comment]
Sorry for this mistake
