### ISSUE TITLE
Postgresql insert json string

### ISSUE THREAD

**Issue by shiausan** [SOCI/soci#1019]
Hi
when c++ executed below
select count(*) from sp_status_write('[{"begin":"2022-11-27T13:45:40","end":"2022-11-27T13:45:40","loop":"0:1:0","number":100,"prizes":[],"property":1}]'); 
but db shows 
"[{""begin"":""2022-11-27T13$1:40"",""end"":""2022-11-27T13$2:40"",""loop"":""0$3:0"",""number"":100,""prizes"":[],""property"":1}]"

but it is correct result if execute sp_status_write procedure from pgAdmin4 tool 

thanks

**Comment by vadz** [comment]
Sorry, what is `sp_status_write`? Also, have you tried the data as a bound variable?

**Comment by shiausan** [comment]
sp_status_write is a stored procedure and i tried the data as a bound
variable which is working fine now

thanks a lot

VZ ***@***.***> 於 2022年11月20日 週日 晚上10:02寫道：
