### ISSUE TITLE
suci

### ISSUE THREAD

**Issue by stan1334** [SOCI/soci#1039]

**Comment by stan1334** [comment]
https://soci.sourceforge.net/doc/master/backends/odbc/


ODBC Driver	Bulk Read	Bulk Insert
MS SQL Server 2005	YES	YES


i cannot find the newest MS SQL Server version,so i want know
soic/odbc support MSSqlserver version list, thanks

@mloskot 
@vadz

**Comment by vadz** [comment]
SOCI should work with just about any SQL Server version but you ought to test it yourself. Running SOCI unit tests with your database would be a good start.

Also, please don't use the issue tracker for non-issues and don't tag people needlessly.

**Comment by stan1334** [comment]
> SOCI should work with just about any SQL Server version but you ought to test it yourself. Running SOCI unit tests with your database would be a good start.
> 
> Also, please don't use the issue tracker for non-issues and don't tag people needlessly.

thank U，I try use 2022 Version ，exec some demo AND UT after 。
