### ISSUE TITLE
How to create an empty rowset?

### ISSUE THREAD

**Issue by vatnic** [SOCI/soci#1057]
Good afternoon!
I did not find documentation on how to create an empty rowset, which is necessary for output from the method, when an exception occurs.
```cpp
rowset<row> DbConnector::selectData(wxWindow* win, wxString selectString)
{
    rowset<row> rowSet= (sql.prepare << "");
    try
    {
        rowSet= (sql.prepare << selectString);
        return rowSet;
    }
    catch (const std::exception& e)
    {
        wxMessageDialog messageDialog(win, e.what(), "Ошибка", wxOK);
        messageDialog.ShowModal();
    }
    return rowSet;
}
```
How to create an empty rowset without accessing the database?

**Comment by vadz** [comment]
I'm afraid a `rowset` already has to be valid currently. It wouldn't be difficult to add a default ctor to it and change `begin()` and `end()` to return the (same) invalid iterator for such an empty `rowset`. Any patches doing this would be welcome!

**Comment by asmwarrior** [comment]
I got here by searching. I just want to know how to got the `size` of the `rowset`. Maybe this issue is related, I see there is no function call named `size()`, so I have to iterate all the elements of the `rowset` to get the size of this `rowset`?
`

**Comment by asmwarrior** [comment]
[Add rowset::clear() · Issue #198 · SOCI/soci](https://github.com/SOCI/soci/issues/198)

This is a related discussion, but it is in year 2013, and no response of this issue.



Also, in this issue [ORM and rowset · Issue #1020 · SOCI/soci](https://github.com/SOCI/soci/issues/1020), some one gives a way to translate the `rowset `to `std::vector`.

**Comment by cstiborg** [comment]
I've created a PR which patches `rowset` with a default constructor. Feel free to comment.

**Comment by asmwarrior** [comment]
Is it possible to make a new tag(release) in the git? I just looked at the git commit history, the last git tag is 4.0.3, which is in beginning of the year 2022. Thanks.
