### ISSUE TITLE
soci 4.0 build Oracle backend on Windows

### ISSUE THREAD

**Issue by vassilux** [SOCI/soci#1092]
Hi alls,
I can not build Oracle backend on windows, core , odbc are build fine this is y commande line 
`cmake -G "Visual Studio 14" -DWITH_BOOST=OFF -DWITH_ORACLE=ON -DORACLE_INCLUDE_DIR=G:\Oracle\product\19.0.0\client_1\oci\include -DORACLE_LIBRARIES=G:\Oracle\product\19.0.0\client_1\oci\lib\msvc C:\soci-release-4.0`
Thanks for help

**Comment by vadz** [comment]
It's not really serious to open an issue without even showing the error message.

**Comment by vassilux** [comment]
So I can find error jsute warning with cmake 

`CMake Warning (dev) at C:/Program Files/CMake/share/cmake-3.28/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
  The package name passed to `find_package_handle_standard_args` (ORACLE)
  does not match the name of the calling package (Oracle).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  cmake/modules/FindOracle.cmake:84 (find_package_handle_standard_args)
  src/backends/CMakeLists.txt:17 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.`

I tried change CMaleLists.txt with 
`file(GLOB SOCI_CMAKE_FILES "${CMAKE_CURRENT_SOURCE_DIR}/*.cmake")
set(Oracle_INCLUDE_DIR "G:/Oracle/product/19.0.0/client_1/oci/include")
set(Oracle_LIBRARIES "G:/Oracle/product/19.0.0/client_1/oci/lib")`

Also tried with vcpkg 
core and odbc was generated well
I home I'm clear now

**Comment by vadz** [comment]
No, sorry not at all. If you don't get any errors, why can't you build it?

**Comment by vassilux** [comment]
I try to generate oracle backend and I don't understand why cmake generate juste core and odbc  backend 
maybe my cmake option are wrong ? 
`cmake -G "Visual Studio 14" -DWITH_BOOST=OFF -DWITH_ORACLE=ON -DORACLE_INCLUDE_DIR=G:\Oracle\product\19.0.0\client_1\oci\include -DORACLE_LIBRARIES=G:\Oracle\product\19.0.0\client_1\oci\lib\msvc C:\soci-release-4.0`

**Comment by vassilux** [comment]
I added to os PATH oci include and lib directories  and the VC2015 projet was create  and I can build oracle backend 
thanks

**Comment by vassilux** [comment]
I added to os PATH oci include and lib directories and the VC2015 projet was create and I can build oracle backend
thanks
