### ISSUE TITLE
CMake installation issues with soci as a dependency

### ISSUE THREAD

**Issue by jonasbhjulstad** [SOCI/soci#1094]
I get the following error when trying to install my library (`SBM_Database`)
```
CMake Error at _deps/soci-build/src/backends/empty/cmake_install.cmake:61 (file):
  file INSTALL cannot find
  "/home/man/Documents/SBM_Database/build/lib/libsoci_empty.so.4.1.0": No
  such file or directory.
Call Stack (most recent call first):
  _deps/soci-build/src/backends/cmake_install.cmake:47 (include)
  _deps/soci-build/src/cmake_install.cmake:52 (include)
  _deps/soci-build/cmake_install.cmake:51 (include)
  cmake_install.cmake:52 (include)
```
Soci was fetched using the following:
```
CPMFindPackage(
    NAME Soci
    GITHUB_REPOSITORY SOCI/soci
    GIT_TAG master
    OPTIONS
    "WITH_POSTGRESQL ON"
)
```

**Comment by Spixmaster** [comment]
That same issue needs to be circumventend in the [package for Arch Linux](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=soci). Take a look at it.

**Comment by vadz** [comment]
Sorry, no idea what's going on here and no time to debug it right now but if anybody has a fix, it would be welcome, of course.

**Comment by Krzmbrzl** [comment]
SOCI's install routines are completely rewritten in #1118 - I'm assuming that the present issue is fixed with my PR until proven otherwise (e.g. please try it out and report back)
