### ISSUE TITLE
How to read DATETIME(3) type in database?

### ISSUE THREAD

**Issue by q2013** [SOCI/soci#1121]
I want to get DATETIME(3) type data from the database, that is, accurate to the millisecond level of data. But now the soci library directly converts the date type of data into std::tm type, the millisecond data is lost, how can I get it?

**Comment by vadz** [comment]
This is currently not supported, although there is #1093 which could help.

**Comment by q2013** [comment]
Thank you for your answer. I converted the date type to string type  in the library, and then parsed it with my own wrapper date-time class.

**Comment by JoshuaVThomas** [comment]
Hi @q2013 . Can you help me with the implemetation. How did you do it?

**Comment by q2013** [comment]
I converted the std::tm to std::string in the source code.

> Hi [@q2013](https://github.com/q2013) . Can you help me with the implemetation. How did you do it?

**Comment by JoshuaVThomas** [comment]
@q2013 thanks for replying in a short note. I am not sure where you are doing the operation. I am using ODBC implementation and I modified the describe_column function where 

![Image](https://github.com/user-attachments/assets/dca7f42a-a38d-459c-bc20-d93155a1e52e)

I don't know and not sure if this would work. It would be so helpful if you could help me further on this.

**Comment by q2013** [comment]
> [@q2013](https://github.com/q2013) thanks for replying in a short note. I am not sure where you are doing the operation. I am using ODBC implementation and I modified the describe_column function where
> 
> ![Image](https://github.com/user-attachments/assets/dca7f42a-a38d-459c-bc20-d93155a1e52e)
> 
> I don't know and not sure if this would work. It would be so helpful if you could help me further on this.

I‘m using MYSQL but I think your change is OK. You can have a try.
