### ISSUE TITLE
failed to connect to mysql database after I upgrade the mariadbclient library inside the msys2

### ISSUE THREAD

**Issue by asmwarrior** [SOCI/soci#1123]
Hi, I have recently update the msys2 to the latest version, and soon I found that soci failed to connect to the mysql library.

Here is the details:

[soci+mariadbclient 3.3.8-1 failed to connect to a mysql database, while it works with 3.1.13(replace the libmariadb.dll with old one works) · Issue #19861 · msys2/MINGW-packages](https://github.com/msys2/MINGW-packages/issues/19861)

Maybe, this is caused that the mariadbclient 3.3.8 has the different interface with the mariadbclient 3.1.13.

Any idea how to fix this issue? Thanks.

**Comment by vadz** [comment]
This looks like mariadb installation problem, i.e. I'm pretty sure that just using its C API directly would fail too. IMO it's not a SOCI problem at all, so closing.

**Comment by asmwarrior** [comment]
Hi, @vadz , with the help of msys2 package devs, this issue is located and now fixed in the msys2, See that issue ([soci+mariadbclient 3.3.8-1 failed to connect to a mysql database, while it works with 3.1.13(replace the libmariadb.dll with old one works) · Issue #19861 · msys2/MINGW-packages](https://github.com/msys2/MINGW-packages/issues/19861)) for more details. 

Sorry about the noise.
