### ISSUE TITLE
Dates before year 1900 stored in Oracle as one hundred years earlier.

### ISSUE THREAD

**Issue by JaroslawCendrowski** [SOCI/soci#1135]
Observed on table with TIMESTAMP column type.
tm_year component of std::tm structure is negative then. The solution is to use Euclidean modulo instead of % operator when converting from std::tm to Oracle type..

**Comment by vadz** [comment]
Sorry, not on a Oracle expert by any means, so I don't really know what's going on here. If you can propose a PR fixing this, please do.
