### ISSUE TITLE
How to create database using soci in mysql?

### ISSUE THREAD

**Issue by q2013** [SOCI/soci#1149]
I want to connect to the mysql server with the soci library and use it to create a database.(like 'CREATE DATABASE person;') I find that I have to create a session with 'dbName'. 
![img_v3_02au_e82591b3-e18d-4cd4-a7d7-bb218e1982dg](https://github.com/SOCI/soci/assets/44694138/f0fe77d0-238b-4e60-8729-2e02e03129ca)

I can do this without passing dbName so that I can connect to the default database when I call mysql_real_connect(). What should I do next to create a new database and switch to it? Or is there another way?
![image](https://github.com/SOCI/soci/assets/44694138/42f68b84-fbf0-48d8-947e-393166cb8b93)

**Comment by vadz** [comment]
I don't think there is another way, you need to be able to connect to "mysql" database.
