### ISSUE TITLE
File "private/soci-trivial-blob-backend.h" missing

### ISSUE THREAD

**Issue by Spixmaster** [SOCI/soci#1153]
@Krzmbrzl, the commit #992 includes `#include <private/soci-trivial-blob-backend.h>` which is not present when installed with CMake.

**Comment by Krzmbrzl** [comment]
See my revamp cmake PR. I think there this should be fixed

**Comment by Spixmaster** [comment]
The header is used two times, https://github.com/search?q=repo%3ASOCI%2Fsoci%20%23include%20%3Cprivate%2Fsoci-trivial-blob-backend.h%3E&type=code.

**Comment by Krzmbrzl** [comment]
I had another look at this and am now in line with what @vadz said. That is, I misused private headers. Consequently, this is fixed in #1165
