### ISSUE TITLE
Faulty iterator check in oracle factory's get_key_value()

### ISSUE THREAD

**Issue by Jofagi** [SOCI/soci#1175]
For a connect string with a trailing '=', such as  `"password="`, this line causes an "iterator out of range" situation.

https://github.com/SOCI/soci/blob/a55c80984a447bf8c788a7d6a23ff93c022069fa/src/backends/oracle/factory.cpp#L45

I believe it should be `if ((i + 1) != end && *(i + 1) == '"') ` instead.

**Comment by vadz** [comment]
Thanks for reporting, this is fixed by #1176 (for the record, the same problem also existed in PostgreSQL backend).
