### ISSUE TITLE
Review uses of SOCI_POSTGRESQL_NOPREPARE and SOCI_POSTGRESQL_NOPARAMS options

### ISSUE THREAD

**Issue by mloskot** [SOCI/soci#122]
First, are we still interested in supporting PostgreSQL 7.x?

If we do not aim to support old PostgreSQL, then we can remove all the compatibility options like `SOCI_POSTGRESQL_NOPREPARE`, `SOCI_POSTGRESQL_NOPARAMS` and `SOCI_POSTGRESQL_NOBINDBYNAME`.

If we do want to keep support for PostgreSQL 7.x, then all those options have to be checked in action. Currently, building with `-DSOCI_POSTGRESQL_NOPARAMS=ON` leads to common tests failure.

It seems, nobody has tested SOCI with PostgreSQL 7.x for long time and we may have no capacity to test it regularly, but without testing we will likely break support for it and it may hold further development back.

Supporting combination of those configurations makes PostgreSQL backend implementation fairly complex with lots of interleaved execution paths and `#ifdef`s which rather should be cleaned up and simplified. So, I'd vote for dropping support for those options in SOCI 4.0.0

**Comment by jsonn** [comment]
I would say there is little value in supporting versions of PostgreSQL that are not supported by them either, at least without a good indication that someone requires such a need.

That said, at least SOCI_POSTGRESQL_NOPREPARE has a use right as discussed on the mailing list.

**Comment by mloskot** [comment]
:+1:  for clean up

**Comment by mloskot** [comment]
I'd like to complete this clean-up.

Can we work out an agreement about who old version of PostgreSQL SOCI 4 should support?

Would it be possible to follow the PostgreSQL End Of Life dates?
https://www.postgresql.org/support/versioning/

Thoughts? @msobczak  @vadz, you were recently active in the PostgreSQL area, thoughts?

**Comment by vadz** [comment]
I'd like to support at least the version in the previous stable Debian release (currently Jessie, 9.4). The earliest version we'd conceivably have to support would be 8.4 from CentOS 6.

**Comment by mloskot** [comment]
Support for PostgreSQL 9.0 or later should be a fair compromise.

**Comment by vadz** [comment]
Even 9.1, I don't think 9.0 was shipped in any important Linux distros.

**Comment by mloskot** [comment]
9 is just a round number :-)

**Comment by jsonn** [comment]
Well, I'd suggest to start from https://www.postgresql.org/support/versioning/. Given that upstream has/is about to deprecate 9.2, I see no point in supporting anything older.

**Comment by mloskot** [comment]
@jsonn Yup, we do https://github.com/SOCI/soci/issues/122#issuecomment-331744216

I guess, there is minor or no differences in the `libpq` API between 9.0 and 9.2, comparing to changes between 7 vs 9 or 8 vs 9.

If I'm correct, it doesn't really matter if we support 9.0+ or 9.2+, but for user/documentation it is easier to say SOCI supports 9.x.
