### ISSUE TITLE
Add timeout support for postgresql

### ISSUE THREAD

**Issue by alexott** [SOCI/soci#129]
this is just not to forget...

we can implement timeouts in postgresql backend by issuing the `SET SESSION statement_timeout TO NNN` command right after opening a connection to database. `NNN` is in milliseconds.

When getting corresponding error back, we can wrap it into separate exception.

P.S. I think, that this is possible to implement timeouts not only for postgesql backend....

**Comment by mloskot** [comment]
`sql << "SET statement_timeout = whatever";`
