### ISSUE TITLE
sqlite3_statement_backend::loadOne: database is locked

### ISSUE THREAD

**Issue by Syffs** [SOCI/soci#144]
Dears,

This might be related more to sqlite than SOCI itself, but I havn't found much information about this issue on the web, so I'm just asking here!

I'm using a connection pool and my sqlite is build with SQLITE_THREADSAFE, and while Read operations (select) don't seem to be an issue, Write ones (Update, Replace, Insert) keep poping the same issue:

```
sqlite3_statement_backend::loadOne: database is locked
```

Thanks in advance!

**Comment by mloskot** [comment]
Closing as related to SQLite and client-side workaround. SOCI can't really help, unless there's update in SQLite API, I guess.

**Comment by Spixmaster** [comment]
Concurrency with SQLite is possible by setting `PRAGMA journal_mode=WAL` once. As it is a database setting this mode persists for all connections. Some reference: https://til.simonwillison.net/sqlite/enabling-wal-mode
