### ISSUE TITLE
Set up postgression service for Travis CI

### ISSUE THREAD

**Issue by mloskot** [SOCI/soci#167]
This task is about enabling PostgreSQL test on http://www.postgression.com, where [apparently](https://groups.google.com/d/msg/travis-ci/v36cHwvMJnw/3ta3h1uxdBYJ) we could test against different versions of PostgreSQL.

**Comment by vadz** [comment]
Access to Postgression servers either doesn't to work at all from Travis or is too slow, so apparently this just can't be done.
