### ISSUE TITLE
sqlite4 backend ?

### ISSUE THREAD

**Issue by microcai** [SOCI/soci#187]
Hi, sqlite4 is out, can soci support sqlite4?

Did any one already done that port ?

**Comment by davidsummers** [comment]
I think you can close this issue now.

SQLite4 was just experimental and all lessons learned have been back-ported into SQLite3.

See: https://sqlite.org/src4/doc/trunk/www/index.wiki

**Comment by vadz** [comment]
Closing as indicated, thanks.
