### ISSUE TITLE
[fix] Remove -ansi when building on FreeBSD 10

### ISSUE THREAD

**Issue by johndickinson** [SOCI/soci#236]
It is necessary to remove the -ansi flag from SOCI_GCC_CLANG_COMMON_FLAGS in src/cmake/SociConfig.cmake when building on FreeBSD 10. Compiled using the following:

mkdir build
cd build
cmake -G "Unix Makefiles" -DWITH_ORACLE:BOOL=OFF ../../soci-3.2.2
gmake install

**Comment by jsonn** [comment]
The current combination of -ansi and -std=gnu++98 looks schizophrenic at least. It doesn't make sense to ask for one standard and overwrite it with the GNU extensions afterwards. As such, the -ansi can just be dropped.

**Comment by vadz** [comment]
Ah, I didn't realize both were used. This indeed doesn't make sense, let's drop `-ansi`.
