### ISSUE TITLE
error processing table with two fieldnames one of which is part of the other

### ISSUE THREAD

**Issue by juelle** [SOCI/soci#26]
table persons with two fields

```
passwd      VARCHAR(20),
passwd_klar VARCHAR(20),
```

This version works:

```
db << "INSERT INTO persons(passwd,passwd_klar) VALUES(:passwd, :passwd_klar)", soci::use(p);
```

This version does not work:

```
db << "INSERT INTO persons(passwd_klar,passwd) VALUES(:passwd_klar, :passwd)", soci::use(p);
```

Error is caused by:
file: statement.cpp
Method:

```
void statement_impl::bind(values & values)

       std::size_t const pos = query_.find(placeholder); 
        --> when searching for placeholder ":passwd" finds position of ":passwd_klar"
                      with nextChar = '_'.

    Thus the following condition does not hold
     if (nextChar == ' ' || nextChar == ',' ||
         nextChar == '\0' || nextChar == ')')
     {
     -->     ":passwd" is added to  values.add_unused
```

and is consequently not bound to the prepared statement (which in my case results in an "persons.passwd may not be NULL" error).

**Comment by mloskot** [comment]
This needs to be covered with a test and let's see if it is still an issue.

**Comment by mloskot** [comment]
Syntax used above is invalid, number of `use` parameters does not match
and it neither uses binding by name of single buffer into multiple placeholders.

```
db << "INSERT INTO persons(passwd,passwd_klar) VALUES(:passwd, :passwd_klar)", soci::use(p);
```

Anyhow, test for some sort of similar case has been added in #601
