### ISSUE TITLE
BUG problem on the second iteration in a rowset

### ISSUE THREAD

**Issue by d3roch4** [SOCI/soci#280]
when a rowset<row> is traversed for the second time does not work
sample:
rowset<row> columns = dataBase.prepare << "SELECT cols.DATA_TYPE, cols.COLUMN_NAME, refs.REFERENCED_TABLE_NAME\
                                              FROM INFORMATION_SCHEMA.COLUMNS as cols\
                                              LEFT JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE AS refs\
                                              ON refs.TABLE_SCHEMA=cols.TABLE_SCHEMA\
                                                  AND refs.REFERENCED_TABLE_SCHEMA=cols.TABLE_SCHEMA\
                                                  AND refs.TABLE_NAME=cols.TABLE_NAME\
                                                  AND refs.COLUMN_NAME=cols.COLUMN_NAME\
                                              WHERE cols.TABLE_SCHEMA='"+tableSchema+"'\
                                              AND cols.TABLE_NAME='"+table+"'";

for(rowset<row>::iterator column=columns.begin(); column!=columns.end(); column++) // this work
{
        relation = column->get<string>(2, "");
        if(relation.size())
            file <<  << relation << ".h\"";
}

for(rowset<row>::iterator column=columns.begin(); column!=columns.end(); column++) // not work
{
        tipo = typeDb2Cpp(column->get<string>(0));
        variable = column->get<string>(1);
        file << '\t' << tipo << " " << variable << ';' << endl;
}

**Comment by mloskot** [comment]
The rowset iterator is of category of input iterator, so it is not guaranteed that it is possible to pass through the same input iterator twice. 

Related/duplicate to #17 and #50
