### ISSUE TITLE
Deadlock in non-windows implementation of soci::connection_pool::try_lease

### ISSUE THREAD

**Issue by javerskulpa** [SOCI/soci#284]
Non-windows implementation of soci::connection_pool::try_lease:

```c++
bool connection_pool::try_lease(std::size_t & pos, int timeout)
{
    struct timespec tm;
    if (timeout >= 0)
    {
        // timeout is relative in milliseconds

        struct timeval tmv;
        gettimeofday(&tmv, NULL);

        tm.tv_sec = tmv.tv_sec + timeout / 1000;
        tm.tv_nsec = tmv.tv_usec * 1000 + (timeout % 1000) * 1000 * 1000;
    }

    int cc = pthread_mutex_lock(&(pimpl_->mtx_));
    if (cc != 0)
    {
        throw soci_error("Synchronization error");
    }

    while (pimpl_->find_free(pos) == false)
    {
        if (timeout < 0)
        {
            // no timeout, allow unlimited blocking
            cc = pthread_cond_wait(&(pimpl_->cond_), &(pimpl_->mtx_));
        }
        else
        {
            // wait with timeout
            cc = pthread_cond_timedwait(
                &(pimpl_->cond_), &(pimpl_->mtx_), &tm);
        }

        if (cc == ETIMEDOUT)
        {
            break;
        }
    }

    if (cc == 0)
    {
        pimpl_->sessions_[pos].first = false;
    }

    pthread_mutex_unlock(&(pimpl_->mtx_));

    return cc == 0;
}
```

The deadlock occurs always when these conditions are satisfied:
1. timeout >= 0
2. Connection pool is fully used (pimpl_->find_free(pos) == false)
3. tm.tv_nsec >= 1,000,000,000

It seems that function pthread_cond_timedwait expects value of tm.tv_nsec to be in range 0 .. 999,999,999 inclusive. Otherwise EINVAL is returned. But function try_lease sets the tm.tv_nsec to value (tmv.tv_usec * 1000 + (timeout % 1000) * 1000 * 1000) what results in range 0 .. 1,998,999,000. In case tm.tv_nsec >= 1,000,000,000, EINVAL is returned and while loop becomes endless loop consumming 100% of CPU. The endless loop also never release mutex pimpl_->mtx_, function pthread_cond_timedwait probably atomically release the mutex only when the timeout is valid. Other thread also cannot give any connection back to connection pool because they would need to acquire mutex pimpl_->mtx_ => deadlock.

Solution: fixing the timeout:

```c++
if (tm.tv_nsec >= 1000 * 1000 * 1000)
{
    ++tm.tv_sec;
    tm.tv_nsec -= 1000 * 1000 * 1000;
}
```

**Comment by vadz** [comment]
This looks correct to me, thanks. If you could please make a PR I'd gladly merge it.

**Comment by vadz** [comment]
Cherry picked into develop branch too in 21824a15b7974fc82279fdb31c043df5651164bc, thanks!
