### ISSUE TITLE
Merge master 3.2.3 into develop

### ISSUE THREAD

**Issue by mloskot** [SOCI/soci#303]
We have released 3.2.3.
The current `master` branch now hosts the snapshot of that release.
The current `develop` branch is being behind that release, because the recent changes in `master` have not been merged into `develop`.
The task is to merge the `master` so we don't loose fixes and improvements released in 3.2.3

I'm currently working on the merge. The merge is not an easy one due to structure changes and numerous conflicts.

It would be helpful if we could limit commits into `develop` for a couple of days, thanks.

**Comment by vadz** [comment]
Sorry to hear about the merge conflicts, I think they may be also due to the fact that some commits were applied to both branches already.

Have you tried using [git-imerge](https://github.com/mhagger/git-imerge)? IME it's very helpful with non trivial merges.

**Comment by mloskot** [comment]
@vadz No, I haven't tried git-merge, but looks interesting. Meanwhile, I've resolved all the conflicts and now it's matter of making the Travis CI green, see #304

**Comment by mloskot** [comment]
Done.
