### ISSUE TITLE
Drop GitFlow branching model

### ISSUE THREAD

**Issue by mloskot** [SOCI/soci#305]
The task is to drop GitFlow completely and switch back to the traditional role of **master** branch on GitHub. Released versions of SOCI will be maintained in **release/X.Y** branch and then **X.Y.Z** tags.
See https://sourceforge.net/p/soci/mailman/message/33648574/ for links to detailed discussion.

Based on [Moving Another Branch to Master on Github](https://mikegriffin.ie/blog/20140410-moving-another-branch-to-master-on-github/), here is the plan:

1. On Github, set the default branch to something other than **master**

1. Rename the **master**

        git branch -m master release/3.2

1. Rename the **develop**

        git branch -m develop master

1. Delete the **master** branch on Github

        git push origin :master

1. Push the new **master** to Github

        git push origin master:refs/heads/master

1. Push the **release/3.2** to Github

        git push origin release/3.2:refs/heads/release/3.2

1. Delete the **develop** branch on Github

        git push origin :develop

1. Have a tea!

**Comment by vadz** [comment]
Looks good to me (except for the item 8, I'd prefer a coffee)!

**Comment by mloskot** [comment]
Done (actually, I would do prefer a coffee too).

**Comment by mloskot** [comment]
Hmm, an interesting thing happened which I didn't expect.

While renaming the branches, I was sitting on the irc://irc.freenode.net/soci and once I deleted the **master**, the IRC channel received bulk notification from GitHub:

-----
<GitHub34> [soci] mloskot deleted master at 111b50a: http://git.io/vvLf9
<GitHub85> [soci] mloskot closed pull request #267: support blob on native level (master...master) http://git.io/FGwXZQ
<GitHub180> [soci] mloskot closed pull request #277: function describe_column changed to get all column properties via column_properties in the row class (master...mn_develop) http://git.io/6mMrng
<GitHub97> [soci] mloskot closed pull request #221: fixed bug with get_affected_rows() and user defined types (master...master) http://git.io/P2IG-Q
<GitHub8> [soci] mloskot closed pull request #3: Added timeout and charset parameters to mysql connection string (master...master) http://git.io/vvLfQ
<GitHub164> [soci] mloskot closed pull request #257: Avoid final_action() call during stack unwinding (master...issue/256) http://git.io/xOEitQ
<GitHub119> [soci] mloskot closed pull request #156: Fix the issue #136 across all backends. (master...136-reconnect-sigsegv) http://git.io/vvLfH
<GitHub102> [soci] mloskot closed pull request #288: Nested transaction support (master...nestedTransaction2) http://git.io/pEqh
<GitHub33> [soci] mloskot created master from develop (+0 new commits): http://git.io/vvLfx
<GitHub185> [soci] mloskot created release/3.2 at 111b50a (+0 new commits): http://git.io/vvLJt
<GitHub75> [soci] mloskot closed pull request #138: Support for logging query parameters (develop...feature/parameter_log) http://git.io/vvLJP
<GitHub141> [soci] mloskot closed pull request #115: Auto-reconnect if the connection goes bad during statement execution (develop...feature/psql_reconnect) http://git.io/DSmRSQ
<GitHub188> [soci] mloskot closed pull request #215: minor bug fixes and improvments (develop...bugs) http://git.io/vvLJX
<GitHub150> [soci] mloskot deleted develop at 4f570d7: http://git.io/vvLJi
<GitHub7> [soci] mloskot closed pull request #190: Time stamps from Postgres are UTC (develop...patch-2) http://git.io/lzIImQ
<GitHub178> [soci] mloskot closed pull request #245: Add logger class to allow customizing SOCI logging operations. (develop...better-query-log) http://git.io/zgV5Bw
<GitHub93> [soci] mloskot closed pull request #203: Add WITH_CXX11 configuration flag (currently for gcc and clang) (develop...develop) http://git.io/hxT6Uw
<GitHub133> [soci] mloskot closed pull request #195: Allow SOCI_LIBDIR to be set on the command line for easier packaging. (develop...develop) http://git.io/pQ9VxQ
<GitHub168> [soci] mloskot closed pull request #232: Handle SQL_NO_DATA return value from SQLDriverConnect (develop...fix-230) http://git.io/ebsQHQ

-----

I think I wouldn't notice, so kudos to the IRC channel :)

I'll re-open those Issues and PRs.

**Comment by mloskot** [comment]
The PRs targetting master have been reopened.

The handful of PRs targetting develop are still closed
-----
#190: Time stamps from Postgres are UTC (develop...patch-2)
#245: Add logger class to allow customizing SOCI logging operations. (develop...better-query-log) 
#203: Add WITH_CXX11 configuration flag (currently for gcc and clang) (develop...develop)
#195: Allow SOCI_LIBDIR to be set on the command line for easier packaging. (develop...develop)
#232: Handle SQL_NO_DATA return value from SQLDriverConnect (develop...fix-230)
-----

I will review them manually.
