### ISSUE TITLE
Port: Add WITH_CXX11 configuration flag (currently for gcc and clang) #203

### ISSUE THREAD

**Issue by mloskot** [SOCI/soci#310]
Renaming of the develop branch #305, caused unintentional closure of the #203 pull request.

This task is to review and port #203 to the current master branch.

**Comment by mloskot** [comment]
Done in #336, we've got `SOCI_CXX_C11` (default is OFF).

**Comment by lacek** [comment]
Are there plan to document this flag? Spent quite a while struggling with #256 until seeing this.
