### ISSUE TITLE
Packaging for Debian Jessie

### ISSUE THREAD

**Issue by OniDaito** [SOCI/soci#329]
Any thoughts on this? It looks like there is no candidate for Jessie, although there is a version for Sid. We are targeting Jessie here at QMUL. I've written up and submitted a pull request to the soci-pkg project but I suspect the maintainer isn't active on that project anymore. Could be wrong but it's not had a lot of love in the last couple of years.

**Comment by vadz** [comment]
I'd love to see SOCI in Jessie personally, but I'm pretty sure it's too late for it.

**Comment by mloskot** [comment]
@OniDaito The soci-pkg repo is not actively maintained, it's more ad-hoc maintained.
However, it's open for maintenance for anyone who's willing to update it.
If you are interested, you can become a committer and update the scripts there.

**Comment by OniDaito** [comment]
Fantastic! Yes, thats a big help. We are looking to get an actual debian / ubuntu repos setup here (QMUL) if we can. Too late for official release but maybe for these who want it, they can have a url for their sources.list

**Comment by mloskot** [comment]
@OniDaito Done. Thanks!

**Comment by bblough** [comment]
This is an old issue, but it's still open so I figured I'd comment.  Jessie is of course already released, but unless something changes (e.g., breakage that can't be fixed in time), SOCI will be in the next stable release (Stretch).

**Comment by OniDaito** [comment]
Oh thats cool! I've not looked at this project for a while, having been moved onto other things. I guess we can probably close this and look forward to Stretch

**Comment by mloskot** [comment]
Closing as suggested
