### ISSUE TITLE
Auto-generated documentation

### ISSUE THREAD

**Issue by OniDaito** [SOCI/soci#332]
I've been looking over the soci-pkg with lintian and I've been getting a few errors regarding the documentation. It made me wonder, is the documentation being auto-generated in anyway and was there a decision in the past not to use doygen or similar for any reason?

**Comment by mloskot** [comment]
No, there is no autogenerated documentation. Currently, SOCI follows the legacy of hand-crafted HTML pages. It's neither efficient nor it gives optimal results nowadays.

So, as per [SOCI 4 roadmap](https://github.com/SOCI/soci/wiki/Roadmap#version-400-future), I've been planning to re-work the whole website and documentation using [Sphinx](http://sphinx-doc.org/) and maintain everything in, currently empty, [soci.github.com](https://github.com/SOCI/soci.github.com).

I started a prototype ages ago, see https://github.com/mloskot/soci-doc

Why Sphinx? I believe in Makdown or reStructuredText. I like it more than Doxygen.

Ideas and actions welcome!

**Comment by vadz** [comment]
FWIW I have some experience with Sphinx and while I admit it generates nice to read documentation (see https://docs.readthedocs.org/en/latest/index.html for example), I didn't really like the complexity of dealing with it and I think just plain Markdown would be sufficient for SOCI needs.

**Comment by mloskot** [comment]
@vadz The reason I looked at Sphinx was two-fold:
1. Similarly to Doxygen, it can auto-generate API Reference (there is C++ plugin)
2. Markdown is needs a HTML/PDF/whatever compiler anyway. If we consider hosting on GitHub, this point is no longer valid (it used to be ~2011 though).

**Comment by vadz** [comment]
Good point about (1), I should have mentioned that my Sphinx experience was only with Python, not C++.

In any case, just to be perfectly clear: I definitely agree that Sphinx will be an improvement compared to the current situation. Which one of Sphinx, (just) Markdown or maybe recent Doxygen with Markdown support is the best choice is less clear but I think it should be for whoever does the actual work of setting up the new system and transforming the existing docs into it to decide.

**Comment by mloskot** [comment]
Right.

One more aspect to consider is hosting. I've assumed to keep hosting website+docs at http://soci.sf.net. So, it seemed natural that I generate everything with Sphinx, then upload HTML output to SF.net server.

We may, however, consider GitHub pages for hosting and redirect SF.net, though I'm not sure what's the current SF's policy about redirecting.

One way or another, we want to keep SourceForge as the SOCI end-user bay, for downloads, 
mailing lists, etc.

If I will pick up the task myself, I'll probably go for Sphinx for everything, website + docs, as I explained above.

**Comment by OniDaito** [comment]
SourceForge is where projects go to die :P Ok, a little flippant perhaps (couldn't help it! Sorry!) but I suspect that github pages might be the better option with the possibility of generating it all yourself locally with Sphinx or similar. I'm fairly pro markdown but I've not tried Sphinx.

**Comment by mloskot** [comment]
SOCI does not live on SF.net, it lives on GitHub :)
For the sake of respect to the SourceForge legacy and to the SOCI authors' choice, I keep using SF.net for downloads + mailing list + subdomain. However, all SOCI development happens here.

We need to do:
1. One off, refactor the website HTML files to Markdown.
2. Frequent task, generate Markdown files with the API reference
3. Frequent task, compile everything into HTML output, using GitHub Pages (on-demand) or Sphinx (locally).

Can we delegate the 2. to GitHub Pages too?

**Comment by OniDaito** [comment]
Yeah, tbh I do like SourceForge and miss it sometimes :)

These three things sound pretty good. Happy to do the gruntwork on number one, whilst we think about 2 and 3.

**Comment by mloskot** [comment]
PDAL, a C/C++ based project I'm also a contributor to, maintains website+docs this way:
* Markdown sources lives in the main repository: https://github.com/PDAL/PDAL/tree/master/doc
  * Sphinx is used to generate HTML output
* HTML output is uploaded to gh-pages repository: https://github.com/PDAL/pdal.github.io
  * The pdal.io website is hosted as gh-pages with static HTML content.

I like this approach.

**Comment by OniDaito** [comment]
Awesome! So going forward, I can change the HTML pages to markdown and submit a pull request?

**Comment by mloskot** [comment]
@OniDaito Yes, I'd appreciate.

In your fork, I'd suggest to create **new** subdirectory named `doc`, that would be home for new documentation. Once completed, we will delete the `docs` one as obsolete.

I will work on adding Sphinx' `conf.py` there.

**Comment by OniDaito** [comment]
First stab at the markdown version

https://github.com/OniDaito/soci/tree/master/doc

There are mistakes... I shall correct them!

**Comment by OniDaito** [comment]
Ok I think I've got the majority of the markdown stuff done. Its online at the above. Will check again later to make sure I've not made any mistakes in conversion.

**Comment by mloskot** [comment]
BTW, I also consider [cldoc](https://github.com/jessevdk/cldoc) as a compelling alternative to Sphinx.

**Comment by mloskot** [comment]
Docs has moved to Markdown #344 Thanks to @OniDaito for awesome efforts!

**Comment by mloskot** [comment]
I assume this long standing feature request has been addressed and SOCI documentation:

* moved to Markdown (see #344)
* uses MkDocs (see #566)
* is automatically built and deployed on CircleCI after every commit
  * first checked with [markdownlint](https://github.com/DavidAnson/markdownlint) (see df87eb1eb330b171872672c6c8f7f4202f8d3f01)
  * then generated and deployed (see 15eba50e8bbf6909b21f7ca0d504b6a163366116)

Note: 

1. The soci.sourceforge.net website is still in form of the few hand-written HTML
2. API reference is still hand-written, but in Markdown now. Perhaps this could be replaced with doxygen-generated Markdown. Proposals are welcome.
