### ISSUE TITLE
Mac OS: master branch fails to build on Yosemite

### ISSUE THREAD

**Issue by dunn** [SOCI/soci#334]
As of 2bf3aa7ed33c88945265ba7be4933c5e9720ad56

Build logs for: 
- [GCC](https://gist.github.com/dunn/414baf26442d9fa9c699)
- [Clang](https://gist.github.com/dunn/60fecfb4ded71e1aee54)

Stable release 3.2.3 from https://downloads.sourceforge.net/project/soci/soci/soci-3.2.3/soci-3.2.3.tar.gz works fine.

May be related to #258

**Comment by vadz** [comment]
Yes, this is exactly the same as #258 and I don't think it's useful to keep both of them open. FWIW you could try manually adding `--undefined-suppress` to `LDFLAGS` (sorry, I don't know how to do it with Cmake but I dare hope it should be possible) and check if it fixes the problem.

**Comment by mloskot** [comment]
@dunn Please, check fix proposed to #258
