### ISSUE TITLE
Building errors with mingw, linking and undef. reference

### ISSUE THREAD

**Issue by Superlokkus** [SOCI/soci#338]
Building of the soci master branch stopped working on my mingw /Win 7Prof. setup.

Building with default (without Boost, but with odbc backend) failed with following error/full log
```
Linking CXX shared library ..\..\..\bin\libsoci_empty_4_0.dll
CMakeFiles\soci_empty.dir/objects.a(factory.cpp.obj):factory.cpp:(.text+0xa3): u
ndefined reference to `__imp__ZN4soci16dynamic_backends16register_backendERKSsRK
NS_15backend_factoryE'
CMakeFiles\soci_empty.dir/objects.a(factory.cpp.obj):factory.cpp:(.text$_ZN4soci
15backend_factoryC2Ev[_ZN4soci15backend_factoryC2Ev]+0xf): undefined reference t
o `__imp__ZTVN4soci15backend_factoryE'
c:/progra~2/dev-cpp/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/4.8.1/../../../../
x86_64-w64-mingw32/bin/ld.exe: CMakeFiles\soci_empty.dir/objects.a(factory.cpp.o
bj): bad reloc address 0xf in section `.text$_ZN4soci15backend_factoryC2Ev[_ZN4s
oci15backend_factoryC2Ev]'
collect2.exe: error: ld returned 1 exit status
src\backends\empty\CMakeFiles\soci_empty.dir\build.make:294: recipe for target '
bin/libsoci_empty_4_0.dll' failed
```
Full log: https://gist.github.com/Superlokkus/d9a0de97e55556131a5e

When building without SOCI_TESTS a linking error occurs:
```
Linking CXX shared library ..\..\..\bin\libsoci_odbc_4_0.dll
collect2.exe: error: ld returned 255 exit status
src\backends\odbc\CMakeFiles\soci_odbc.dir\build.make:295: recipe for target 'bi
n/libsoci_odbc_4_0.dll' failed
mingw32-make.exe[2]: *** [bin/libsoci_odbc_4_0.dll] Error 1
mingw32-make.exe[2]: Leaving directory 'C:/Users/klm/Downloads/soci_build'
CMakeFiles\Makefile2:227: recipe for target 'src/backends/odbc/CMakeFiles/soci_o
dbc.dir/all' failed
```
Full log: https://gist.github.com/Superlokkus/a10f8c679188498ccc9f
Building with only SOCI_ODBC and SOCI_STATIC seemed to work, also building without tests worked with soci 3.2 on this setup.

**Comment by mloskot** [comment]
I recall some users reported linking failures related to the backend factory objects, like `extern SOCI_ODBC_DECL odbc_backend_factory const odbc;` perhaps correct exports were missing.

I don't use MinGW, so I can't check it myself.
BTW, MinGW setup for our Travis CI would be helpful, se #247

**Comment by OniDaito** [comment]
At the risk of being "well volunteered" I just this minute found this:
http://www.kitware.com/blog/home/post/877

**Comment by mloskot** [comment]
@OniDaito Thx, looks interesting. Should help those interested in building SOCI w/ MinGW to contribute updates to .travis.yml

**Comment by Superlokkus** [comment]
I could try to help to, but I'm a newbie to travis and the internals of soci. I don't have time until late July.

**Comment by mloskot** [comment]
@Superlokkus Don't worry, no rush. I may try to add MinGW to Travis myself, if I have a moment myself.

**Comment by snikulov** [comment]
@Superlokkus can we close this issue?

**Comment by mloskot** [comment]
Check MinGW job status on https://ci.appveyor.com/project/mloskot/soci. It's successful.

**Comment by Superlokkus** [comment]
Yes this can stay closed
