### ISSUE TITLE
Rename SOCI headers

### ISSUE THREAD

**Issue by mloskot** [SOCI/soci#342]
Picking up an old idea from #25, where I proposed to rename SOCI headers:
* rename `.h.` extension to `.hpp`
* replace `-` (dash) separator with `_`

Rationale:
* useful if one wants to install and use SOCI versions with both, old and post-#25 source tree layout.
* avoid potential names clashes like `error.h` in #335
* dash is not a common separator used in file names
* to me, `.hpp` and underscore are more C++'ish

Please, comment and give the thumb up or down to save or kill the idea.

**Comment by OniDaito** [comment]
Agreed. hpp is more the style. Nor is dash often used in header names really. +1

**Comment by vadz** [comment]
I agree that dashes in file names are relatively rare and so not such a great idea but I don't think it's worth breaking the existing code using the current names -- unless you want to provide wrappers with the old names for compatibility, but at this moment I don't think it's worth the extra trouble.

As for `.h` vs `.hpp` this is really cosmetic, while the latter might be considered more logical, both conventions are very widely used in C++ and it's definitely not worth renaming the headers just for the style points.

**Comment by mloskot** [comment]
No, I didn't want to provide any wrappers. I assume SOCI 4 can breaks existing code and if we want to break anything, SOCI 4 is the right moment to break things.

Yes, the change is cosmetic.

Simply, this is an old idea I considered that bubbled up and I decided to clear it, one way or another.
It's not critical in any way.

**Comment by vadz** [comment]
SOCI 4 is pretty much compatible with SOCI 3...

**Comment by mloskot** [comment]
Yes, but **if...*, then now :)
