### ISSUE TITLE
Mysql backend memory leaks due to mysql_library_init()

### ISSUE THREAD

**Issue by thibault-martinez** [SOCI/soci#349]
Hi,

It seems that mysql_init() implicitly calls mysql_library_init().
Unfortunately mysql_close() doesn't calls mysql_library_end(), resulting in 2 memory leaks.

You should explicitly call mysql_library_end() in your mysql_session_backend::clean_up() function.
https://github.com/SOCI/soci/blob/master/src/backends/mysql/session.cpp#L405

I'll do a pull request to add it.

Regards,

**Comment by mloskot** [comment]
Regarding "it seems", you likely refer to the remarks from the MySQL docs:

> In a nonmulti-threaded environment, mysql_init() invokes mysql_library_init() automatically as necessary. However, mysql_library_init() is not thread-safe in a multi-threaded environment, and thus neither is mysql_init(). Before calling mysql_init(), either call mysql_library_init() prior to spawning any threads, or use a mutex to protect the mysql_library_init() call. This should be done prior to any other client library call.

PR is welcome!

**Comment by thibault-martinez** [comment]
Absolutely !

The need to call mysql_library_end() is well explained in the [Mysql C API Function Overview](https://dev.mysql.com/doc/refman/5.0/en/c-api-function-overview.html)
> The purpose of calling mysql_library_init() and mysql_library_end() is to provide proper initialization and finalization of the MySQL library. For applications that are linked with the client library, they provide improved memory management. If you do not call mysql_library_end(), a block of memory remains allocated. (This does not increase the amount of memory used by the application, but some memory leak detectors will complain about it.) For applications that are linked with the embedded server, these calls start and stop the server.

**Comment by avidboarder** [comment]
It looks like a call to `mysql_thread_end()` is missing from `mysql_session_backend::clean_up()`
See https://dev.mysql.com/doc/refman/8.0/en/mysql-thread-end.html
