### ISSUE TITLE
How to pass dynamic multiple variables to query

### ISSUE THREAD

**Issue by redboltz** [SOCI/soci#354]
I'm looking for a way to pass multiple variables as query parameters dynamically.

```C++
std::vector<std::string> vs;
vs.push_back("key1");
vs.push_back("key2");
sql << "select * from mytable as t where t.field1 = :f1 and t.field2 = :f2", use(vs[0]), use(vs[1]);
```
I can pass the vector of string, vs, individually. My situation is the query string is generated dynamically. For example, comparison fields increase dynamically as follows:

select * from mytable as t where t.field1 = :f1 and t.field2 = :f2 and t.field3 = :f3 ...

However, I can't increase use() function dynamically. 'dynamically' means on run time.

I've tried to pass the vector of strings directly. It compiles but doesn't work. It seems that soci regards 'vs' to the parameter for bulk insertion.

```C++
sql << "select * from mytable as t where t.field1 = :f1 and t.field2 = :f2", use(vs);
```

I can concatenate query string that contains parameters using string manipulation or query transformation http://soci.sourceforge.net/doc/3.2/queries.html. However, it doesn't provide the way to avoid SQL injection. 

I also checked "Extending SOCI to support custom (user-defined) C++ types" http://soci.sourceforge.net/doc/3.2/exchange.html. However, I couldn't find a way to map user defined type, in this case std::vector<std::string> to multiple placeholders.

Is there any good way to do that?

I've posted it on the stack-overflow:
http://stackoverflow.com/questions/31023172/how-to-provide-the-values-corresponding-to-the-placeholders-in-soci

After I posted it, I noticed here.

**Comment by mloskot** [comment]
AFAIU, you want to pass `vector<string>` into query for, let's call it, vertical or column-wise expansion.
AFAICT, it is not possible, `vector<T>` can be used with, again, horizontal or row-wise, expansion as a row data carrier.

Typically, the protocol is that number of placeholders must match number of `use` occurrences.
User-defined data and ORM is an exception, where, N placeholders match 1 `use` occurrence.

You may try ORM with generated placeholders
```
namespace soci
{
    template<>
    struct type_conversion<MyVectorOfStrings>
    {
        typedef values base_type;

        static void from_base(values const & v, indicator /* ind */, MyVectorOfStrings & p)
        { ... }
    
        static void to_base(const MyVectorOfStrings & p, values & v, indicator & ind)
        {
		    int i = 0;
		    for (auto s : p)
			{ 
                // generate placeholders from V0...Vn where n is size of p
                v.set("V" + std::to_string(i);, s);
				i++;
            }
            ind = i_ok;
        }
    };
}
```

Then try something along these lines:
```
MyVectorOfStrings p = ...;
std::string query = "select * from mytable as t where ";
int i = 0;
for (auto s : p)
{ 
	if (i > 0) query += " and ";
    std::string si = std::to_string(i);
    query += "t.field" + si + "=:f" + si;
}
sql << query, use(p);
```

TBH, I have never tried to run it, so no idea if it would even work :-)

**Comment by vadz** [comment]
I'm not sure what the problem is exactly, i.e. how would you like to make it work, ideally. But it might be useful to note that `use()` is just a syntactic sugar and that you can also call `exchange()` directly on the statement -- and you can, of course, do it in a loop over all vector elements without any problems.

**Comment by mloskot** [comment]
On 26 June 2015 at 14:18, VZ <notifications@github.com> wrote:

> But it might be useful to note that use() is just a syntactic sugar and
> that you can also call exchange() directly on the statement
>
Good point. All the three flavours of public interfaces, sugar, core and
simple, are explained here:

http://soci.sourceforge.net/doc/3.2/interfaces.html

**Comment by redboltz** [comment]
@mloskot , @vadz, thank you for your comments. My problem has been solved. I use Core interface as follows instead of Sugar interface:
```C++
        session sql(sqlite3, "./test");

        std::vector<std::string> qs { "v1", "v2", "v3" }; // determined on run time

        int count;

        // Create query string dynamically
        std::stringstream ss;
        ss << "select count(*) from mytable as t where t.field1 = :f1";
        for (std::size_t i = 1; i < qs.size(); ++i) {
            ss << " and t.field" << i+1 << " = :f" << i+1;
        }

        // Give the values corresponding to the placeholders in the query string
        statement st(sql);
        for (auto const& e : qs) {
            st.exchange(use(e));
        }
        st.exchange(into(count));
        st.alloc();
        st.prepare(ss.str());
        st.define_and_bind();
        st.execute(true);

        std::cout << count << std::endl;
```

I appreciate your help!

**Comment by redboltz** [comment]
@mloskot , I also tested the approach that you suggested. It works! I modified a little.

```C++
using namespace soci;

struct MyVectorOfStrings : public std::vector<std::string> {
    using std::vector<std::string>::vector;
};

namespace soci
{
    template<>
    struct type_conversion<MyVectorOfStrings>
    {
        typedef values base_type;

        static void from_base(values const& v, indicator /* ind */, MyVectorOfStrings &p)
        {}

        static void to_base(const MyVectorOfStrings& p, values& v, indicator& ind) {
            for (auto s : p) v << s;
            ind = i_ok;
        }
    };
}

int main()
{
    try {
        session sql(sqlite3, "./test");

        MyVectorOfStrings qs { "v1", "v2", "v3" }; // determined on run time

        int count;

        sql << "select count(*) from mytable as t where t.field1 = :f1 and t.field2 = :f2 and t.field3 = :f3", use(qs), into(count);

        std::cout << count << std::endl;
    }
    catch (std::exception const &e) {
        std::cerr << "Error: " << e.what() << '\n';
    }
}
```
