### ISSUE TITLE
Memory leak when reusing statements

### ISSUE THREAD

**Issue by grisharav** [SOCI/soci#367]
I'm using Visual Studio 2013, ODBC backend. Table consists of single varchar 'Name' column
According to my tests the following code:

``` cpp
    auto sql = std::make_shared<soci::session>(parameters);
    std::string name;
    soci::statement st((sql->prepare << "INSERT INTO TestTable(Name) VALUES(:n)", use(name)));
    for (int j = 0; j < 10; ++j)
    {
        name = std::string("NameTest") + std::to_string(j);
         st.execute(true);
    }
```

Leaks 9/10 strings. The reason as far as I understand, is that in standard_use_type.cpp odbc_standard_use_type_backend::prepare_for_bind, for a string parameter a buf_ variable is allocated and is not released upon statement completion. Last string is being deleted in odbc_standard_use_type_backend::clean_up See http://sourceforge.net/p/soci/mailman/message/30008866/ for the same issue pretty much.

**Comment by grisharav** [comment]
Any updates on this?

**Comment by mloskot** [comment]
@grisharav I have no time to look at it. To move forward, I can only suggest you to submit pull request with a fix. Assuming it will correct the problem for you, and the builds on Travis CI are all green, I will be happy to merge it.

**Comment by snikulov** [comment]
Confirmed.
