### ISSUE TITLE
Building of very first file fails with mingw

### ISSUE THREAD

**Issue by Superlokkus** [SOCI/soci#369]
With the most recent master checkout (70085e8a0a6d0d) building with mingw fails now at the very first file. 
Although I already got one ticket ( #338 ) about building problems with mingw, I have opened this one, because I assume this is just a minor, different, one line correction bug.
```
C:\Users\klm\Downloads\soci_build>"C:\Program Files (x86)\Dev-Cpp\MinGW64\bin\mi
ngw32-make.exe"
Scanning dependencies of target soci_core
[  1%] Building CXX object src/core/CMakeFiles/soci_core.dir/backend-loader.cpp.
obj
C:\Users\klm\Downloads\soci\src\core\backend-loader.cpp:1:0: error: -fPIC ignore
d for target (all code is position independent) [-Werror]
 //
 ^
cc1plus.exe: all warnings being treated as errors
src\core\CMakeFiles\soci_core.dir\build.make:54: recipe for target 'src/core/CMa
keFiles/soci_core.dir/backend-loader.cpp.obj' failed
mingw32-make[2]: *** [src/core/CMakeFiles/soci_core.dir/backend-loader.cpp.obj]
Error 1
CMakeFiles\Makefile2:125: recipe for target 'src/core/CMakeFiles/soci_core.dir/a
ll' failed
mingw32-make[1]: *** [src/core/CMakeFiles/soci_core.dir/all] Error 2
Makefile:126: recipe for target 'all' failed
mingw32-make: *** [all] Error 2
```

**Comment by Superlokkus** [comment]
So I erased the `-fPIC` flag in the `SociConfig.cmake` file, but after that I got another build error:
```
[ 75%] Building CXX object src/backends/empty/CMakeFiles/soci_empty_static.dir/v
ector-use-type.cpp.obj
Linking CXX static library ..\..\..\lib\libsoci_empty_4_0.a
[ 75%] Built target soci_empty_static
Scanning dependencies of target soci_odbc
[ 77%] Building CXX object src/backends/odbc/CMakeFiles/soci_odbc.dir/blob.cpp.o
bj
In file included from C:/Users/klm/Downloads/soci/include/soci/odbc/soci-odbc.h:
31:0,
                 from C:\Users\klm\Downloads\soci\src\backends\odbc\blob.cpp:9:
C:/Program Files (x86)/Windows Kits/8.0/Include/um/windows.h:31:0: error: ignori
ng #pragma region Application [-Werror=unknown-pragmas]
 #pragma region Application Family
 ^
In file included from c:\progra~2\dev-cpp\mingw64\x86_64-w64-mingw32\include\min
windef.h:146:0,
                 from c:\progra~2\dev-cpp\mingw64\x86_64-w64-mingw32\include\win
def.h:8,
                 from C:/Program Files (x86)/Windows Kits/8.0/Include/um/windows
.h:164,
                 from C:/Users/klm/Downloads/soci/include/soci/odbc/soci-odbc.h:
31,
                 from C:\Users\klm\Downloads\soci\src\backends\odbc\blob.cpp:9:
C:/Program Files (x86)/Windows Kits/8.0/Include/um/winnt.h:82:25: fatal error: k
ernelspecs.h: No such file or directory
 #include <kernelspecs.h>
                         ^
cc1plus.exe: all warnings being treated as errors
compilation terminated.
src\backends\odbc\CMakeFiles\soci_odbc.dir\build.make:54: recipe for target 'src
/backends/odbc/CMakeFiles/soci_odbc.dir/blob.cpp.obj' failed
mingw32-make[2]: *** [src/backends/odbc/CMakeFiles/soci_odbc.dir/blob.cpp.obj] E
rror 1
CMakeFiles\Makefile2:317: recipe for target 'src/backends/odbc/CMakeFiles/soci_o
dbc.dir/all' failed
mingw32-make[1]: *** [src/backends/odbc/CMakeFiles/soci_odbc.dir/all] Error 2
Makefile:126: recipe for target 'all' failed
mingw32-make: *** [all] Error 2
```

**Comment by vadz** [comment]
I have no idea how it happens but MinGW shouldn't be using `windows.h` from the platform SDK, it can't compile it. If CMake picks it up automatically, it would be a bug in SOCI cmakefiles but I don't work with CMake so I don't know how to fix this.

**Comment by snikulov** [comment]
@Superlokkus Intermediate patch for MinGW build can be found here https://github.com/snikulov/soci/commit/709b07ff80102e35d0ec1640e9da736aa4e9ee2a
Could you please try it?
"MinGW Makefiles" should be generated with option "-DWITH_ODBC=OFF".
Or you need ODBC back-end explicitly?

**Comment by Superlokkus** [comment]
@snikulov Unfortunately I need the ODBC back-end, because it's my primary use case and I want to verify #287

**Comment by snikulov** [comment]
@Superlokkus ok. I've updated FindODBC module. Could you please try ea4976f16889aed03f3b3f2c928e5b42dcdc2544 and check if it work for you?

**Comment by Superlokkus** [comment]
Didn't work: (longer version see https://gist.github.com/Superlokkus/bbd9f376a2eea4466268 )
"
[ 76%] Building CXX object src/backends/odbc/CMakeFiles/soci_odbc.dir/standard-i
nto-type.cpp.obj
C:\Users\klm\Downloads\soci\src\backends\odbc\standard-into-type.cpp: In member
function 'virtual void soci::odbc_standard_into_type_backend::post_fetch(bool, b
ool, soci::indicator*)':
C:\Users\klm\Downloads\soci\src\backends\odbc\standard-into-type.cpp:175:53: err
or: ISO C++98 does not support the 'I' scanf flag [-Werror=format=]
           if (sscanf(buf_, "%" LL_FMT_FLAGS "d", &ll) != 1)
                                                     ^
C:\Users\klm\Downloads\soci\src\backends\odbc\standard-into-type.cpp:175:53: err
or: format '%d' expects argument of type 'int*', but argument 3 has type 'long l
ong int*' [-Werror=format=]
C:\Users\klm\Downloads\soci\src\backends\odbc\standard-into-type.cpp:183:53: err
or: ISO C++98 does not support the 'I' scanf flag [-Werror=format=]
           if (sscanf(buf_, "%" LL_FMT_FLAGS "u", &ll) != 1)
                                                     ^
C:\Users\klm\Downloads\soci\src\backends\odbc\standard-into-type.cpp:183:53: err
or: format '%u' expects argument of type 'unsigned int*', but argument 3 has typ
e 'long long unsigned int*' [-Werror=format=]"

**Comment by snikulov** [comment]
@Superlokkus updated with 741faae6fd6906e6dbab49137b30920dd7dc43f0.
Could you please check?
BTW, I have another error in boost/optional.hpp.
Do you use boost and if yes, which version?

**Comment by Superlokkus** [comment]
Building with soci_shared didn't work (linker crashed) but at least soci static built.
Currently I built without boost, would it help if I built it with?

With dynamic, without empty and C++11 flag, commit 741faae6fd6906e6dbab49137b30920dd7dc43f0

Linking CXX static library ..\..\lib\libsoci_core_4_0.a
[ 67%] Built target soci_core_static
Scanning dependencies of target soci_odbc
[ 69%] Building CXX object src/backends/odbc/CMakeFiles/soci_odbc.dir/blob.cpp.o
bj
[ 71%] Building CXX object src/backends/odbc/CMakeFiles/soci_odbc.dir/factory.cp
p.obj
[ 73%] Building CXX object src/backends/odbc/CMakeFiles/soci_odbc.dir/row-id.cpp
.obj
[ 75%] Building CXX object src/backends/odbc/CMakeFiles/soci_odbc.dir/session.cp
p.obj
[ 76%] Building CXX object src/backends/odbc/CMakeFiles/soci_odbc.dir/standard-i
nto-type.cpp.obj
[ 78%] Building CXX object src/backends/odbc/CMakeFiles/soci_odbc.dir/standard-u
se-type.cpp.obj
[ 80%] Building CXX object src/backends/odbc/CMakeFiles/soci_odbc.dir/statement.
cpp.obj
[ 82%] Building CXX object src/backends/odbc/CMakeFiles/soci_odbc.dir/vector-int
o-type.cpp.obj
[ 83%] Building CXX object src/backends/odbc/CMakeFiles/soci_odbc.dir/vector-use
-type.cpp.obj
Linking CXX shared library ..\..\..\bin\libsoci_odbc_4_0.dll
collect2.exe: error: ld returned 255 exit status
src\backends\odbc\CMakeFiles\soci_odbc.dir\build.make:296: recipe for target 'bi
n/libsoci_odbc_4_0.dll' failed
mingw32-make[2]: *** [bin/libsoci_odbc_4_0.dll] Error 1
CMakeFiles\Makefile2:227: recipe for target 'src/backends/odbc/CMakeFiles/soci_o
dbc.dir/all' failed
mingw32-make[1]: *** [src/backends/odbc/CMakeFiles/soci_odbc.dir/all] Error 2
Makefile:126: recipe for target 'all' failed
mingw32-make: *** [all] Error 2

C:\Users\klm\Downloads\soci_build>

**Comment by snikulov** [comment]
@Superlokkus 
 > Currently I built without boost, would it help if I built it with?

Not at that moment.
Could you please provide me with additional info?
 - mingw version
 - cmake version
 - cmake arguments you're using to generate project

Because
```cmake .. -G"MinGW Makefiles" -DWITH_BOOST=OFF```
```cmake --build .```

with 
```
c:\WORK\GitHub\dev\soci\build.mingw>gcc --version
gcc (x86_64-posix-seh-rev1, Built by MinGW-W64 project) 4.8.3
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


c:\WORK\GitHub\dev\soci\build.mingw>cmake --version
cmake version 3.2.2
```
works for me.

**Comment by Superlokkus** [comment]
gcc (tdm64-2) 4.8.1
cmake 3.0.1
GNU Make 3.82.90
Built for i686-pc-mingw32

I guess I shall update? 

I'm using the cmake GUI:
```

[1;4;34mConfiguring SOCI:[0m 
SOCI_VERSION                             = 4.0.0 
SOCI_ABI_VERSION                         = 4_0 
SOCI_SHARED                              = OFF 
SOCI_STATIC                              = ON 
SOCI_TESTS                               = OFF 
SOCI_CXX_C11                             = OFF 
[1;4;34mLooking for SOCI dependencies:[0m 
[1;36mThreads:[0m 
CMAKE_THREAD_LIBS_INIT                   =  
[1;31mBoost:[0m [31mdisabled, since WITH_BOOST=OFF[0m 
[1;31mMySQL:[0m [31mdisabled, since WITH_MYSQL=OFF[0m 
[1;36mODBC:[0m 
ODBC_INCLUDE_DIR                         = C:/Program Files (x86)/Windows Kits/8.0/Include/um 
ODBC_LIBRARIES                           = C:/Windows/System32/odbc32.dll 
[1;31mOracle:[0m [31mdisabled, since WITH_ORACLE=OFF[0m 
[1;31mPostgreSQL:[0m [31mdisabled, since WITH_POSTGRESQL=OFF[0m 
[1;31mSQLite3:[0m [31mdisabled, since WITH_SQLITE3=OFF[0m 
[1;31mFirebird:[0m [31mdisabled, since WITH_FIREBIRD=OFF[0m 
[1;31mDB2:[0m [31mdisabled, since WITH_DB2=OFF[0m 
[1;4;34mConfiguring SOCI core library:[0m 
SOCI_CORE_TARGET                         = soci_core 
SOCI_CORE_TARGET_OUTPUT_NAME             = soci_core_4_0 
SOCI_CORE_DEPS_LIBS                      =  
SOCI_CORE_INCLUDE_DIRS                   = C:/Users/klm/Downloads/soci_build C:/Users/klm/Downloads/soci/include C:/Users/klm/Downloads/soci/include/private C:/Users/klm/Downloads/soci_build/src/core 
WITH_BOOST                               = OFF 
COMPILE_DEFINITIONS                      = SOCI_ABI_VERSION="4_0" SOCI_LIB_PREFIX="libsoci_" SOCI_LIB_SUFFIX=".dll" SOCI_DEBUG_POSTFIX="" 

[1;4;34mConfiguring SOCI backend libraries:[0m 
[1;32mODBC - SOCI backend for ODBC[0m 
SOCI_ODBC                                = ON 
SOCI_ODBC_TARGET                         = soci_odbc 
SOCI_ODBC_OUTPUT_NAME                    = soci_odbc_4_0 
SOCI_ODBC_COMPILE_DEFINITIONS            = SOCI_ABI_VERSION="4_0" HAVE_ODBC=1 
SOCI_ODBC_INCLUDE_DIRECTORIES            = C:/Users/klm/Downloads/soci_build C:/Users/klm/Downloads/soci/include C:/Users/klm/Downloads/soci/include/private C:/Users/klm/Downloads/soci/include/private 

[1;4;34mConfiguring SOCI tests:[0m 

Configuring done
Generating done
```

**Comment by snikulov** [comment]
@Superlokkus Well, I'm not convince you to update. But I think it's good idea.
Investigate what's wrong with linker (tdm64-2) gcc 4.8.1 is not in list of my goals now ;)

**Comment by Superlokkus** [comment]
@snikulov Well I just updated cmake (which did not make any difference) and it is the latest stable release of mingw.

**Comment by snikulov** [comment]
@Superlokkus I think it's not exactly true. 
Latest here http://tdm-gcc.tdragon.net/download is 4.9 and 5.1. Perhaps somewhere in bug-tracker you can find issues with linker.
Also here http://mingw-w64.org/doku.php/download you can get 4.8.2 and 4.8.3

**Comment by Superlokkus** [comment]
@snikulov I meant original mingw, but I wasn't aware that I use the tdm version already. I will it update in the next days or switch to MS MVC

**Comment by snikulov** [comment]
@Superlokkus Could you please verify this issue with pull request #393?
It should work now (at least Appveyor-CI does not complain).

**Comment by snikulov** [comment]
@fixed on master

**Comment by Superlokkus** [comment]
Building soci_static with odbc worked, but failed with shared:
```
[ 83%] Linking CXX shared library ..\..\..\bin\libsoci_odbc_4_0.dll
collect2.exe: error: ld returned 5 exit status
src\backends\odbc\CMakeFiles\soci_odbc.dir\build.make:314: recipe for target 'bi
n/libsoci_odbc_4_0.dll' failed
mingw32-make[2]: *** [bin/libsoci_odbc_4_0.dll] Error 1
mingw32-make[2]: *** Deleting file 'bin/libsoci_odbc_4_0.dll'
CMakeFiles\Makefile2:251: recipe for target 'src/backends/odbc/CMakeFiles/soci_o
dbc.dir/all' failed
mingw32-make[1]: *** [src/backends/odbc/CMakeFiles/soci_odbc.dir/all] Error 2
Makefile:137: recipe for target 'all' failed
mingw32-make: *** [all] Error 2
```

**Comment by snikulov** [comment]
@Superlokkus as we already discussed here, could you please update your mingw tool-set?

**Comment by Superlokkus** [comment]
@snikulov Oh I'm sorry I forgot, yeah thank you very much for the fix. Issue can stay closed :-)
