### ISSUE TITLE
Boost 1.58.0 fails static assertion when streaming optional w/o optional_io header

### ISSUE THREAD

**Issue by musopr** [SOCI/soci#370]
Boost 1.5.8 fails a static assertion when trying to stream an optional (ref: [#10825](http://www.boost.org/users/history/version_1_58_0.html)).

It seems that including boost/optional/optional_io.hpp is required as of version 1.5.8 to prevent a bug that occurs when streaming optional objects. Including this header in soci/boost-optional.h seems to resolve the issue.

**Comment by mloskot** [comment]
Thanks for the report. Pull request is welcome.

**Comment by snikulov** [comment]
@musopr then submit pull request :) :+1:
