### ISSUE TITLE
Clang warnings preventing compilation

### ISSUE THREAD

**Issue by musopr** [SOCI/soci#374]
Hi,

From soci-sqlite3.h I'm getting a number of occurrences of:
warning: anonymous types declared in an anonymous union are an extension [-Wnested-anon-types]

And from type-conversion.h, a number of occurrences of:
warning: field 'ownInd_' is uninitialized when used here [-Wuninitialized]

I can't seem to be able to pass in their negations via -DCMAKE_CXX_FLAGS either, which seems to be due to the ordering of the flags.

I've gotten around this by editing SOCI_GCC_CLANG_COMMON_FLAGS in SociCongif.cmake, on my machine, but I'm not sure if this is the preferred way to handle this.

**Comment by mloskot** [comment]
I haven't checked the actual code, but any chance to get rid of those warnings by fixing the code?

**Comment by snikulov** [comment]
@mloskot Clang emit uninitialized warnings, which seems to me serious enough. 

Anonymous structures/unions was introduced not long ago with @ArnaudD-FR  in f1f0162bd9844a40b3533c4f036a370adf79f264 and we can just remove it with ```-Wno-anon-types``` or name it :)

**Comment by mloskot** [comment]
@snikulov I'm in favour of naming any unonymous type.

**Comment by snikulov** [comment]
@musopr should be fixed as of https://github.com/SOCI/soci/commit/91fb559f04c3ac3253208763259249a5a6f683d6
If problem still exist, please submit another issue.

**Comment by musopr** [comment]
Thank you @snikulov, it compiles okay now.
