### ISSUE TITLE
soci-3.2.3/backends/mysql/session.cpp:202: bad if test ?

### ISSUE THREAD

**Issue by dcb314** [SOCI/soci#377]
soci-3.2.3/backends/mysql/session.cpp:202]: (style) A pointer can not be negative so it is either pointless or an error to check if it is.

Source code is

            *port = std::atoi(val.c_str());
            if (port < 0)
            {
                throw soci_error(err);
            }

Suggest new code

            *port = std::atoi(val.c_str());
            if (*port < 0)
            {
                throw soci_error(err);
            }

**Comment by mloskot** [comment]
Good catch!
We'd be thankful for pull request, either against the [release/3.2](https://github.com/SOCI/soci/tree/release/3.2) branch or the master.

**Comment by dcb314** [comment]
>Good catch!

You are welcome.

>We'd be thankful for pull request

Sorry, no can do. Someone else will be in a better position than me to do this.
