### ISSUE TITLE
Can't run SOCI tests under Windows using ODBC data source

### ISSUE THREAD

**Issue by picant** [SOCI/soci#396]
Environment:
Windows 8.1. 64 bit
ODBC and MS SQL
MSVC 2013

Had a problem trying to run tests using command 'ctest -VV -C Debug' for ODBC soci build. Tests ran but each asked about the data source (see attached screenshot) and after specified the password. Because there are many tests it makes it not practical to run them as one has to enter same information over and over again (I gave up after entering this about 5 times). Consider changing tests to accept a db connection string that includes driver name, server, login and password. Something like:

Driver={SQL Server};Server=192.168.11.54\SPSQL;Uid=sa;Pwd=Master10

![soci_issue_384_test_run](https://cloud.githubusercontent.com/assets/14172933/9985569/818235c2-6071-11e5-97b9-aa5b97649cb7.JPG)

**Comment by mloskot** [comment]
Historically, ODBC tests assume use of FILEDSN, see `tests/odbc/test-mssql.dsn`.

Perhaps it could be improved with the use of SOCI 3.2+ feature of [connection_parameters](http://soci.sourceforge.net/doc/3.2/connections.html).

**Comment by snikulov** [comment]
@mloskot Well, I suspect, the problem almost in add_test :)

```
      add_test(${TEST_TARGET}
        ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/${TEST_TARGET}
        ${${TEST_CONNSTR_VAR}})
```

here we got 
-- SOCI_ODBC_TEST_ACCESS_CONNSTR            = test-access.dsn
without full path to dsn. 
Test runs out of the source and test driver unable to find this file.
Perhaps we need pass connection string as absolute path to dsn.
Will check it soon.

**Comment by mloskot** [comment]
This is default setting, legacy from previous tests configuration where it was assumed that user specifies FILEDNS location as CMake argument. That's exactly what Travis CI did

```
cmake \
-DSOCI_ODBC_TEST_MYSQL_CONNSTR="FILEDSN=${PWD}/../backends/odbc/test/test-mysql.dsn;"
```

See https://github.com/SOCI/soci/blob/release/3.2/bin/ci/script_odbc.sh

**Comment by snikulov** [comment]
well, but for Windows it'll not work, unless you're using msys shell.

**Comment by snikulov** [comment]
@mloskot Ideally, the best way to use cmake is to avoid usage of platform specific scripts
so command sequence
```
cmake ..
cmake --build . 
ctest -VV 
```
should work on any platform.

But real world is far from ideal :)

**Comment by snikulov** [comment]
@picant in you case the better way is provide path to MSSQL DSN file as @mloskot suggested during project generation.

for example
```
cmake -DSOCI_ODBC_TEST_MSSQL_CONNSTR= < path to DSN with your connection parameters > .......
```
This should save your time with MSSQL.

AFAIK, other backends tests can be skipped using ctest command line.

So anyway it can be closed as WAE (work as expected).

**Comment by mloskot** [comment]
Closing.
If anyone would have suggestion how to improve running the ODBC tests, please submit a new PR. Thanks.
