### ISSUE TITLE
conversion_use_type misses members initialization

### ISSUE THREAD

**Issue by mloskot** [SOCI/soci#412]
This is follow up of #411 PR which pointed out this issue

The ownInd_ is passed to the base class before it is initialized.
This allows it to compile, however, it should be cleaned up.

**Comment by snikulov** [comment]
@mloskot we have #374 regarding this issue. So we have duplicate here.

**Comment by mloskot** [comment]
On 6 October 2015 at 15:49, Sergei Nikulov <notifications@github.com> wrote:

> @mloskot <https://github.com/mloskot> we have #374
> <https://github.com/SOCI/soci/issues/374> regarding this issue. So we
> have duplicate here.
>

If we do, then sorry for this duplicate - I was being lazy and didn't check.

**Comment by snikulov** [comment]
Dup for #374
