### ISSUE TITLE
Fix discrepency between SOCI_USE_BOOST and HAVE_BOOST

### ISSUE THREAD

**Issue by mloskot** [SOCI/soci#433]
The issue has been revealed in #429 
Between 3.2.2 and 3.2.3, role of `HAVE_BOOST` has changed and it disconnected from `SOCI_USE_BOOST` legacy.

In SOCI 3.2.3 (and current master too) `HAVE_BOOST` controls the Boost support in SOCI.
The `SOCI_USE_BOOST` is still dangling in the all-in-one header `soci.h` and in fact, it should be automatically defined if `HAVE_BOOST` is defined - that is missing, unfortunately.

Sources and CMake need to rely on single definition that will also be required while building SOCI clients.

Documentation needs updating as it mentions the old `SOCI_USE_BOOST` only.

**Comment by ArnaudD-FR** [comment]
Even if role of `HAVE_BOOST` has changed I don't think keeping it is a good idea. This macro name is too generic. `SOCI_USE_BOOST` has a better name.

I checked on SOCI 3.2 branch and both macro exist, that maybe why I made this mistake and introduced this regression.

We will have to to support both macro for a while or use version 4.0 to correctly handle this.

**Comment by ArnaudD-FR** [comment]
Lets continue with my latest message from issue #429.

I think that SOCI users shouldn't care about having correct definitions when they build a program using SOCI library and it can cause error if they forget one.

So the idea is to automatically put all definitions in a single file explaining how the library as been built.

Currently my commit ArnaudD-FR@882bff3a2903c9a1688ce8028734ba2bc421a6a5 is an example and only show  the SOCI_USE_BOOST macro definition but this is the main idea.

**Comment by mloskot** [comment]
On 29 October 2015 at 21:53, ArnaudD-FR <notifications@github.com> wrote:

> Even if role of HAVE_BOOST has changed I don't think keeping it is a good
> idea. This macro name is too generic. SOCI_USE_BOOST has a better name.
>

I was thinking of replacing both with new macro SOCI_HAVE_BOOST and place
it in generated config header.
The HAVE indicates clearly, particular build/package of SOCI has Boost
support built-in.


> We will have to to support both macro for a while or use version 4.0 to
> correctly handle this.
>

As far as I'm concerned, SOCI 4.0 can wipe old macros and introduce new
ones.

For SOCI 3.x, I'm not in favour of doing anything, or perhaps just update
docs in release/3.2 branch to indicate requirement of HAVE_BOOST while
building a client.

**Comment by mloskot** [comment]
On 30 October 2015 at 09:38, ArnaudD-FR <notifications@github.com> wrote:

> I think that SOCI users shouldn't care about having correct definitions
> when they build a program using SOCI library and it can cause error if they
> forget one.


Yes, definitely users should not care about that.
In fact, there is almost no obvious way for users to know what features are
built-in and what macros they should use to match those features.

> Currently my commit ArnaudD-FR@882bff3
> <https://github.com/ArnaudD-FR/soci/commit/882bff3a2903c9a1688ce8028734ba2bc421a6a5>
> is an example and only show the SOCI_USE_BOOST macro definition but this is
> the main idea.
>

Looks good. Just two comments:

1. Rename SOCI_USE_BOOST with SOCI_HAVE_BOOST?
2. Rename header from soci-definitions.h to soci-config.h?
3. We already have CMake option WITH_BOOST used to request CMake to try to
find Boost or to disable the lookup. I don't think we need any other public
CMake option like SOCI_USE_BOOST or similar. Simply, if CMake finds Boost,
then SOCI_HAVE_BOOST is defined in the config header.

What do you think?

**Comment by ArnaudD-FR** [comment]
> I was thinking of replacing both with new macro SOCI_HAVE_BOOST and place it in generated config header. The HAVE indicates clearly, particular build/package of SOCI has Boost support built-in.

OK for this name. Any macro used in header files have to be prefixed by SOCI_

> As far as I'm concerned, SOCI 4.0 can wipe old macros and introduce new ones. For SOCI 3.x, I'm not in favour of doing anything, or perhaps just update docs in release/3.2 branch to indicate requirement of HAVE_BOOST while building a client.

fine.

**Comment by ArnaudD-FR** [comment]
> 1. Rename SOCI_USE_BOOST with SOCI_HAVE_BOOST?
OK

> 2. Rename header from soci-definitions.h to soci-config.h?
I create this new one because soci-config.h already exists. But as it includes only soci-plateform.h we can extend it.

> 3. We already have CMake option WITH_BOOST used to request CMake to try to find Boost or to disable the lookup. I don't think we need any other public CMake option like SOCI_USE_BOOST or similar. Simply, if CMake finds Boost, then SOCI_HAVE_BOOST is defined in the config header.
Yes, no duplicated CMake option. It just that CMake replace  definitions in ".in" file using variable names. So if boost is found by CMake, we must define a CMake variable with the same name as the macro

**Comment by mloskot** [comment]
> > 2 Rename header from soci-definitions.h to soci-config.h?
>
> I create this new one because soci-config.h already exists. But as it includes only soci-plateform.h we can extend it.

I'd suggest to extend the existing soci-config.h - make it a generated header. The `config` is more common naming for such purpose.

**Comment by snikulov** [comment]
@mloskot Can we close this? AFAIU it was merged with pull https://github.com/SOCI/soci/pull/435

**Comment by mloskot** [comment]
@snikulov Yes, good catch.
