### ISSUE TITLE
C++11 #define should be in soci-config.hpp defined

### ISSUE THREAD

**Issue by qwertzui11** [SOCI/soci#437]
instead of in 
cmake/SociConfig.cmake:88
add_definitions(-DSOCI_CXX_C11)
the define SOCI_CXX_C11
should be added to the soci-config.h
else everyone, who wants to use the resulting build, has to set the flag SOCI_CXX_C11 too.

**Comment by mloskot** [comment]
Good catch, thanks.
It would also need to be renamed to `SOCI_HAVE_CXX_C11` to follow convention we discussed in #435.

**Comment by qwertzui11** [comment]
nice! thx!
