### ISSUE TITLE
Compile errors

### ISSUE THREAD

**Issue by cipriancus** [SOCI/soci#439]
Good day ! I'm new to SOCI and I'm having some problems while compiling

I ran  g++ file.cpp -I/usr/local/include/soci  -I/home/u01/app/oracle/product/12.1.0/dbhome_1/rdbms/
public/ -lsoci_core  -lsoci_oracle -ldl -lpq

and I get some errors  ( attached the error file ). Could you please spare some advice ? Thank you !
[t.txt](https://github.com/SOCI/soci/files/68506/t.txt)

**Comment by ArnaudD-FR** [comment]
Can you also attach source code?

And which SOCI release are you trying to use?

**Comment by cipriancus** [comment]
Thanks for the response

 !I'm running the latest version, soci 3.2.3. You want the file.cpp source code ? (if so, I attached it)

[file.txt](https://github.com/SOCI/soci/files/68535/file.txt)

**Comment by ArnaudD-FR** [comment]
The problem is coming from type-conversion-traits.h that does not include `error.h`. I will submit a PR for this issue.

For the moment, can you try to add `#include <soci-backend.h>` before `#include <soci.h>`.

**Comment by ArnaudD-FR** [comment]
I just try to compile your file and I don't get error.

I believe there is some duplicated headers name with your second search path `/home/u01/app/oracle/product/12.1.0/dbhome_1/rdbms/public/`

Instead of including `"soci.h"`, try to include `<soci/soci.h>` and use search path `/usr/local/include` instead of `/usr/local/include/soci`

Don't use `""` when including files not in current directory, always use `<>`

**Comment by cipriancus** [comment]
Thank you for the help. I installed the framework again and now it appears to be working, it doesn't print anything but still...better than nothing. Will try to debug

**Comment by cipriancus** [comment]
The program doesn't give me an error but neither does it give me a output. Is there a way to debug ? The standard gdb does not appear to work

[source.txt](https://github.com/SOCI/soci/files/69485/source.txt)

**Comment by ArnaudD-FR** [comment]
First if you want to use debugger you have to add debug symbols using `-g` in gcc command line.

Seconly, you are using `stdout` (`printf`) to print informations to console, `stdout` is buffered, so it is only flushed once buffer is full or you request it.

To be sure to see your logs use `fprintf(stderr, "%d\n", linii);`

**Comment by snikulov** [comment]
@cipriancus If you have some questions regarding SOCI lib usage, please use soci-users@lists.sourceforge.net mail list first.
Thank you.
