### ISSUE TITLE
SOCI doesn't define SOCI_HAVE_CXX_C11 for VS2015

### ISSUE THREAD

**Issue by Cleroth** [SOCI/soci#441]
VS2015 seems to support every C++11 in SOCI, but still doesn't get that defined. I just spent an entire day figuring out why I wasn't able to catch exceptions from SOCI queries. The reason? SOCI is throwing from a destructor even when it's not supported (or thinks it's not supported).

**Comment by mloskot** [comment]
Regardless of compiler features, SOCI builds in C++98 mode by default.

**Comment by Cleroth** [comment]
Isn't it pretty useless if you can't catch any exceptions in C++98? Any query error results in abort()/terminate() being called.

**Comment by mloskot** [comment]
`SOCI_HAVE_CXX_C11` enables or disables C++11 features *on-demand*.

In case of VS2015, the problem is it does not support C++98 only mode as GCC or clang do, so the `noexcept(false)` needs to be implicitly enabled, indeed. VS2015 support is incomplete, apparently.

**Comment by Cleroth** [comment]
I see. Honestly I'm not sure if the problem occurs in `master`, as it seems it's a bit different in that aspect from the latest release (3.2.3). If the problem still happens, there really should be something done about it as it makes SOCI pretty much unusable with VS2015.

All I did to fix it was the noexcept declaration to this:
    #if __cplusplus >= 201103L || (defined(_MSC_FULL_VER) && _MSC_FULL_VER >= 190023026)
    #define SOCI_ONCE_TEMP_TYPE_NOEXCEPT noexcept(false)

Since VS's __cplusplus is still defined to C++98 (because its C++11 features are not complete), but the noexcept is fully implemented, then this should work just fine (and it does for me).

**Comment by mloskot** [comment]
Please, consider submitting a pull request. Thanks!

**Comment by Cleroth** [comment]
I only changed it on 3.2.3, not on trunk. I don't really know how to make it so that `SOCI_HAVE_CXX_C11` is set for VS (I don't have much knowledge in CMake and such configs).
VS could probably benefit from C++11 on the all of SOCI but I don't know how to do that. It really isn't as important as the breaking case of exceptions being thrown in a destructor and terminating the program, though. So what should I do? Just commit that one line that enables noexcept for VS?

**Comment by ckaminski** [comment]
I know this is old and fixed but I'd like to add the following for the Googlebot: 

    terminate called after throwing an instance of 'soci::postgresql_soci_error'

I wasted a few hours tracking this down.  It might be nice if the Installation documentation on Sourceforge was updated with this flag. 
http://soci.sourceforge.net/doc/3.2/installation.html

**Comment by vadz** [comment]
FWIW you should really use SOCI 4 (i.e. current Git master) instead of 3.2. There have been just too many fixes and improvements since then.

**Comment by Cleroth** [comment]
Maybe it's time for a release.

**Comment by willw-git** [comment]
Well, this really was a big, scary, time-consuming problem for me. 

If you have a version on master that fixes it, your users would be really grateful for a release.
