### ISSUE TITLE
async query call

### ISSUE THREAD

**Issue by redboltz** [SOCI/soci#445]
I'm using soci 3.2 on the network server that I'm developing. The network server is using Boost.Asio. It is connected to MariaDB server using soci and its MySQL backend. When the network server received some packets from clients, then makes some soci API call. Most of them are query (read access).

For example, 
```C++
sql << "select count(*) from permission where ...", into(count), use(id);
```

I've checked the network server profile using Google Performance Tools, then I realized that soci seems to to a bottle neck.

Here is a callgrind result:
```
Incl    Self   Called Function
45.52    0.00   178   soci::details::once_temp_type::~once_temp_type
45.52    0.26   178   soci::details::ref_counted_statement::dec_ref
41.43    0.00   162   soci::details::ref_counted_statement::final_action
18.67    0.26    73   soci::details::statement_impl::execute
18.67    0.00    73   soci::statement::execute
15.86    0.00    62   soci::details::statement_impl::prepare
15.86    0.00    62   soci::statement::prepare
12.79    0.51    50   soci::mysql_statement_backend::execute
12.79    2.81    50    soci::mysql_statement_backend::prepare
```

I assume that the following API call blocks internally until receiving a query result from MySQL server. Is that right? Does soci have async APIs?

I found that MariaDB provides async APIs. See https://mariadb.com/kb/en/mariadb/using-the-non-blocking-library/

I think that it is great if soci would provide async APIs if the backend support async APIs.

**Comment by snikulov** [comment]
@redboltz Are you calling SOCI from the same thread where you read network? If it is so, you should reconsider your design.

**Comment by redboltz** [comment]
@snikulov , thank you for the reply.

> @redboltz Are you calling SOCI from the same thread where you read network?

Yes.

> If it is so, you should reconsider your design.

OK, let's consider multi-threaded model. If I call SOCI from the different thread from reading network thread, the thread that calling SOCI would be blocked until getting the result of the query. Is that right?

According to the document http://soci.sourceforge.net/doc/3.2/multithreading.html, I can create many threads that call SOCI. (phase 2: usage from working threads in the example code)

I think that is a solution.

I'm not sure but I still wonder that if the backend DB such as MariaDB supports asynchronous APIs and I could call them, I might get a good performance.

**Comment by snikulov** [comment]
> OK, let's consider multi-threaded model. If I call SOCI from the different thread from reading network thread, the thread that calling SOCI would be blocked until getting the result of the query. Is that right?

It's not, just add [monitor](https://en.wikipedia.org/wiki/Monitor_%28synchronization%29) queue with request to SOCI thread.

> According to the document http://soci.sourceforge.net/doc/3.2/multithreading.html, I can create many threads that call SOCI. (phase 2: usage from working threads in the example code)

Not exactly. Link you've provided states ```SOCI classes are not thread-safe, meaning that their instances should not be used concurrently by multiple threads.``` which means it should be not called from multiple threads.

> I'm not sure but I still wonder that if the backend DB such as MariaDB supports asynchronous APIs and I could call them, I might get a good performance.

Perhaps. But SOCI pretending to be generic interface, which means it's not trying to cover all features of specific DB.

@mloskot Mateusz, should we close this? Or leave it as feature request?

**Comment by redboltz** [comment]
> > According to the document http://soci.sourceforge.net/doc/3.2/multithreading.html, I can create many threads that call SOCI. (phase 2: usage from working threads in the example code)

> Not exactly. Link you've provided states SOCI classes are not thread-safe, meaning that their instances should not be used concurrently by multiple threads. which means it should be not called from multiple threads.

Really? I've mentioned `phase 2: usage from working threads in the example code`. That means the following code:

```C++
// phase 1: preparation

const size_t poolSize = 10;
connection_pool pool(poolSize);

for (size_t i = 0; i != poolSize; ++i)
{
    session & sql = pool.at(i);

    sql.open("postgresql://dbname=mydb");
}

// phase 2: usage from working threads 

{
    session sql(pool);

    sql << "select something from somewhere...";

} // session is returned to the pool automatically
```

I think that 

```C++
// phase 2: usage from working threads 

{
    session sql(pool);

    sql << "select something from somewhere...";

} // session is returned to the pool automatically
```

can be called from multiple threads.

**Comment by snikulov** [comment]
@redboltz Yes, but only if you use connection_poll. Otherwise it is unsafe.

**Comment by redboltz** [comment]
Thank you, I understand it :)
