### ISSUE TITLE
AppVeyor can not find sh.exe?

### ISSUE THREAD

**Issue by mloskot** [SOCI/soci#447]
Looks like AV setup got broken, but I'm not sure what is going on:
```
del /Q "%ProgramFiles(x86)%\Git\bin\sh.exe"
The system cannot find the path specified.
Command exited with code 1
```
Do we really aim to delete the executable?

Sergei, could you have a look or confirm what needs to be done and I'll try?

**Comment by snikulov** [comment]
I'll check it soon. This deletion was intentional, because cmake fail generate makefile for MinGW with sh.exe discovered. Perhaps, something was changed on AppVeyor OS images.

**Comment by snikulov** [comment]
@mloskot OK. I've found the issue. They change git to recent 64 bit version. So path to sh.exe is changed. Will fix it with power-shell script to avoid same issue in future.
