### ISSUE TITLE
NLS supports for connection params in Oracle

### ISSUE THREAD

**Issue by msobczak** [SOCI/soci#458]
Please see the following commit:

https://github.com/msobczak/soci/commit/beb97c0f93bb4acf912c2ee9db6190866ad0a1cd

This improvement introduces support for charset/ncharset settings for connection parameters in Oracle. These parameters allow to set the character code for the whole session. The new parameters are optional and if not used, the backend behaves as before.
There are no new files in this commit.

Let me know if you have any feedback on this. If there are no objections I will implement these changes in the main SOCI repository.

**Comment by mloskot** [comment]
:+1:

**Comment by msobczak** [comment]
Commited in:

https://github.com/SOCI/soci/commit/8c6b479773113a2ceaab6a6ff588ad2e3f5e8c6e
