### ISSUE TITLE
Oracle wallet authentication

### ISSUE THREAD

**Issue by msobczak** [SOCI/soci#463]
Please see the following commit:

https://github.com/msobczak/soci/commit/a3b061af6954d0d9048b34c9c939222bc8e3baca

This improvement adds optional wallet-based authentication for Oracle, which is related to different methods of user authentication that are available there. The modification in code is rather cosmetic.

Let me know if you have any feedback on this before I can introduce this modification in the main repository.

**Comment by mloskot** [comment]
Looks good to me.

**Comment by snikulov** [comment]
:+1:

**Comment by msobczak** [comment]
Committed in:

https://github.com/SOCI/soci/commit/cae51eec9c7fdb28bd2afc261a1f45c73b880e04
