### ISSUE TITLE
VS2015 Exceptions => abort()

### ISSUE THREAD

**Issue by alastairUK** [SOCI/soci#465]
Using v3.2.3

If I compile my application with VS2015 then I am seeing some unexpected behavior. 

I am using an ODBC backend to a Microsoft Access database (MDB). Under VS2013 if I issued a query to a non-existent table (select count(*) from SomeFakeTable) I would be able to catch the exception in a catch (soci::soci_error& e) and e.what() yields:

[Microsoft][ODBC Microsoft Access Driver] The Microsoft Jet database engine cannot find the input table or query 'SomeFakeTable'.  Make sure it exists and that its name is spelled correctly.

As expected.

If I do the same with VS2015 I can't seem to catch the exception and the VS output window shows:

Exception thrown at 0x764EDAD8 in MyApp.exe: Microsoft C++ exception: soci::odbc_soci_error at memory location 0x0018D4E0.
Exception thrown at 0x764EDAD8 in MyApp.exe: Microsoft C++ exception: [rethrow] at memory location 0x00000000.
Exception thrown at 0x764EDAD8 in MyApp.exe: Microsoft C++ exception: [rethrow] at memory location 0x00000000.
Debug Error!
Program: ...\Debug\MyApp.exe
abort() has been called

I have tried running the unit tests and seeing the same behavior and an exception is thrown when trying to call:

msession << "drop table soci_test"

Exception thrown at 0x764EDAD8 in soci_odbc_test_access_static.exe: Microsoft C++ exception: soci::odbc_soci_error at memory location 0x0018F774.

Exception thrown at 0x764EDAD8 in soci_odbc_test_access_static.exe: Microsoft C++ exception: [rethrow] at memory location 0x00000000.

Exception thrown at 0x764EDAD8 in soci_odbc_test_access_static.exe: Microsoft C++ exception: [rethrow] at memory location 0x00000000.

**Comment by vadz** [comment]
You need ffc564b70d96ea13fa64c134e0b5b74fe0afd720 to fix this, see #448.

**Comment by alastairUK** [comment]
Thanks!
