### ISSUE TITLE
Char * not supported in use/into. Documentation states otherwise.

### ISSUE THREAD

**Issue by mattj0nes2** [SOCI/soci#466]
Assuming http://soci.sourceforge.net/doc/3.2/exchange.html is the correct documentation to be referring to, it lists as supported for use/into:

char*, char[], std::string (for string values)

For all I can tell only std::string is actually supported. Given some of the code I'm trying to port to SOCI supporting char* would certainly get my vote, but that aside the documentation being updated might save other people the time of realising this later.

**Comment by mloskot** [comment]
@mattj0nes2 Thanks for the report.


Following [char[N] and compilation problems](https://sourceforge.net/p/soci/mailman/message/20179704/) discussion on the mailing list long time ago, @msobczak removed support for C-array of `char` in SOCI/soci@25c704ac4cb7bb0135dabc2421a1281fb868a511.

Indeed, the documentation is missing the update.
