### ISSUE TITLE
Is there any roadmap to support vertica ?

### ISSUE THREAD

**Issue by wdavilaneto** [SOCI/soci#477]
Is there any roadmap to support vertica  ?

**Comment by mloskot** [comment]
Not as far as I know

**Comment by snikulov** [comment]
@mloskot Should we close this?

**Comment by mloskot** [comment]
On 3 Jun 2016 22:39, "Sergei Nikulov" <notifications@github.com> wrote:
>
> @mloskot Should we close this?

Unless anyone wants to implement backend for it, I think we can close it.

Alternative for interested users is to use the ODBC backend to access
vertica. It could even be tested on Travis CI, see my notes here
https://github.com/lexicalunit/nanodbc/issues/162, if anyone wants it.

**Comment by wdavilaneto** [comment]
As a SOCI user, and not developer, i can't tell i'll implement it. But I've
started to study SOCI implementation and Vertica API to measure the
challenge.

Think I'll need at least a month...

**Comment by wdavilaneto** [comment]
Ok. I'll Close it, there are no C/C++ API to consume other then ado/odbc.
