### ISSUE TITLE
Provide CMake package configuration file

### ISSUE THREAD

**Issue by mloskot** [SOCI/soci#481]
It might be desirable to provide the library users with `SociConfig.cmake `or `soci-config.cmake`
https://cmake.org/cmake/help/git-master/manual/cmake-packages.7.html

**Comment by snikulov** [comment]
@mloskot We already have such task #394

**Comment by mloskot** [comment]
Aha! I should have used the search. Thanks @snikulov.

Closing as #394 dup.
