### ISSUE TITLE
Thoughts on integrating a decimal library?

### ISSUE THREAD

**Issue by candychiu** [SOCI/soci#483]
Is there any interest to integrate a decimal library into the framework, for example, [decimal_for_cpp](https://github.com/vpiotr/decimal_for_cpp)?

**Comment by mloskot** [comment]
I'm sure there would be some interest.
It should be implemented similarly to Boost.Fusion, as an optional dependency controlled at SOCI build time.

**Comment by mloskot** [comment]
No further feedback or pull request. 
I'm closing it due to no interest.
