### ISSUE TITLE
Illegal memory access on Windows

### ISSUE THREAD

**Issue by candychiu** [SOCI/soci#488]
One of my unit test cases on odbc starts to fail after I upgrade to the latest code base.  I compiled the code on a Windows box with Visual Studio 2013 and 2015.  Both exhibits the same behavior.  

I traced the error to 
`prepare_temp_type &operator,(use_container<T, Indicator> const &uc)`

Before `rcpi_->exchange(uc);` is called, `rcpi_` is in a good state: 
`rcpi_  0x0000000000262780 {intos_={ size=0 } uses_={ size=0 } }`

One step forward, in `ref-counted-prepare-info.h`, 
```
template <typename T, typename Indicator>
void exchange(use_container<T, Indicator> const &uc)
 { uses_.exchange(uc); }
```
is also fine.

One more step forward to `bind-value.h`, 
```
class use_type_vector: public std::vector<use_type_base *>
{
    template <typename T, typename Indicator>
    void exchange(use_container<T, Indicator> const &uc)
    {
#ifdef SOCI_HAVE_BOOST
        exchange_(uc, (typename boost::fusion::traits::is_sequence<T>::type *)NULL);
#else
        exchange_(uc, NULL);
#endif // SOCI_HAVE_BOOST
    }
```

For some reason, the use_type_vector is corrupted when it reached `exchange`.  
Corrupted value: `0x00000000002627b8 { size=452126080238279090 }`

I also captured the memory addresses:
```
this	0x000000000029fa48 {rcpi_=0x00000000004df640 {intos_={ size=0 } uses_={ size=0 } } }soci::details::prepare_temp_type *

rcpi_	**0x00000000004df640** {intos_={ size=0 } uses_={ size=0 } }soci::details::ref_counted_prepare_info *

this	0x000000000029fa48 {intos_={ size=0 } uses_={ size=0 } }soci::details::ref_counted_prepare_info *
          &intos_ 	0x000000000029fa90 { size=0 }
          &uses_ 	0x000000000029fab0 { size=0 }

this	**0x00000000004df640** { size=452126080669924939 }	soci::details::use_type_vector *
```

`soci::details::ref_counted_prepare_info *` shared the same memory address as `soci::details::use_type_vector *`?  

I also tried disabling boost, didn't help. 

The last version of the code that I compiled and worked fine was mater on Feb 17, 2016.

**Comment by vadz** [comment]
We really need to be able to reproduce it in the SOCI test suite itself, it's very hard to understand what happens here without this.

**Comment by candychiu** [comment]
I can only compile with Visual Studio.  Any plan to fix the failed builds on AppVeyor soon?

**Comment by vadz** [comment]
Sorry, I don't understand this. What's the problem with compiling SOCI test suite using MSVC?

As for the problem with AppVeyor, I haven't even noticed it somehow, but I hope @msobczak can look at it as this seems due to #486.

**Comment by candychiu** [comment]
Once it compiles, I can work on a test case and have it run on AppVeyor for everybody to see. 

I tried starting from checking code out and it appears the problem has to do with regenerating project files in cmake using different settings.  I am also on boost 1_60.  It would be great if we can upgrade to 1_60.

**Comment by vadz** [comment]
If you can reproduce the problem in a test when running it locally, please do it and open a PR with a patch adding the (failing) test. This will be sufficient to allow others to debug it already, fixing AppVeyor build would definitely be nice but is absolutely not a prerequisite for doing this and fixing this bug.

**Comment by candychiu** [comment]
@vadz I can't reproduce the problem after I start with a fresh copy of the code.  I ran cmake in the same directory with different commits and different settings.  That probably messed up the configuration.  

I included boost in one of the runs which referenced version 1_60, and it didn't complain about not finding the fusion header.
