### ISSUE TITLE
XML type

### ISSUE THREAD

**Issue by msobczak** [SOCI/soci#496]
I would like to propose the extension of the library to support the XML data type.
Even though XML is fundamentally a string, some databases offer separate SQL data types for it, with special handling including schema validation and XPath searches. Unfortunately, at least for Oracle, such data types require different steps for binding and data transmission.
A possible solution is to define a wrapper type like:

```
struct XMLType
{
    std::string xml;
}
```

which will be recognized by the library and handled appropriately.
Backends could then handle it in one of the three ways:
- ignore whatsoever (no code change required, but no added value gained for the backend),
- bind/define in the same way as std::string (trivial code extension required)
- bind/define in some special way (appropriate change required)

Any feedback welcome.

**Comment by vadz** [comment]
Even though I don't have any plans to do it in the immediate future, I'd like to have a solution which could also be used for native JSON support later too.

Otherwise no real comments except for the usual naming one: maybe `xml_data` would be more in line with SOCI conventions?

**Comment by mloskot** [comment]
I believe this has been implemented now, by #509
