### ISSUE TITLE
draft: Findsoci.cmake

### ISSUE THREAD

**Issue by wisk** [SOCI/soci#498]
Hello again,

As I told in my previous issue, I started a Findsoci.cmake script.
It relies on "modern" cmake properties to make the use easier.
At this time, it only supports static libraries, but I think shared library could be easily added.
However, I'm sure if I can write a script which supports both at the same time.

I didn't make a PR since I'm not sure where this file should be located and how it'd be installed.
This current version is available [here](https://gist.github.com/wisk/289d4dfa147501da064e7ec3dabf519a).

BTW, I'm wondering how I should write this project name: soci, Soci, SOCI?

**Comment by mloskot** [comment]
The project name is SOCI, so I think the script should be named `FindSOCI.cmake`, similarly to scripts provided by CMake itself: `FindGTK.cmake`, etc.
(If  you look at names in the current `/cmake` folder, scripts use `Soci` what was not very fortunate choice and might be confusing.)

If it is OK, I would put the script into `/cmake` folder.

Regarding where to install it, I'm not sure what is the current CMake recommendation . Do you know?

**Comment by snikulov** [comment]
@wisk the better way is config files generation during build and package it with library.
The main idea was described here https://cmake.org/Wiki/CMake/Tutorials/How_to_create_a_ProjectConfig.cmake_file and we already have issue for that https://github.com/SOCI/soci/issues/394

**Comment by mloskot** [comment]
@wisk 's `FindSoci.cmake` has been added long time ago
