### ISSUE TITLE
unfortunate placement of soci headers with common names

### ISSUE THREAD

**Issue by karnigen** [SOCI/soci#505]
It seems to me that soci headers with very common names (error.h version.h procedure.h session.h ...) should be moved into some subdirectory - high probability of conflict with other such names in other projects. On top directory should remain only files prefixed with "soci-" or so. Otherwise is very annoying.

**Reason**: soci backends requires that soci include directory is on c/c++ headers search path, (see eg. soci-postgresql.h that includes `<soci-backand.h>` ...).

**Solution**: replace in backends `#include <soci-backand.h>` with `#include <soci/soci-backand.h>` and than it is enough to set search path only to parent of top soci directory. Users should use `#include <soci/soci.h>`.

**Comment by snikulov** [comment]
@karnigen This #151 was already merged on master branch.
