### ISSUE TITLE
Throw if truncation happens but no indicators was provided

### ISSUE THREAD

**Issue by vadz** [SOCI/soci#51]
Currently if a select statement results in a null value and no indicator is defined for the corresponding output parameter, a "Null value fetched and no indicator defined." exception is thrown. However when the same happens with truncation, it is silently ignored if there is no indicator (if there is one, the truncation is reported via it). This is inconsistent and actually dangerous as the data can be silently corrupted, so we should throw an exception when this happens instead of just ignoring it.

As this would be a backwards incompatible change, it should only be done in 4.0 and not in any of 3.x releases.

**Comment by vadz** [comment]
Update: I have now tested with Oracle too and it behaves as PostgreSQL, i.e. an exception is thrown.

So I actually have a new plan: just make all backends throw an exception on truncation except, perhaps, SQLite, which doesn't lose data (even though it doesn't truncate neither).

The main problem I have with this is that I don't know how to make MySQL generate an exception in non-strict mode, would anybody know how to do it? If not, I'll probably just leave MySQL alone.

**Comment by mloskot** [comment]
The new plan sounds good :+1: 

I don't know. @pfedor is our MySQL guru.
