### ISSUE TITLE
Link issue with master

### ISSUE THREAD

**Issue by b1c9g76** [SOCI/soci#513]
`build/Debug/GNU-Linux/main.o:(.rodata._ZTVN4soci7details8use_typeI2tmEE[_ZTVN4soci7details8use_typeI2tmEE]+0x30): undefined reference to `soci::details::standard_use_type::dump_value(std::ostream&) const'
build/Debug/GNU-Linux/main.o:(.rodata._ZTVN4soci7details8use_typeIdEE[_ZTVN4soci7details8use_typeIdEE]+0x30): undefined reference to `soci::details::standard_use_type::dump_value(std::ostream&) const'
build/Debug/GNU-Linux/main.o:(.rodata._ZTVN4soci7details8use_typeIiEE[_ZTVN4soci7details8use_typeIiEE]+0x30): undefined reference to `soci::details::standard_use_type::dump_value(std::ostream&) const'
build/Debug/GNU-Linux/main.o:(.rodata._ZTVN4soci7details8use_typeISsEE[_ZTVN4soci7details8use_typeISsEE]+0x30): undefined reference to `soci::details::standard_use_type::dump_value(std::ostream&) const'`

I'm chasing some memory leaks that appear to be in 3_2_3 that look like they may have been addressed in the master.

I'm linking against soci_core and soci_mysql

Is there something else that should be in there now that I have missed?

**Comment by mloskot** [comment]
There is no `soci::details::standard_use_type::dump_value` in SOCI 3.
Looks like linker gets SOCI 3 and 4 (current master) mismatched.

**Comment by b1c9g76** [comment]
Yes, you're right. 

Earlier version was still there in /usr/lib64/ c.f. the new version in /usr/local/lib64/

Thanks for replying

**Comment by mloskot** [comment]
Np, you're welcome.
