### ISSUE TITLE
[Q] Store query in unsorted_map

### ISSUE THREAD

**Issue by Cilenco** [SOCI/soci#522]
We can use the code below to query data from the database and store the result ins a std::vector:

```
std::vector<Person> persons;
sql << "select * from person , into(persons);
```

Is it possible to use ```std::unsorted_map<std::string, Person>``` with the ```into``` function? The first argument should be the ```PRIMARY_KEY``` and the second one the object itself.

**Comment by mloskot** [comment]
No, it is not possible.
