### ISSUE TITLE
can std::string of soci hold the right utf8 data?

### ISSUE THREAD

**Issue by lkkey80** [SOCI/soci#525]
I get wrong Chinese bytes using into(string)

**Comment by lkkey80** [comment]
with sql << select ... , into(string)

**Comment by snikulov** [comment]
@lkkey80 Which OS? Linux or Windows?

**Comment by lkkey80** [comment]
linux, centos 7。
for example oracle varchar '鲁XXXXXX', sql << select ..., into(string); I got ?XXXXXX everytime.

**Comment by lkkey80** [comment]
contents of varchar is encoded in GBK，not utf8, but I think soci should handle this.

**Comment by mloskot** [comment]
On 3 March 2017 at 14:30, lkkey80 <notifications@github.com> wrote:

> contents of varchar is encoded in GBK，not utf8, but I think soci should
> handle this.
>

No. SOCI is supposed to be encoding-agnostic, transferring between
server/client whatever it is fed up with.

**Comment by lkkey80** [comment]
after setting NLS_LANG="Simplified Chinese_china".ZHS16GBK, the issue disappeared.

**Comment by mloskot** [comment]
I'm glad you've solved the problem.

Thank you for sharing the solution.

**Comment by jsonn** [comment]
I don't think it is encoding-agnostic since it depends on the value being NUL-terminated. Just saying.

**Comment by mloskot** [comment]
@jsonn good point, there are caveats
