### ISSUE TITLE
How to use rowset with Core interface

### ISSUE THREAD

**Issue by redboltz** [SOCI/soci#527]
According to the document, I can use rowset as follows:

http://soci.sourceforge.net/doc/3.2/statements.html#rowset

```cpp
rowset<int> rs = (sql.prepare << "select values from numbers");

for (rowset<int>::const_iterator it = rs.begin(); it != rs.end(); ++it)
{
     cout << *it << '\n';
}
```

This is a way to use rowset with Sugar intarface.

SOCI also provides Core interface.
http://soci.sourceforge.net/doc/3.2/interfaces.html

Here is an example:
```cpp
statement st(sql);
st.alloc();
st.prepare("select values from numbers");
st.define_and_bind();
st.execute(true);
```

I want to use rowset with Core interface. How can I do that?

**Comment by redboltz** [comment]
Maybe I found a way:

```cpp
row r;

statement st(sql);
st.alloc();
st.prepare("select values from numbers");
st.define_and_bind();

// after define_and_bind and before execute
st.exchange_for_rowset(into(r));

st.execute(true);

rowset_iterator<row> it(st, r);
rowset_iterator<row> end;
for (; it != end; ++it) {
    // ... access *it
}
```

It works for me. But I'm not sure this is a correct way.

**Comment by mloskot** [comment]
LGTM

**Comment by redboltz** [comment]
Thank you for the comment!

**Comment by redboltz** [comment]
I realized that the first record is missing.

I replaced `st.execute(true);` with `st.execute(false);`, then it works fine.

**Comment by Astrinus** [comment]
It could be interesting to put that in the documentation.

**Comment by mloskot** [comment]
@Astrinus Please, consider extending this section with relevant paragraph

https://github.com/SOCI/soci/blob/master/docs/statements.md#rowset-and-iterator

**Comment by Astrinus** [comment]
I'll do it as soon as I find a way to discriminate if I can use rowset or not depending on the query (not known in advance), because for INSERTs, when the rowset iterator `operator++` calls `st_->fetch()`, the latter returns always true with no data...
