### ISSUE TITLE
Unable to catch sqlite3_soci_error, program aborts

### ISSUE THREAD

**Issue by sinall** [SOCI/soci#529]
I'm using soci with an encrypted sqlite3 database (sqlcipher).

```
try {
	session sql(sqlite3, "encrypted.db");
        // sql << "PRAGMA key = 'testkey';";
	sql << "SELECT count(*) FROM sqlite_master;";
}
catch (const sqlite3_soci_error& e) {
	int x = 1; // Unable to go to here.
}
```

If I don't provide the passphrase, VS2015 show 'Debug Error!' dialog, then aborts the program even if I click 'Retry' or 'Ignore' button.

**Comment by mloskot** [comment]
One thing you may do is to check call stack trace (eg. run session under VS debugger, you may need to enable some extra exceptions like Access Violation etc.  to break the debugger at). That may help to figure out what's the problem.

**Comment by sinall** [comment]
The first breakpoint is as below when I click 'Ignore' button:

```
void sqlite3_statement_backend::prepare(std::string const & query,
    statement_type /* eType */)
{
    clean_up();

    char const* tail = 0; // unused;
    int const res = sqlite3_prepare_v2(session_.conn_,
                              query.c_str(),
                              static_cast<int>(query.size()),
                              &stmt_,
                              &tail);
    if (res != SQLITE_OK)
    {
        char const* zErrMsg = sqlite3_errmsg(session_.conn_);

        std::ostringstream ss;
        ss << "sqlite3_statement_backend::prepare: "
           << zErrMsg;
        throw sqlite3_soci_error(ss.str(), res); // <---- Break at this line.
    }
    databaseReady_ = true;
}

```

While the call stack is:

>  	[Frames below may be incorrect and/or missing, no symbols loaded for ucrtbased.dll]	
>  	[External Code]	
> >	UnitTest.dll!soci::sqlite3_statement_backend::prepare(const std::basic_string<char,std::char_traits<char>,std::allocator<char> > & query, soci::details::statement_type __formal) Line 69	C++
>  	UnitTest.dll!soci::details::statement_impl::prepare(const std::basic_string<char,std::char_traits<char>,std::allocator<char> > & query, soci::details::statement_type eType) Line 193	C++
>  	UnitTest.dll!soci::statement::prepare(const std::basic_string<char,std::char_traits<char>,std::allocator<char> > & query, soci::details::statement_type eType) Line 204	C++
>  	UnitTest.dll!soci::details::ref_counted_statement::final_action() Line 26	C++
>  	UnitTest.dll!soci::details::ref_counted_statement_base::dec_ref() Line 40	C++
>  	UnitTest.dll!soci::details::once_temp_type::~once_temp_type() Line 41	C++
>  	UnitTest.dll!UnitTest::SQLCipherTest::ShouldNotAccessEncryptedDbWithoutPassphrase() Line 54	C++
>  	UnitTest.dll!Microsoft::VisualStudio::CppUnitTestFramework::TestClass<UnitTest::SQLCipherTest>::__Invoke(void(Microsoft::VisualStudio::CppUnitTestFramework::TestClassImpl::*)() method) Line 465	C++
>  	Microsoft.VisualStudio.TestTools.CppUnitTestFramework.Executor.dll!0f0eeffb()	Unknown
>  	Microsoft.VisualStudio.TestTools.CppUnitTestFramework.Executor.dll!0f0ec9d2()	Unknown
>  	Microsoft.VisualStudio.TestTools.CppUnitTestFramework.Executor.dll!0f0eca51()	Unknown
>  	Microsoft.VisualStudio.TestTools.CppUnitTestFramework.Executor.dll!0f0ee8bb()	Unknown
>  	Microsoft.VisualStudio.TestTools.CppUnitTestFramework.Executor.dll!0f0e7aa8()	Unknown
>  	Microsoft.VisualStudio.TestTools.CppUnitTestFramework.Executor.dll!0f0e7773()	Unknown
>  	Microsoft.VisualStudio.TestTools.CppUnitTestFramework.Executor.dll!0f0e5ed0()	Unknown
>  	[External Code]	
>

**Comment by sinall** [comment]
I add break point, when it hit, I click 'Step Over' then 'Debug Error!' dialog shows up. This is might be the real place for the root cause.

```
    void dec_ref()
    {
        if (--refCount_ == 0)
        {
            try
            {
                final_action();
            }
            catch (...)
            {
                delete this;
                throw; // <---- Add break point here.
            }

            delete this; // <--- BTW, Is this a bug? if exception happens in final_action.
        }
    }

```

Call stack:

> >	UnitTest.dll!soci::details::ref_counted_statement_base::dec_ref() Line 45	C++
>  	UnitTest.dll!soci::details::once_temp_type::~once_temp_type() Line 41	C++
>  	UnitTest.dll!UnitTest::SQLCipherTest::ShouldNotAccessEncryptedDbWithoutPassphrase() Line 54	C++
>  	UnitTest.dll!Microsoft::VisualStudio::CppUnitTestFramework::TestClass<UnitTest::SQLCipherTest>::__Invoke(void(Microsoft::VisualStudio::CppUnitTestFramework::TestClassImpl::*)() method) Line 465	C++
>  	Microsoft.VisualStudio.TestTools.CppUnitTestFramework.Executor.dll!6a3eeffb()	Unknown
>  	[Frames below may be incorrect and/or missing, no symbols loaded for Microsoft.VisualStudio.TestTools.CppUnitTestFramework.Executor.dll]	
>  	Microsoft.VisualStudio.TestTools.CppUnitTestFramework.Executor.dll!6a3ec9d2()	Unknown
>  	Microsoft.VisualStudio.TestTools.CppUnitTestFramework.Executor.dll!6a3eca51()	Unknown
>  	Microsoft.VisualStudio.TestTools.CppUnitTestFramework.Executor.dll!6a3ee8bb()	Unknown
>  	Microsoft.VisualStudio.TestTools.CppUnitTestFramework.Executor.dll!6a3e7aa8()	Unknown
>  	Microsoft.VisualStudio.TestTools.CppUnitTestFramework.Executor.dll!6a3e7773()	Unknown
>  	Microsoft.VisualStudio.TestTools.CppUnitTestFramework.Executor.dll!6a3e5ed0()	Unknown
>  	[External Code]

**Comment by sinall** [comment]
```

class X {
public:
	void dec_ref() {
		try {
			throw sqlite3_soci_error("", 0);
		}
		catch (...) {
			delete this;
			throw;
		}

		delete this;
	}
};

		try {
			X x;
			x.dec_ref();
		}
		catch (const sqlite3_soci_error& e) {
			int x = 1; // Unable to go to here.
		}
```

Here's an very simple example which could reproduce the 'similar' issue.

**Comment by sinall** [comment]
Good news, the issues doesn't happen on current master branch.
