### ISSUE TITLE
Error	C2065	'x_type': undeclared identifier

### ISSUE THREAD

**Issue by sinall** [SOCI/soci#531]
Environment:
VS2015 Update 3
SOCI-3.2 branch built with -DSOCI_TESTS=OFF -DWITH_BOOST=OFF -DWITH_SQLITE3=ON

The type_conversion is already defined under soci namespace.

Error message:

> Severity	Code	Description	Project	File	Line	Suppression State
> Error	C2065	'x_type': undeclared identifier	My_App	...\soci-3.2\include\core\exchange-traits.h	40	
> 

What should I do?

**Comment by mloskot** [comment]
No idea, can't test now and unfortunately AppVeyor config is still broken not checking VS2015.

Try `master` branch, perhaps.

**Comment by sinall** [comment]
Seems that that's because I use a customized type in my domain class. The compiler does not report error friendly, that's a pain.

**Comment by sinall** [comment]
I will try master for sure, since the sqlite_soci_error crash problem.
