### ISSUE TITLE
API/ABI changes review for SOCI

### ISSUE THREAD

**Issue by lvc** [SOCI/soci#537]
The review of API/ABI changes for SOCI since 3.1.0 version: https://abi-laboratory.pro/tracker/timeline/soci/

Created with the help of open-source abi-tracker tool: https://github.com/lvc/abi-tracker. Hope it will be helpful for users and maintainers of the library.

![soci-1](https://cloud.githubusercontent.com/assets/1517837/25737915/51f1be1c-318b-11e7-8817-7b8785dae6dd.png)
![soci-2](https://cloud.githubusercontent.com/assets/1517837/25737949/81282df6-318b-11e7-9283-33a092f92c39.png)

## Environment
* Linux x86_64
* GCC 4.9
* SOCI 3.1.0 and higher

**Comment by mloskot** [comment]
@lvc Awesome, thanks! I wonder, would it be possible to include the current `master` branch too?

**Comment by lvc** [comment]
Easy!

https://abi-laboratory.pro/tracker/timeline/soci/

It is updated 3 times a week.

![soci-3](https://cloud.githubusercontent.com/assets/1517837/25753624/48f99b3a-31cd-11e7-840c-af2ec845daa1.png)

**Comment by mloskot** [comment]
Great, thank you a lot!
