### ISSUE TITLE
How can I install SOCI on HP UX?

### ISSUE THREAD

**Issue by sloagnidea** [SOCI/soci#538]
GNU GCC 4.2.3

**Comment by mloskot** [comment]
Build from source code?

**Comment by sloagnidea** [comment]
When I compile SOCI with source code, the compiler outputs "Segmentation fault".

The compiler output contents:
soci/include/soci/bind-values.h: In member function 'void soci::details::use_type_vector::exchange(const soci::details::use_container<T, Indicator>&) [with T = std::basic_string<char, std::char_traits<char>, std::allocator<char> >, Indicator = void]':
soci/include/soci/ref-counted-prepare-info.h:42 instantiated from 'void soci::details::ref_counted_prepare_info::exchange(const soci::details::use_container<T, Indicator>&) [with T = std::basic_string<char, std::char_traits<char>, std::allocator<char> >, Indicator = void]'
soci/include/soci/prepare-temp-type.h:50: instantiated from 'soci::details::prepare_temp_type& soci::details::prepare_temp_type::operator,(const soci::details::use_container<T, Indicator>&) [with T = std::basic_string<char, std::char_traits<char>, std::allocator<char> >, Indicator = void]'
soci/src/core/session.cpp:374: instantiated from here
soci/include/soci/bind-values.h:42: 编译器内部错误: Segmentation fault

**Comment by mloskot** [comment]
Sorry, I can't help.
Perhaps update GCC to more recent version will solve the problem.

**Comment by sloagnidea** [comment]
Thanks!!!
