### ISSUE TITLE
how to build soci with postgresql?

### ISSUE THREAD

**Issue by pingsoli** [SOCI/soci#543]
I followed the following steps:
- download and extract the soci archive
- mkdir build && cd build
- cmake -G "Unix Makefiles" -DWITH_BOOST=OFF -DWITH_POSTGRESQL=ON -DPOSTGRESQL_INCLUDE_DIR=/usr/local/postgresql/include -DPOSTGRESQL_LIBRARIES=/usr/local/postgresql/lib ../soci
- ** gived some warnings **
- make 
- ** error **
the warnings as following:
WARNING: Target "soci_postgresql" requests linking to directory "/usr/local/postgresql/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "soci_postgresql_test" requests linking to directory "/usr/local/postgresql/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "soci_postgresql_test_static" requests linking to directory "/usr/local/postgresql/lib".  Targets may link only to libraries.  CMake is dropping the item.

and the error:
Scanning dependencies of target soci_postgresql_test
[ 96%] Building CXX object backends/postgresql/test/CMakeFiles/soci_postgresql_test.dir/test-postgresql.cpp.o
[ 97%] Linking CXX executable ../../../bin/soci_postgresql_test
../../../lib/libsoci_postgresql.so.3.2.3: undefined reference to `PQresultStatus'
../../../lib/libsoci_postgresql.so.3.2.3: undefined reference to `PQgetvalue'
../../../lib/libsoci_postgresql.so.3.2.3: undefined reference to `PQclear'
../../../lib/libsoci_postgresql.so.3.2.3: undefined reference to `PQresultErrorMessage'
../../../lib/libsoci_postgresql.so.3.2.3: undefined reference to `PQexec'
../../../lib/libsoci_postgresql.so.3.2.3: undefined reference to `lo_lseek'
../../../lib/libsoci_postgresql.so.3.2.3: undefined reference to `PQfsize'
../../../lib/libsoci_postgresql.so.3.2.3: undefined reference to `PQgetisnull'
../../../lib/libsoci_postgresql.so.3.2.3: undefined reference to `PQerrorMessage'
../../../lib/libsoci_postgresql.so.3.2.3: undefined reference to `lo_open'
../../../lib/libsoci_postgresql.so.3.2.3: undefined reference to `PQexecPrepared'
../../../lib/libsoci_postgresql.so.3.2.3: undefined reference to `PQftype'
../../../lib/libsoci_postgresql.so.3.2.3: undefined reference to `lo_close'
../../../lib/libsoci_postgresql.so.3.2.3: undefined reference to `PQexecParams'
../../../lib/libsoci_postgresql.so.3.2.3: undefined reference to `PQfname'
../../../lib/libsoci_postgresql.so.3.2.3: undefined reference to `PQconnectdb'
../../../lib/libsoci_postgresql.so.3.2.3: undefined reference to `PQstatus'
../../../lib/libsoci_postgresql.so.3.2.3: undefined reference to `PQntuples'
../../../lib/libsoci_postgresql.so.3.2.3: undefined reference to `PQresultErrorField'
../../../lib/libsoci_postgresql.so.3.2.3: undefined reference to `PQfformat'
../../../lib/libsoci_postgresql.so.3.2.3: undefined reference to `lo_read'
../../../lib/libsoci_postgresql.so.3.2.3: undefined reference to `PQfinish'
../../../lib/libsoci_postgresql.so.3.2.3: undefined reference to `PQprepare'
../../../lib/libsoci_postgresql.so.3.2.3: undefined reference to `lo_write'
../../../lib/libsoci_postgresql.so.3.2.3: undefined reference to `PQcmdTuples'
../../../lib/libsoci_postgresql.so.3.2.3: undefined reference to `PQnfields'
collect2: error: ld returned 1 exit status
backends/postgresql/test/CMakeFiles/soci_postgresql_test.dir/build.make:97: recipe for target 'bin/soci_postgresql_test' failed
make[2]: *** [bin/soci_postgresql_test] Error 1
CMakeFiles/Makefile2:526: recipe for target 'backends/postgresql/test/CMakeFiles/soci_postgresql_test.dir/all' failed
make[1]: *** [backends/postgresql/test/CMakeFiles/soci_postgresql_test.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

Did I do anything wrong? please tell me, thank you.

**Comment by snikulov** [comment]
@pingsoli AFAIR, -DPOSTGRESQL_LIBRARIES=/usr/local/postgresql/lib should point to library not directories.

This exactly what here is given
> WARNING: Target "soci_postgresql" requests linking to directory "/usr/local/postgresql/lib"

Could you please try the following command?

> cmake -G "Unix Makefiles" -DWITH_BOOST=OFF -DWITH_POSTGRESQL=ON ../soci

On systems where "postgresql-devel.x86_64 : PostgreSQL development header files and libraries" installed, this command always should suffice.

**Comment by pingsoli** [comment]
@snikulov Thanks for your reply, your way worked it out. I remembered I must gave the postgresql include directory and libraries when configuring last time, but this time, I don't add them and it works. By the way,  I have not installed postgresql-devel package. Thanks a lot.

**Comment by snikulov** [comment]
@pingsoli then it was already installed :)
