### ISSUE TITLE
Make Oracle work again on Travis CI

### ISSUE THREAD

**Issue by vadz** [SOCI/soci#554]
Unfortunately the current scripts don't work any longer and this is a pity because Oracle is a backend that is not simple to test locally -- yet important enough to care about not breaking it.

It looks like the simplest way to use it on Travis is https://github.com/cbandy/travis-oracle, so perhaps we should try doing this instead.

**Comment by mloskot** [comment]
There is hope.

I've just successfully tested the [cbandy/travis-oracle](https://github.com/cbandy/travis-oracle) solution which downloads Oracle packages directly from Oracle (using newly created Oracle account dedicated for SOCI purposes).

Here is successful Travis CI build which installs Oracle database and makes test connection using `$ORACLE_HOME/bin/sqlplus`

Next, I will try to incorporate this solution into SOCI repo
