### ISSUE TITLE
ddl_type copy bug

### ISSUE THREAD

**Issue by Arenoros** [SOCI/soci#565]
It's not work if compilation not use NRVO.
`soci::ddl_type ddl = sql.create_table("t2");`
Because ddl_type constructor not copy  field **session * s_;**
```
ddl_type::ddl_type(const ddl_type & d) : rcst_(d.rcst_) {
    rcst_->inc_ref();
}
```

**Comment by davidsummers** [comment]
I just fixed this in PR #739.
