### ISSUE TITLE
sequence support MySQL and PostgreSQL

### ISSUE THREAD

**Issue by dpocock** [SOCI/soci#569]
According to the 3.2 docs, http://soci.sourceforge.net/doc/3.2/beyond.html describes sequences and then it says:

"These methods are currently only implemented in Firebird and ODBC backends."

Is that information still current for 3.2?

Is MySQL and PostgreSQL support in the pipeline or available for testing on the development branch?

If not, please classify this as a feature request for adding them.

**Comment by vadz** [comment]
These methods are implemented in git master, please feel free to use it, it is going to become 4.0.0 in (hopefully near) future.
