### ISSUE TITLE
Null value fetched and no indicator defined

### ISSUE THREAD

**Issue by mloskot** [SOCI/soci#580]
We have restored Oracle builds on Travis CI (#579).

Oracle build is failing due one test failure:
https://travis-ci.org/SOCI/soci/jobs/275269772

```
-------------------------------------------------------------------------------
String length
-------------------------------------------------------------------------------
/home/travis/build/SOCI/soci/tests/common-tests.h:4213
...............................................................................
/home/travis/build/SOCI/soci/tests/common-tests.h:4213: FAILED:
  {Unknown expression after the reported line}
due to unexpected exception with message:
  Null value fetched and no indicator defined while executing "select str,
  length(str) from soci_test order by length(str)".
```

The failing test was added by @vadz on 20 July in c6aef12b1e959c99d424ef3dcd6d6f74785390d2 and I assume it has never been tried against Oracle due to missing build.

Vadim, I'm taking the liberty to pass the issue over to you :-)

**Comment by vadz** [comment]
Will check, thanks. Looks like a real bug in Oracle backend...

**Comment by mloskot** [comment]
This is interesting finding. I had no idea.
Yes, tweaking the tests sound like a good idea.

BTW, this reminds me bugs/annoyances between ODBC drivers - there is no way to work around it than `if-else if-else` test cases.
