### ISSUE TITLE
Cannot link to backend DLL with VS2015

### ISSUE THREAD

**Issue by Astrinus** [SOCI/soci#606]
I get the following error when compiling a project referencing SOCI (master branch) with VS2015, after enabling verbose linker output:

```
1>SOCINXTtest.obj : error LNK2001: unresolved external symbol "struct soci::postgresql_backend_factory const soci::postgresql" (?postgresql@soci@@3Upostgresql_backend_factory@1@B)
1>
1>         Unused libraries:
1>           C:\soci\lib\soci_postgresql_4_0.lib
1>           [...VS/Win libs follow...]
```

Inspecting **soci_postgresql_4_0.lib** and **soci_postgresql_4_0.dll** with **dumpbin** shows that that symbol is indeed present in both files. I've tried to add `SOCI_POSTGRESQL_DECL` in front of the definition of `soci::postgresql` in **factory.cpp** but without any effect.

The **soci_core_4_0.lib** is correctly found (and linked), whereas the PG backend is found but apparently ignored. Linking with static libraries, however, is fine.

**Comment by vadz** [comment]
`soci::postgresql` is not exported from the DLL and shouldn't be used. You can use either `factory_postgresql` or `register_factory_postgresql()`.

**Comment by Astrinus** [comment]
In "Connection" you say `session sql(postgresql, "dbname=mydb");` and nowhere is stated that this works only when linking statically backend libraries.

**Comment by mloskot** [comment]
Documentation updated in c98c877bc87a48c333db764dd1678b22583eac2d
