### ISSUE TITLE
Uninitialized gotData_ in soci::statement

### ISSUE THREAD

**Issue by jonathanmcdougall** [SOCI/soci#609]
Similar to [this one for `procedure`](https://github.com/SOCI/soci/pull/535), `statement::gotData_` is not initialized in constructors nor is it copied in copy constructors or by `operator=`.

    soci::statement f()
    {
        soci::statement s = ...
        assert(!s.got_data());    // passes
        return s;
    }

    auto s = f();
    assert(!s.got_data());        // can fail

**Comment by mloskot** [comment]
PR is welcome

**Comment by mloskot** [comment]
Fixed in #615
