### ISSUE TITLE
Will it work for remote Oracle Database ? 

### ISSUE THREAD

**Issue by Rakin061** [SOCI/soci#610]
I have been trying to use SOCI to connect Oracle Database using C++. But, I am writing C++ code in one machine and the Oracle Database is in another machine.

I am using:-   
                  --Compiler: Microsoft Visual Studio Community 2015 v 14 
                  --Database: Oracle 11g

So, my intention is to connect to the remote database using Oracle Instant Client libraries through SOCI. Does SOCI support this kind of Scenario ? 

If yes, then what will be  `ORACLE_LIBRARIES` while configuring in CMake for my above described environment? 
I tired inputting the directory of I**nstant_Client_11_2**, **Instant_Client_Libraries_Sdk_lib (oraocci.lib)** as the value of  `ORACLE_LIBRARIES. But, it fails each and every cases.

There have no problems in compiling and linking in my code, I just can't connect and query from my remote database.

**Comment by mloskot** [comment]
> my intention is to connect to the remote database using Oracle Instant Client libraries through SOCI. Does SOCI support this kind of Scenario ?

Yes, of course.

You need Oracle InstantClient libraries. You can check https://github.com/SOCI/soci/blob/master/cmake/modules/FindOracle.cmake for details about what does SOCI CMake search for.

Also, check docs at http://soci.sourceforge.net/doc/master/backends/oracle/
> "The SOCI Oracle backend requires Oracle's libclntsh client library."

**Comment by Rakin061** [comment]
Thanks for the reply. 

But I am using windows. So, libclntsh client library will not help. Should I use oci.dll instread ? 

Thanks in advance.

**Comment by mloskot** [comment]
You will need to consult Oracle Instant Client documentation for developers what are the libraries required to link against on Windows.

**Comment by mloskot** [comment]
I'm closing this as no further activity occurred. Feel free to reopen in case you have any new feedback to bring in.
