### ISSUE TITLE
Documentation on make with Windows + Mingw (BOOST + PostgreSQL)

### ISSUE THREAD

**Issue by rXp** [SOCI/soci#612]
I am looking for documentation on how to build SOCI with mingw because I am constantly getting errors so I'm assuming I'm missing variables or something in my mingw setup is wrong.

I would love to see if anyone managed to build it with mingw, which version of mingw and how. I'm not a big fan of mingw but that is what I must use for my project and I don't have a choice. I would appreciate any help.

**Comment by rXp** [comment]
I manage to build it with a different version of mingw but now when I try to link it this happens : 
```
CMakeFiles\AuthServer.dir/objects.a(main.cpp.obj): In function `main':
C:/Users/DafflonE01/Documents/MagesBattleAuthServerCPP/AuthServer/AuthServer/main.cpp:16: undefined reference to `soci::postgresql'
C:/Users/DafflonE01/Documents/MagesBattleAuthServerCPP/AuthServer/AuthServer/main.cpp:16: undefined reference to `soci::session::session(soci::backend_factory const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
C:/Users/DafflonE01/Documents/MagesBattleAuthServerCPP/AuthServer/AuthServer/main.cpp:16: undefined reference to `soci::session::~session()'
C:/Users/DafflonE01/Documents/MagesBattleAuthServerCPP/AuthServer/AuthServer/main.cpp:16: undefined reference to `soci::session::~session()'
```
Even though soci_core and soci_postgresql and lpq are linked to the project.

**Comment by mloskot** [comment]
http://soci.sourceforge.net/doc/master/connections/
> In case of SOCI linked against DLLs on Windows, the factory objects are not exported from the DLLs.
> In order to avoid linker errors, access factory objects via dedicated backend functions provided (eg. `factory_postgresql()`)

Sorry, but I don't use MinGW at all and I don't know if any one from the team does it either.

**Comment by rXp** [comment]
@mloskot I built and linked static libraries and rebuilt postgresql with mingw to have a static lib too (*.a).

**Comment by mloskot** [comment]
OK

**Comment by rXp** [comment]
I meant that I have static libraries from the start. The errors do not come the DLL issue.

**Comment by mloskot** [comment]
@rXp For DLL build, did you follow the hint from the docs I pasted/linked above? If not, try it out. If it still does not work, sorry, I can't help.

**Comment by rXp** [comment]
I dropped mingw and went for VC 141 to fix it.
Mingw was already being an issue but that was too much so I just dropped and went to VC. I will have to accommodate for it.
