### ISSUE TITLE
Release 4.0.0?

### ISSUE THREAD

**Issue by jeking3** [SOCI/soci#616]
It's been almost 3 years since the last release, and a lot has changed - for example optional C++11 support while retaining C++03 support.  (Does that also mean Boost becomes unnecessary when building with C++11 support?)

Was wondering when we would see a version 4 release.  This library is used in a C++03 project I am involved in that is transitioning to C++14.

Thanks.

**Comment by BrainlessLabs** [comment]
I would also be interested in this. I am already using it in [Bun (C++ ORM)](https://github.com/BrainlessLabs/bun). I am using the latest code for this. It would be great if there is an official release for this.

**Comment by dpocock** [comment]
is there anything people can volunteer for to help make a 3.2.4, 3.3.0 or 4.0.0 release?

**Comment by abrownsword** [comment]
Hello, I just found SOCI and am interested in adopting it for my project, however it doesn't look like that's possible until the items planned for 4.0.0 are released.  This issue was last updated almost a year ago -- how far away is the next release now?

**Comment by mloskot** [comment]
Please, use the `master` as it won't be much more stable at point of release than it is now.

>  how far away is the next release now?

The `master` branch is pretty much ready. The only outstanding task is the CMake modernisation, https://github.com/mloskot/soci/tree/ml/modern-cmake

**Comment by mloskot** [comment]
FYI, I have just completed collecting the list of [CHANGES](https://github.com/SOCI/soci/blob/d769e5f923c4ae0dd59db08718d77dbebd8993f7/CHANGES) up to now.

**Comment by mloskot** [comment]
[Freezing master and branching release/4.0](https://sourceforge.net/p/soci/mailman/message/36773320/) has happened.

**Comment by alexchenfeiyu** [comment]
Hi, I'd like to know when the  4.0.0 will be officially released? 
Do you have any plans?
I may not be able to use the master directly because my project requires me to use the release version.

**Comment by mloskot** [comment]
I planned to publish release candidates a week ago plans, but I was busy with other things.
I'm hoping to publish RC1 over the weekend.

> I may not be able to use the master directly because my project requires me to use the release version.

In practice, there will no completely no difference w.r.t. features or stability because
current `master` branch equals current `release/4.0` branch, and RC[1-3] and final release package will equal the branches.

**Comment by mloskot** [comment]
I have just published SOCI 4.0.0 RC1 calling for tests

https://sourceforge.net/p/soci/mailman/message/36793193/

I'm expecting final release in a week or so, depending on stream of RC issues reported back.

**Comment by mloskot** [comment]
[SOCI 4.0.0 has been released](https://github.com/SOCI/soci/blob/6dcfe530f213ce664c0c0e198e8e6d929fea3328/scripts/release.sh)

Please, prefer the mailing lists for questions.
