### ISSUE TITLE
Can you update vcpkg install?

### ISSUE THREAD

**Issue by IronsDu** [SOCI/soci#637]
Because 'https://github.com/Microsoft/vcpkg/tree/master/ports/soci' install is old.

**Comment by mloskot** [comment]
I'm busy with preparing new release. Why don't you update yourself the URL, date, checksum to point to the latest master. Anyone can submit or update vcpkg ports.

**Comment by ras0219-msft** [comment]
I've pushed a branch with the latest update [1] and I intend to merge it if the CI passes. This also switches SOCI to use `vcpkg_from_github()` so we'll be able to automatically pick up any updates in the future :)

[1] https://github.com/Microsoft/vcpkg/tree/dev/roschuma/soci

**Comment by mloskot** [comment]
@ras0219-msft Awesome,thank you!

**Comment by ras0219-msft** [comment]
Merged!

To keep with standard policy, we'll wait until 4.0.0 is truly released (with a tag that won't move) to pull it in as `soci`. Since there will be no future maintenance of 3.x, we won't have a `soci3`.

**Comment by mloskot** [comment]
@ras0219-msft Good plan. Thank you!

Meanwhile, I'm closing as addressed.

**Comment by IronsDu** [comment]
@ras0219-msft Can't find `/backends/mysql/factory.cpp` alter install soci. 
Because I not install mysql driver in my computer?

**Comment by mloskot** [comment]
@IronsDu https://github.com/Microsoft/vcpkg/blob/b142632afdba938a7fc7386074c5d8446e1d7ab0/ports/soci/portfile.cmake#L27-L33 Possibly, someone will be able to help. I am not able to maintain any aspects of SOCI 3.x, so I can't help. However, I will *try* to help with vcpkg ports for SOCI 4, once it is released. No promises though and help will be appreciated. (Porting vcpkg packages is not difficult!)

Please, move questions and issues about vcpkg to https://github.com/Microsoft/vcpkg
