### ISSUE TITLE
Use of deprecated std::ptr_fun

### ISSUE THREAD

**Issue by JoeLoser** [SOCI/soci#651]
**Problem:**
I would like to use soci with `-std=c++17` applied. There is [one usage](https://github.com/SOCI/soci/blob/master/src/backends/sqlite3/statement.cpp#L495) `std::ptr_fun` which is deprecated in C++17. 

**Solution:**
Replace the usage with a lambda inline if there is compiler support for lambdas (so, C++11 onward I suppose). For example:

```
-    std::string::iterator siter = std::find_if(dt.begin(), dt.end(), std::not1(std::ptr_fun(isalnum)));
+    std::string::iterator siter = std::find_if(dt.begin(), dt.end(), [](const auto c) { return std::isalnum(c); });
```

**Comment by mloskot** [comment]
@JoeLoser The only fix suggestion I see feasible for now would be 
```
if defined(SOCI_HAVE_CXX_C11) || (defined(_MSC_VER) && _MSC_VER >= 1800)
    std::string::iterator siter = std::find_if(dt.begin(), dt.end(), [](const auto c) { return std::isalnum(c); });
else
    std::string::iterator siter = std::find_if(dt.begin(), dt.end(), std::not1(std::ptr_fun(isalnum)));
```

From a maintenance point, it would be easier if we could switch SOCI 4.x to C++11 compilation mode by default. I'm not sure if it is possible though. @vadz Thoughts on that?

**Comment by vadz** [comment]
We still use SOCI with pre-C++11 compilers (not by choice, believe me...). I think it would make sense to release 4.0 as the last C++98-compatible version and require C++11 (or even 14 or 17...) in SOCI 5.0.

**Comment by mloskot** [comment]
@vadz Works for me.

**Comment by mloskot** [comment]
@jivancic Good catch, updated the snipped. Thanks
