### ISSUE TITLE
Testcase "MS SQL long string" fails for ODBC backend used for MSSQL Server

### ISSUE THREAD

**Issue by hrabe** [SOCI/soci#654]
It's interesting, that this test seems to work on AppVeyor runs but not if it's running against a MSSQL Server on macOS with following environment:
```
macOS High Sierra 10.13.5
Docker version 18.03.1-ce, build 9ee9f40
docker image: microsoft/mssql-server-linux:2017-latest
unixODBC 2.3.6
freetds v1.00.91
```

Failed test:

```
2/6 Test #2: soci_odbc_test_mssql .............***Failed   10.35 sec

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
soci_odbc_test_mssql is a Catch v1.9.6 host application.
Run with -? for options

-------------------------------------------------------------------------------
MS SQL long string
-------------------------------------------------------------------------------
/Users/heikorabe/Github-private/soci/tests/odbc/test-odbc-mssql.cpp:23
...............................................................................

/Users/heikorabe/Github-private/soci/tests/odbc/test-odbc-mssql.cpp:61: FAILED:
explicitly with message:
  Read back string of length 8000 instead of expected 9890

===============================================================================
test cases:   47 |   46 passed | 1 failed
assertions: 1420 | 1419 passed | 1 failed
```

Is this test expected to be general a problem due to limitation of `varchar`/`nvarchar`columns like also discussed here https://github.com/SOCI/soci/issues/383 ?

**Comment by vadz** [comment]
Sorry, I won't be able to debug this under macOS and the test succeeds under Linux using unixODBC, so I'm not sure what's going on here. If you could please try to debug it, it would definitely be very helpful, TIA!

**Comment by mloskot** [comment]
This looks like the value is truncated due to hitting the default limit

I haven't looked into details of the ODBC backend implementation, but it might be related to this 'complexitu' of `varbinary` and `varchar` size rules:

1. https://docs.microsoft.com/en-us/sql/relational-databases/native-client/features/using-large-value-types?view=sql-server-2017

> Large value data types can have a maximum size between **1 and 8 KB**, or they can be specified as **unlimited**.

2. https://docs.microsoft.com/en-us/sql/t-sql/data-types/binary-and-varbinary-transact-sql?view=sql-server-2017

> - When n is not specified in a data definition or variable declaration statement, the **default length is 1**.
> - When n is not specified with the CAST function, the **default length is 30**.

**Comment by hrabe** [comment]
But [https://docs.microsoft.com/en-us/sql/relational-databases/native-client/features/using-large-value-types?view=sql-server-2017](https://docs.microsoft.com/en-us/sql/relational-databases/native-client/features/using-large-value-types?view=sql-server-2017) also states as info:

> If replicating data you may need to configure the max text repl size server configuration option to -1.

Which leads to [https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/configure-the-max-text-repl-size-server-configuration-option?view=sql-server-2017](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/configure-the-max-text-repl-size-server-configuration-option?view=sql-server-2017) and reconfigure server somehow?

```
USE AdventureWorks2012 ;  
GO  
EXEC sp_configure 'show advanced options', 1 ;   
RECONFIGURE ;   
GO  
EXEC sp_configure 'max text repl size', -1 ;   
GO  
RECONFIGURE;   
GO
```
but it should have as default _65536_ already set.

FYI: I also used _freetds_ fresh build from HEAD.

**Comment by mloskot** [comment]
I'd also allow for possibility of a difference between driver behaviours or even a driver bug.
I personally always take the new [Microsoft ODBC Driver for SQL Server](https://docs.microsoft.com/en-us/sql/connect/odbc/microsoft-odbc-driver-for-sql-server?view=sql-server-2017) as a reference.

If this particular test is failing for FreeTDS/OSX only, I see no problem to skip it for that environment.

**Comment by hrabe** [comment]
I will check the Microsoft driver MSSQL17 now on macOS using tapped brew. Will see if this makes any difference. Thanks for the linked resource. Will update and report here soon.

**Comment by hrabe** [comment]
@mloskot Using your suggested driver [**ODBC Driver 17 for SQL Server**] from Microsofts tapped brew formula the tests running successful on macOS High Sierra. So this bug is related to **FreeTDS** version v1.00.91 and HEAD somehow.

```
 ctest --output-on-failure -R soci_odbc_test_mssql
Test project /Users/heikorabe/Builds/soci
    Start  9: soci_odbc_test_mssql
1/2 Test  #9: soci_odbc_test_mssql .............   Passed   14.39 sec
    Start 10: soci_odbc_test_mssql_static
2/2 Test #10: soci_odbc_test_mssql_static ......   Passed   14.44 sec

100% tests passed, 0 tests failed out of 2

Total Test time (real) =  28.84 sec
```

So should this issue be renamed and kept open for **freetds v1.00.91 / v1.1.dev.20180611** or can be closed due to working driver exists? (May be a bug request to FreeTDS could be filed?)

**Comment by mloskot** [comment]
If there is no longer an issue in SOCI, I'd just close this.
FreeTDS is external to SOCI and SOCI does not depend on FreeTDS.

> May be a bug request to FreeTDS could be filed

It is always a good idea to let an upstream know about any bug in their code. 

I don't use FreeTDS myself, so I'm not able to offer any help in working on any FreeTDS specific workarounds or fixes.

**Comment by hrabe** [comment]
Fine for me to close this issue. Will check how to file that to FreeTDS.

_BTW_: Nevertheless the **FreeTDS** seems faster than **Microsoft** (even if 1 test failed) with a diff of 4-5 sec out of 14.5 total. Would meet FreeTDS is approx. 33% faster than vendor 😄

**Comment by mloskot** [comment]
Microsoft is Unix newbie still ;)
