### ISSUE TITLE
How to increase std::string buffer size for Oracle data exchange?

### ISSUE THREAD

**Issue by ristillu** [SOCI/soci#667]
I had a SQL query that aggregates data into a CLOB and then exchanges via soci into a std::string. Most of the time it worked but occasionally it would truncate. I couldn't work out why until I noticed in src/backends/oracle/standard-into-type.cpp there is:
```C++
   case x_stdstring:
        oracleType = SQLT_STR;
        size = 32769;  // support selecting strings from LONG columns
        buf_ = new char[size];
        data = buf_;
        break;
```
Could this be instead increased to something more analogous to std::string::max_size()? On my machine, for example, this value is 4611686018427387897, which is just slightly bigger than `2**15 + 1`. Even if it were hardcoded to `2**32 + 1` that would give a lot more leeway.

As it is, I can't use this CLOB query with soci unfortunately.

**Comment by vadz** [comment]
Just for the record, SOCI has a dedicated API for BLOBs, which is implemented for Oracle. I think you should use it instead.

In any case, allocating 4GiB of RAM for every string parameter is clearly not the right way.

**Comment by ristillu** [comment]
Yeah I was thinking about that. I might try. In this case my data is CSV Clob data, so if there's a nice way to turn that into a blob on the database that will be my approach.

**Comment by mloskot** [comment]
Answer: use the dediccated BLOB API
