### ISSUE TITLE
Use of angle brackets around file names for include statements

### ISSUE THREAD

**Issue by elfring** [SOCI/soci#672]
Would you like to [replace any double quotes](https://github.com/SOCI/soci/blob/1655a195ee244791a34a2448ca3297f6e8d70016/include/soci/soci.h#L12 "Check inclusion style") by [angle brackets around file names for include statements](https://stackoverflow.com/questions/21593/what-is-the-difference-between-include-filename-and-include-filename "What is the difference between #include <filename> and #include “filename”?")?

**Comment by mloskot** [comment]
Unless your suggestion is due to an *actual* issue you're experiencing, thank you, but no.

**Comment by elfring** [comment]
[The Boost software licence is used here](https://github.com/SOCI/soci/blob/b6d97ffa6fb5b30514e6aeabead5c2b025ed6f13/LICENSE_1_0.txt#L1 "Licence information").
* Do you care then for example why [the boost class library](https://www.boost.org/ "Portable C++ source libraries") is using angle brackets in include statements for corresponding header files?
* Would you like to apply the same design patterns?

**Comment by mloskot** [comment]
The fact SOCI uses Boost license does not make any connection to any of Boost guidelines. No, please don't, unless you have a specific bug to report.

**Comment by elfring** [comment]
I suggest to reconsider the consequences of [the following wording](http://c0x.coding-guidelines.com/6.10.2.html "Source file inclusion") from [the section “16.2 Source file inclusion”](http://open-std.org/jtc1/sc22/wg21/docs/papers/2013/n3797.pdf "Draft for the C++ standard specification") in the standard specification for the programming language “C++”.

```
…
The named source file is searched for in an implementation-defined manner. If this search is not supported, or if the search fails, the directive is reprocessed as if it read

#include <h-char-sequence> new-line
…
```
- How do you think about to avoid “a duplicated file search” here?
- Would you like to [restrict the searched directories](https://gcc.gnu.org/onlinedocs/cpp/Include-Syntax.html "Description for include syntax") for header files of your software?
