### ISSUE TITLE
How to get actual query of statement with bound input values

### ISSUE THREAD

**Issue by handy1989** [SOCI/soci#678]
```cpp
string first_name = "Steve";
string last_name = "Jobs";
sql << "insert into test(first_name, last_name)"
    " values(:first_name, :last_name)",
    use(first_name), use(last_name);
```

when I use `sql.get_query()`， the result is `insert into test(first_name, last_name) values(:first_name, :last_name)`

but what I expected is `insert into test(first_name, last_name) values('Steve', 'Jobs')`

**Comment by mloskot** [comment]
AFAICT, it is not possible.

**Comment by handy1989** [comment]
how about add a function of `mysql_statement_backend` like this
```cpp
class statement_backend
{
    virtual std::string get_real_query()
    {
        return "";
    }
};
```
and implements it in mysql_statement_backend(for example)
```cpp
struct mysql_statement_backend
{
    std::string query_;

    virtual std::string get_real_query()
    {
        return query_;
    }
}；

```
asign the real query to query_ before mysql_real_query in `mysql_statement_backend::execute`
```cpp
query_ = query;

//std::cerr << query << std::endl;
if (0 != mysql_real_query(session_.conn_, query.c_str(),
        query.size()))
{
      throw mysql_soci_error(mysql_error(session_.conn_),
          mysql_errno(session_.conn_));
}
```

fill the query to session in statement_impl::execute
```cpp
session_.set_got_data(gotData);
session_.set_real_query(backEnd_->get_real_query());
```

then we can get the actual query by adding a function named `session::get_real_query()`

**Comment by handy1989** [comment]
> AFAICT, it is not possible.

how about add a function of `mysql_statement_backend` like this
```cpp
class statement_backend
{
    virtual std::string get_actual_query()
    {
        return "";
    }
};
```
and implements it in `mysql_statement_backend`(for example)
```cpp
struct mysql_statement_backend
{
    std::string query_;

    virtual std::string get_actual_query()
    {
        return query_;
    }
}；

```
asign the actual query to query_ before executing `mysql_real_query` in `mysql_statement_backend::execute`
```cpp
query_ = query;

//std::cerr << query << std::endl;
if (0 != mysql_real_query(session_.conn_, query.c_str(),
        query.size()))
{
      throw mysql_soci_error(mysql_error(session_.conn_),
          mysql_errno(session_.conn_));
}
```

finnaly  fill the query to session in `statement_impl::execute`
```cpp
session_.set_got_data(gotData);
session_.set_actual_query(backEnd_->get_actual_query());
```

then we can get the actual query by adding a function named `session::get_actual_query()`

**Comment by vadz** [comment]
Just for the record, the exception message does contain the values of the parameters since 8bb66107a2132d424f441305d04ee71a39798f2b
