### ISSUE TITLE
C++17 / MSVC 2017

### ISSUE THREAD

**Issue by tikabass** [SOCI/soci#685]
We are starting to need a c++17 compliant library.

Here are the minimal changes needed to make SOCI c++17 compliant.
Note that SVN revision and working copy #s from my own repository. 
Source revision is tag 'soci-3.2.3'

diff format: [soci-cxx17.txt](https://github.com/SOCI/soci/files/2408852/soci-cxx17.txt)

**Comment by vadz** [comment]
Please use master for a version working with MSVS 2017. SOCI 3.x won't be updated.

**Comment by mloskot** [comment]
See https://github.com/SOCI/soci/wiki/Branches
