### ISSUE TITLE
CMake error

### ISSUE THREAD

**Issue by dkislov** [SOCI/soci#686]
On Windows 10 , with Visual Studio 2017 (version 15.7.4) , CMake version 3.12.1 I 'm trying to generate solution with this options:
cmake -G "Visual Studio 15 2017 Win64" -DSOCI_CXX_C11=ON -DSOCI_STATIC=OFF -DSOCI_TESTS=ON -DWITH_BOOST=OFF -DWITH_DB2=OFF -DWITH_FIREBIRD=OFF -DWITH_ODBC=OFF -DWITH_ORACLE=OFF -DWITH_POSTGRESQL=OFF -DWITH_SQLITE3=OFF -DWITH_MYSQL=ON -DMYSQL_INCLUDE_DIR="C:\Program Files\MySQL\MySQL Connector C 6.1\include" -DMYSQL_LIBRARIES="C:\Program Files\MySQL\MySQL Connector C 6.1\lib\libmysql.lib" ../src

And I'm getting errors:
CMake Error at core/CMakeLists.txt:11 (colormsg):
  Unknown CMake command "colormsg".

CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.12)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring incomplete, errors occurred!
See also CMakeOutput.log".

Can anyone to advise me how to solve it?

**Comment by mloskot** [comment]
> CMake version 3.12.1

Please, stop building SOCI 3.x , see https://github.com/SOCI/soci/wiki/Branches).
Pull the `master` branch and try this.

FYI, I'm half-way through complete rewrite of the CMake configuration and I'm hoping to release SOCI 4 with the new version in near future, it must happen this autumn.

**Comment by dkislov** [comment]
Sorry. But I did try master branch. Look at my screenshot...
![soci_build](https://user-images.githubusercontent.com/862667/46306030-ffb58b00-c5aa-11e8-9640-6272497693bc.png)

**Comment by mloskot** [comment]
I have no idea why you are running `cmake ../src` while you are supposed to point `cmake` to SOCI top-level directory, not `src` sub-directory.

Please, try a typical CMake workflow, for example:

```
git clone https://github.com/SOCI/soci.git
cd soci
mkdir _build.vs2017
cd _build.vs2017
cmake ..    # obviously, add options as you require
```

**Comment by dkislov** [comment]
Sorry , it was my bad with cmake ../src. Everything works. Thank you very much 👍

**Comment by mloskot** [comment]
I'm glad it works. 

BTW, http://soci.sourceforge.net/doc/master/installation/
