### ISSUE TITLE
Failed to find shared library for backend mysql

### ISSUE THREAD

**Issue by c1ewd** [SOCI/soci#687]
I'm creating the program on Windows platform. SOCI built by cmake: .. -G "Visual Studio 14 2015 Win64" -DSOCI_STATIC=OFF -DWITH_MYSQL=ON -DBOOST_ROOT=C:\libs\boost 

Source:
#include <iostream>
#include <stdlib.h>
#include <soci/soci.h>
#include <soci/soci-config.h>
#include <soci/mysql/soci-mysql.h>
#include <vector>

#include <exception>

using namespace soci;
using namespace std;

int main(int argc, char *argv[])
{
	try
	{
		session sql("mysql", "db=db_name user=db_user password=db_password");
	}
	catch (exception const &e)
	{
		cerr << "Error: " << e.what() << '\n';
	}

	getchar();
    return 0;
}
The program built with 0 errors but print: "Error: Failed to find shared library for backend mysql" then start
What libraries does not see the program?

**Comment by c1ewd** [comment]
PS: When cmake is working I saw "MySQL Embedded not found". What does it affect?

**Comment by vadz** [comment]
It doesn't find the DLL during run-time, please check your `PATH` (and if you don't want to deal with DLLs, then link statically). This doesn't have anything to do with the MySQL Embedded message, AFAIK.

**Comment by 363568233** [comment]
libmysql.dll  depends on openssl,  such as libcrypto-1_1-x64.dll 、 libssl-1_1-x64.dll
