### ISSUE TITLE
Is there a mailing list for users?

### ISSUE THREAD

**Issue by roboLoki** [SOCI/soci#689]
HI-

I finally got soci to work with query transformations. I am sure I did something wrong yesterday to make it not link right. I am interested in asking a coding question about usage of soci but this list seems to address more developer stuff. Is the sourceforge list still active? I searched around a bit and the threads seemed kind of old Please let me know. thx.

**Comment by roboLoki** [comment]
HI- I posted to sourceforge mailing list. I will wait patiently and see what happens. Have a cool weekend. thx.

**Comment by mloskot** [comment]
http://soci.sourceforge.net says:
> To meet other users, please consider subscribing to the SOCI-users mailing list.
> There is also SOCI-devel mailing list available dedicated to development discussions only.

https://github.com/SOCI/soci/blob/master/README.md displays [![Mailing Lists](https://img.shields.io/badge/mailing--lists-ok-yellowgreen.svg)](https://sourceforge.net/p/soci/mailman/), once you follow the links, soci-devel and soci-users lists are presented.

I don't know how the lists could be displayed more vividly :-)
