### ISSUE TITLE
SQLite backend accesses freed memory when using std::tm

### ISSUE THREAD

**Issue by pmir** [SOCI/soci#694]
When binding std::tm via soci::use(), sqlite backend creates a temporary string to convert the tm to text. This buffer is passed to sqlite3_bind_text and later deleted in post_use/clean_up.

This seems to work when calling execute(true), however, when reading multiple rows with execute(false) + fetch(), sqlite tries to use this (now deleted) text buffer, causing undpredictable results.

A simple query like this is enough to reproduce this issue. The output printed to stdout is garbage. Everything works if `std::tm datetime` is replaced with `std::string` and the date-to-string conversion is done in main()

```c++
#include <soci/soci.h>
#include <soci/sqlite3/soci-sqlite3.h>
#include <iostream>

int main()
{
	soci::session session;
	session.open(soci::sqlite3, ":memory:");

	std::tm datetime {};
	std::string output;

	soci::statement statement(session);
	statement.exchange(soci::use(datetime, "datetime"));
	statement.exchange(soci::into(output));
	statement.alloc();
	statement.prepare("select :datetime");
	statement.define_and_bind();
	statement.execute(false);

	while (statement.fetch())
	{
		std::cout << output << std::endl;
	}

	return 0;
}
```

This seems to match errors returned when running under Dr.Memory
```
Error #1: UNADDRESSABLE ACCESS of freed memory: reading 0x018048f8-0x018048fc 4 byte(s)
# 0 replace_memcpy                                     
# 1 sqlite3VdbeMemGrow
# 2 vdbeMemAddTerminator
# 3 sqlite3VdbeExec
# 4 sqlite3_step   
# 5 soci::sqlite3_statement_backend::fetch
# 6 soci::details::statement_impl::fetch
# 7 main                                                
Note: @0:00:00.699 in thread 26116
Note: next higher malloc: 0x01804998-0x018049ac
Note: prev lower malloc:  0x018048c8-0x018048d8
Note: 0x018048f8-0x018048fc overlaps memory 0x018048f8-0x0180490c that was freed here:
Note: # 0 replace_operator_delete_array                                 
Note: # 1 soci::sqlite3_standard_use_type_backend::post_use
Note: # 2 main
```

This can be fixed by passing SQLITE_TRANSIENT to sqlite3_bind_text under ```sqlite3_statement_backend::bind_and_execute```. However I'm not sure if that's the optimal solution - I'm not familiar with lifetimes of various soci types. Perhaps this buffer can be kept around until the statement is done?

**Comment by pmir** [comment]
Actually, all the unit tests only seem to insert an `std::tm` into a table or select it. For this issue to occur, the `std::tm` has to be accessed by SQLite after the statement has been executed. For example, if `std::tm` were to occur in a WHERE clause (this is how I originally noticed this issue), or simply bound to a placeholder and SELECTed, like above.
Oh, and just to be sure, I've tested this under Linux as well - same behavior, both valgrind and libasan fail.

**Comment by vadz** [comment]
Ah, I see. It would be great if you could please add a test case for this to the test suite and submit it, together with the fix in your fork, as a PR. TIA!

**Comment by dirkvdb** [comment]
I still ran into the issue using the 4.0 release.
I have created a pull request (#770) with the same fix but it also contains a test that reproduces the issue.

**Comment by mloskot** [comment]
The #770 has been merged.

@dirkvdb Thanks for the fix.
