### ISSUE TITLE
Add Cassandra database support

### ISSUE THREAD

**Issue by Joe-Yeh** [SOCI/soci#696]

**Comment by vadz** [comment]
This doesn't seem serious to me. Cassandra is not an SQL database and I have no idea how would it be useful to support it in SOCI.

**Comment by mloskot** [comment]
FYI, long time ago we briefly brainstormed w/ @msobczak that SOCI can be agnostic to query language and it should be feasible to add non-SQL backends for any tabular/tuple-based data sources (eg. CSV) or even NoSQL databases.

However, I have never investigated any of those further.
