### ISSUE TITLE
Batch select from oracle database fails in debug/win32 only

### ISSUE THREAD

**Issue by malkindan** [SOCI/soci#697]

**Comment by vadz** [comment]
Sorry, this is not very serious, what are we supposed to do with this? Please reopen if you can provide minimal example reproducing the problem or, ideally, an as small as possible patch to the test suite.

Also, information about the compiler and SOCI version you use wouldn't be superfluous.

**Comment by vadz** [comment]
3.2 is not supported any longer, please check if you have the same problem with 4.0.

**Comment by malkindan** [comment]
nuget.org has 3.2.  Do you plan to update it to 4.0?

**Comment by mloskot** [comment]
You need to ask maintainer(s) of the nudge packages.

We do not maintain any packages.

**Comment by vadz** [comment]
You do need to build SOCI yourself, but this is quite straightforward.

**Comment by mloskot** [comment]
@malkindan  Although there is no 4.0 release yet, the current `master` should be considered as stable.
The release could have happened any time now, it's just the matter of no time on my side.
If, however, the release happened already, you would still have to build it from sources yourself.
We do not provide binaries.
