### ISSUE TITLE
Can SOCI throw exception instead call abort to terminate the program?

### ISSUE THREAD

**Issue by akeyliu** [SOCI/soci#701]
Thanks for the project owner and contributors of SOCI first.

    The program is abort and terminated when some soci error occurs and catch for soci::soci_error not work.  Follow Error Message occurs: 
terminate called after throwing an instance of 'soci::sqlite3_soci_error'
  what():  sqlite3_statement_backend::prepare: near "id": syntax error

    I'm now using SOCI to connect Database for the product system, and most is using sqlite3 for fast performance.  The working logic is read some http request of JSON format, and read some URI, columns, table name, where condition for dynamic SQL process using prepare, normal logic is work, but failed when I test for exception with invalid column name, table name or where condition. 
1 . The version is SOCI master branch(3.2.3),  mingw c++ 5.4 using -std=gnu++14, boost 1.58, sqlite 3190300
2.  I compiled SOCI using follow configure: which SOCI_CXX_C11 is suggest to resolve it, but not work.
DSOCI_STATIC=ON -DSOCI_TESTS=OFF -DWITH_BOOST=ON -DSOCI_CXX_C11=ON 

   So, if there is some instruction i.e. define Macro or build flag to enable catch all exception by soci::soci_error not call abort which will terminal the program running? 

Thanks.

**Comment by vadz** [comment]
You need to use SOCI 4 (i.e. current git master) with C++11 or later to get correct `noexcept` on various helper classes dtors.

**Comment by akeyliu** [comment]
Thanks for your comments.
 
I download and compiled soci 4.0 in Mingw gcc 5.4  with -DSOCI_STATIC=ON -DSOCI_TESTS=OFF -DWITH_BOOST=ON -DSOCI_CXX_C11=ON,  and still call abort not throw a soci:soci_error exception.

**Comment by vadz** [comment]
Sorry, not sure what's going on then. Can you make the absolutely minimal example reproducing the problem? Also, perhaps you can run it under gdb and check what happens, i.e. where is the exception thrown from?
