### ISSUE TITLE
POSTGRESQL_LIBRARIES does not working

### ISSUE THREAD

**Issue by tt4g** [SOCI/soci#702]
I defined variable `POSTGRESQL LIBRARIES`, but it didn't work. Worked by defining `POSTGRESQL LIBRARY` instead.

I have read document of master branch and have defined this variable.

> https://github.com/SOCI/soci/blob/master/docs/installation.md
> POSTGRESQL_LIBRARIES - string - Full paths to libraries to link SOCI against to enable the backend support.

I think it is because `find_library` uses` POSTGRESQL_LIBRARY`.

https://github.com/SOCI/soci/blob/3a1f602b3021b925d38828e3ff95f9e7f8887ff7/cmake/modules/FindPostgreSQL.cmake#L127

https://github.com/SOCI/soci/blob/3a1f602b3021b925d38828e3ff95f9e7f8887ff7/cmake/modules/FindPostgreSQL.cmake#L164

Which define variable is correct for me?

**Comment by mloskot** [comment]
Thanks for the report. There is a mismatch indeed. The `FindPostgreSQL.cmake` needs to be improved.

**Comment by tt4g** [comment]
Sorry.
There was a part that was not enough for this issue.

It seems that only `FindFirebird.cmake` and` FindMySQL.cmake` use `find_library(${BACKEND}_LIBRARIES)`,
Other modules use `find_library(${BACKEND}_ LIBRARY)` and `set(${BACKEND}_LIBRARIES ${BACKEND}_ LIBRARY)`.

So only `MYSQL_LIBRARIES` and `FIREBIRD_LIBRARIES` are referenced.

**Comment by mloskot** [comment]
Fixed in https://github.com/SOCI/soci/commit/560cdeb16c43c851d2e5ebf48c6494e910e06817

```
POSTGRESQL_LIBRARY is input variable while POSTGRESQL_LIBRARIES
is variable set by the Find-module.

Waning: This is known issue of Find-modules in SOCI distribution that
they are not unified regarding FOO_LIBRARIES vs FOO_LIBRARY naming.
Most accept or expect FOO_LIBRARIES as input variable.
This should be improved in future, once CMake scripts are modernised
and switched to CMake 3 best practices.
```

**Comment by tt4g** [comment]
Thanks!
