### ISSUE TITLE
int64_t support for sqlite3

### ISSUE THREAD

**Issue by mohansella** [SOCI/soci#719]
Looks like there is no full support for int64_t with sqlite3. since, sqlite3 datatype `SQLITE_INTEGER` is mapped to `soci::dt_integer` in soci. I guess it needs to be mapped to `soci::dt_long_long`. But it is a breaking change. 

Also, the common api : `soci::get_last_insert_id` gives int32_t which may also need to be changed.

**Comment by mloskot** [comment]
There is chance for a breaking change to be accepted into SOCI 4.
If you'd be willing to provide a PR, so it can be CI tested. Then, we will be able to review and decide.

/cc @vadz

**Comment by mohansella** [comment]
Getting below error while compiling in travis. 

```
In file included from /usr/include/c++/4.6/cstdint:35:0,
                 from /home/travis/build/SOCI/soci/include/soci/soci-backend.h:15,
                 from /home/travis/build/SOCI/soci/include/soci/backend-loader.h:11,
                 from /home/travis/build/SOCI/soci/src/core/backend-loader.cpp:10:
/usr/include/c++/4.6/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the upcoming ISO C++ standard, C++0x. This support is currently experimental, and must be enabled with the -std=c++0x or -std=gnu++0x compiler options.```

shall i change the flags with -std=c++0x?

**Comment by mloskot** [comment]
See https://github.com/SOCI/soci/pull/720#issuecomment-475188038

**Comment by mohansella** [comment]
@mloskot , Thanks for merging the `get_last_insert_id` changes to support 64 bit value. 

Getting back to the first isssue, 
>`SQLITE_INTEGER` is mapped to `soci::dt_integer` in soci. I guess it needs to be mapped to `soci::dt_long_long` as an option/default to read 64 bit value.

need some comments. because, reading 64bit value from sqlite3 is a must for me.

**Comment by mloskot** [comment]
The 64-bit integer support is there, but you mean https://github.com/SOCI/soci/pull/721#issuecomment-475324131

If there is no clear way to detect those as BIGINT, I have no any immediate recommendations how to work around this.

By the way, `AUTOINCREMENT` is best avoided:

> The AUTOINCREMENT keyword imposes extra CPU, memory, disk space, and disk I/O overhead and should be avoided if not strictly needed. It is usually not needed. 

https://www.sqlite.org/autoinc.html

**Comment by vadz** [comment]
I'm afraid that not only I don't have the solution to the problem, but I don't even really understand what exactly the problem is. You seem to imply that it's related to `dt_integer` interpretation, but where exactly is this problematic?

I must also admit that I'm somewhat confused by `data_type` enum in general as it's not really clear what exactly is it supposed to represent and where is it used. In particular, it seems pretty weird that it has just `dt_integer` (and not `dt_short`, `dt_unsigned` and all the other combinations) but both `dt_long_long` and `dt_unsigned_long_long`...

**Comment by mohansella** [comment]
I have changed my column types from `INTEGER` to `BIGINT` and even the foreign keys referring to `AUTOINCREMENT INTEGER`. Things working as expected.

**Comment by mloskot** [comment]
@vadz Yes, that is confusing and an improvement would be to simply cover all C++ fundamental types. Long time ago I started sketching the idea https://github.com/SOCI/soci/wiki/RFC1 but I never had time to go around. Something for 5.0.0.
