### ISSUE TITLE
Linker errors for building mysql interface

### ISSUE THREAD

**Issue by BoggGod** [SOCI/soci#726]
Hey,
I tried to test the installation with a slightly modified example http://coliru.stacked-crooked.com/a/f8da40e4c9fc2c62

however, it fails with linker errors I struggle to understand, since I've included all the relevant libraries from the documentation.

```
cesar@debian:~/prog/cpp-tests$ g++ main.cpp -lsoci_core -lsoci_mysql -ldl -lmysqlclient
/usr/bin/ld: /tmp/ccpSdqDA.o:(.data.rel.ro._ZTVN4soci7details9into_typeINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEE[_ZTVN4soci7details9into_typeINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEE]+0x28): undefined reference to `soci::details::standard_into_type::pre_exec(int)'
/usr/bin/ld: /tmp/ccpSdqDA.o:(.data.rel.ro._ZTVN4soci7details9into_typeIiEE[_ZTVN4soci7details9into_typeIiEE]+0x28): undefined reference to `soci::details::standard_into_type::pre_exec(int)'
/usr/bin/ld: /tmp/ccpSdqDA.o:(.data.rel.ro._ZTVN4soci7details8use_typeINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEE[_ZTVN4soci7details8use_typeINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEE]+0x30): undefined reference to `soci::details::standard_use_type::dump_value(std::ostream&) const'
/usr/bin/ld: /tmp/ccpSdqDA.o:(.data.rel.ro._ZTVN4soci7details8use_typeINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEE[_ZTVN4soci7details8use_typeINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEE]+0x38): undefined reference to `soci::details::standard_use_type::pre_exec(int)'
collect2: error: ld returned 1 exit status
```

**Comment by vadz** [comment]
Are you using static libraries? If so, you must list them in the correct order: `-lsoci_mysql` first, before `-lsoci_core`.

**Comment by BoggGod** [comment]
I'm not 

> Are you using static libraries? If so, you must list them in the correct order: `-lsoci_mysql` first, before `-lsoci_core`.



> Are you using static libraries? If so, you must list them in the correct order: `-lsoci_mysql` first, before `-lsoci_core`.

I don't believe so. Both .so and .a files are available for all libraries, but I have not specified to use .a. I have attempted compilation in the way seen above. Putting -lsoci_mysql before -lsoci_core also didn't change anything, unfortunately.

**Comment by BoggGod** [comment]
Alright!
Undoing my specifications of header locations and using this instead worked:

 g++ main.cpp -I/usr/include/soci -I/usr/include/soci/mysql -I/usr/include/mariadb -lsoci_core -lsoci_mysql -ldl -lmysqlclient
