### ISSUE TITLE
mixing bind by position and by name

### ISSUE THREAD

**Issue by redboltz** [SOCI/soci#732]
Can I mix `use()` by position and by name?

http://soci.sourceforge.net/doc/3.2/exchange.html#bind_position
http://soci.sourceforge.net/doc/3.2/exchange.html#bind_name

For example,

```cpp
string addr = "...";
int id = 7;
sql << "update person"
       " set mainaddress = :addr, contactaddress = :addr"
       " where id = :id",
       use(addr, "addr"), use(id); // by name first, and then by position
```

```cpp
string addr = "...";
int id = 7;
sql << "update person"
       " set mainaddress = :addr, contactaddress = :addr"
       " where id = :id",
       use(id), use(addr, "addr"); // by position first, and then by name
```

Are both example matched `:addr` with `addr` twice and `:id` with `id`?
Or mix is dangerous (prohibited) ?

**Comment by redboltz** [comment]
I've tested and got following result:

```
terminate called after throwing an instance of 'soci::soci_error'
  what():  Binding for use elements must be either by position or by name while executing "query string"
```

It seems that soci checks the combination of by position and by name, and if they are mixed, exception is thrown. So the answer is prohibited, in addition checking by soci correctly.

**Comment by mloskot** [comment]
I'm glad you've confirmed that.
