### ISSUE TITLE
What are differences between SOCI 3.x and 4.0?

### ISSUE THREAD

**Issue by SzykCech4** [SOCI/soci#743]
Hi
I am newbie to the SOCI. So I have quesition:
What are differences between SOCI 3.x and 4.0?
Maybe it is obvious to library programmers, but very interesting from apps programmers point of view. Any hints and links appreciated.

**Comment by mloskot** [comment]
Mostly bug fixes, lots of! It's impossible to tell in details before release notes are collected.
