### ISSUE TITLE
When Boost library is required when I compile SOCI 3.x?

### ISSUE THREAD

**Issue by SzykCech4** [SOCI/soci#746]
When Boost library is required when I compile SOCI 3.x?
For what features it is required?
In most compile command examples it is disabled. I notice this on the page: http://soci.sourceforge.net/doc/3.2/installation.html
```
$ mkdir build
$ cd build
$ cmake -G "Unix Makefiles" -DWITH_BOOST=OFF -DWITH_ORACLE=OFF (...) ../soci-X.Y.Z
$ make
$ make install
```

**Comment by vadz** [comment]
See #745.
