### ISSUE TITLE
undefined reference to `soci::details::standard_use_type::dump_value(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) const'

### ISSUE THREAD

**Issue by firesWu** [SOCI/soci#750]
![image](https://user-images.githubusercontent.com/14926995/64635256-d85d7400-d431-11e9-9d0e-95d4f4fabf07.png)

'libsoci_core.so' include 'dump_value', but still report error.

**Comment by vadz** [comment]
Sorry, but I don't think this is a SOCI problem at all. Please check your link command and determine where is the "missing" symbol referenced. You can use `nm` to check for this too.

P.S. Please don't use images to show text, this is just actively unhelpful (e.g. I can't copy and paste the name of the symbol).
