### ISSUE TITLE
Add support for CMAKE_CXX_STANDARD setting interacting with SOCI_CXX11

### ISSUE THREAD

**Issue by mloskot** [SOCI/soci#752]
This is follow-up to discussion started in https://github.com/SOCI/soci/issues/620#issuecomment-533304847 where @5cript suggested:

> And what about optionally checking against __cplusplus if existant/supported,
> secondarily using the special soci cmake option? In principal this allows for
> CMAKE_CXX_STANDARD where supported.

I'd suggest to consider the following, for example:

- If user sets `SOCI_CXX11=ON`, then `CMAKE_CXX_STANDARD=11` is set implicitly.
- If user sets `CMAKE_CXX_STANDARD=11`, then `SOCI_CXX11=ON` is set implicitly
- If user sets `CMAKE_CXX_STANDARD=17` or `=14` or later, then likely `SOCI_CXX11=ON` should be set implicitly too.

(UPDATE: `SOCI_CXX11` is new name since #757)

From CMake perspective, I don't see any reason to fiddle with `__cplusplus`.

Contributions via PRs are always welcome and appreciated.
If any arrives on time for SOCI 4.0.0, then such improvement will be included in this upcoming release.

**Comment by 5cript** [comment]
> If user sets SOCI_CXX_C11=ON, then CMAKE_CXX_STANDARD=11 is set implicitly.

If one wants to do that, Checking if both are supplied is important or we might overwrite user settings unintentionally.
But regardeless, I wouldn't say that SOCI_CXX_C11=ON --implies--> CMAKE_CXX_STANDARD=11.
Only the reverse should be true.

```CMake
if (NOT DEFINED CMAKE_CXX_STANDARD AND SOCI_CXX_C11 EQUAL ON) 
  CMAKE_CXX_STANDARD=11
endif()
```

> If user sets CMAKE_CXX_STANDARD=11, then SOCI_CXX_C11=ON is set implicitly

```CMake
if (DEFINED CMAKE_CXX_STANDARD AND (CMAKE_CXX_STANDARD EQUALS 11) OR (CMAKE_CXX_STANDARD GREATER 11))
  SOCI_CXX_C11=ON
endif()
```

> From CMake perspective, I don't see any reason to fiddle with __cplusplus.

I made the remark to __cplusplus as a way to handle it in the C++ code, outside of CMake, in the form of:
```C++
#if defined(SOCI_HAVE_CXX_C11) || (defined(_MSC_VER) && _MSC_VER >= 1900) || __cplusplus >= 201103L)
```
I'd even consider this a bug regarding compiler support.
https://github.com/SOCI/soci/blob/f8d036e71933d23c8192b920ab98f5635001a63f/include/soci/soci-platform.h#L139

**Comment by mloskot** [comment]
> I wouldn't say that SOCI_CXX_C11=ON --implies--> CMAKE_CXX_STANDARD=11.
> Only the reverse should be true.
> 
> if (NOT DEFINED CMAKE_CXX_STANDARD AND SOCI_CXX_C11 EQUAL ON) 
>   CMAKE_CXX_STANDARD=11
> endif()

What your code snipped illustrates is actually the "SOCI_CXX_C11=ON implies CMAKE_CXX_STANDARD=11" with a guarding tweak "only of no other CMAKE_CXX_STANDARD" is requested.

> In the end I think the single fix in 'soci-platform.h' is the simplest, that does not need me to check against cmake-stoneage

I agree what can be achieved in C++ code, should be achieved in C++ code.

Feel free to submit PR.

**Comment by 5cript** [comment]
> What your code snipped illustrates is actually the "SOCI_CXX_C11=ON implies CMAKE_CXX_STANDARD=11" with a guarding tweak "only of no other CMAKE_CXX_STANDARD" is requested.

I know, this is why I did it this way. :)
PR will come as soon as able.

**Comment by mloskot** [comment]
I have just proposed implementation for this issue in #758
