### ISSUE TITLE
Empty row

### ISSUE THREAD

**Issue by thomaswidmaier** [SOCI/soci#761]
I´m using rowset with row and cannot get it to work in one project while in a test scenario it works.
The rowset can be iterated over correctly for the number of rows I expect, but the size of each row is zero. Using 'into' on different separate variables does produce the correct contents.
I need the dynamic binding as I do not know the column type in advance.
Any hints on what could possibly be wrong in my link order or how I could diagnose this ? 
Using ODBC with freeTDS and soci 3.2.2 on Linux with clang. Also boost is used.
Thank you, Thomas

**Comment by mloskot** [comment]
Try current `master` branch aka `release/4.0` which is about to be out
