### ISSUE TITLE
cmake_policy warning

### ISSUE THREAD

**Issue by abrownsword** [SOCI/soci#771]
SOCI 4.0.0 issues a warning about cmake_policy CMP0048 which cannot be suppressed from the an 'outer' cmake build.  This appears to be because the cmake_minimum_required to 2.8 resets the policies.  Ideally after setting the minimum, the following would also be in the CMakeLists.txt:

```
if (NOT CMAKE_VERSION VERSION_LESS "3.00")
	cmake_policy(SET CMP0048 NEW)
endif()
```

That should suppress the warning being emitted.

**Comment by mloskot** [comment]
Please, consider to submit a PR against the current master.
