### ISSUE TITLE
Soci fails to detect certain SQLite column types

### ISSUE THREAD

**Issue by Cavaler** [SOCI/soci#783]
In src/backends/sqlite3/statement.cpp there is a static map describing column types, and it contains strings like "unsigned big int" - correct. However, in describe_column() only first alphanumeric part of description is analyzed - resulting in 'unsigned' for aforementioned type.
Proposed solution - retain all alphanumeric or spaces.

**Comment by Cavaler** [comment]
Here is a proposed patch
[type_describe.patch.zip](https://github.com/SOCI/soci/files/4161033/type_describe.patch.zip)

**Comment by vadz** [comment]
Could you please make a PR out of this patch, so that CI builds run for it? TIA!
