### ISSUE TITLE
Will SOCI v4.0.0 work for Firebird v3.0 !?

### ISSUE THREAD

**Issue by tomay3000** [SOCI/soci#787]
I was wondering if SOCI v4.0.0 works for Firebird v3.0.
Before I upgrade to Firebird v3.0 I have to make sure it works for this version of Firebird, if not, then I have no other option except to stick to version 2.5.

TIA.

**Comment by vadz** [comment]
Yes, it works with FB 3, but please don't open issues for questions, but post them to the mailing list instead.

**Comment by tomay3000** [comment]
OK, thank you.
