### ISSUE TITLE
Error not caught

### ISSUE THREAD

**Issue by kireevm96** [SOCI/soci#789]
An error occurs:
Code
`
#include "soci.h"
using namespace soci;
using namespace std;

int main() {
    try {
     session sql_fb("firebird", "service=/opt/firebird/examples/empbuild/employee.fdb user=SYSDBA password=masterkey");
     sql_fb << "SELECT COUNT(*) FROM TESTNOTABLE";
    } catch (soci_error const & e) {} 
    return 0;
}`

`terminate called after throwing an instance of 'soci::firebird_soci_error'
  what():  Dynamic SQL Error
SQL error code = -204
Table unknown
TESTNOTABLE
At line 1, column 22 while preparing "SELECT COUNT(*) FROM TESTNOTABLE".
Aborted (core dumped)
`
If you use the prepare method, then the error is caught

**Comment by sruehlemann** [comment]
We also noticed that some errors were not properly caught, which wasn't a real problem so far. But thanks to your issue, I debugged the code, and found that our application was build with C++11 (which expect destructors not to throw), but SOCI is not using C++11 by default, so the include files from SOCI does not expand destructors with `noexept(false)`.

If you build SOCI with `-DSOCI_CXX11=ON`, you'll see this line in `soci-config.h`
```
// Enables C++11 support
#define SOCI_HAVE_CXX11
```

which then expand this to `noexept(false)`
```
#if defined(SOCI_HAVE_CXX11) || (defined(_MSC_VER) && _MSC_VER >= 1900)
    #define SOCI_NOEXCEPT_FALSE noexcept(false)
#else
    #define SOCI_NOEXCEPT_FALSE
#endif
```

for the destructor of this class, which raises the exception.
```
class SOCI_DECL once_temp_type
{
public:

    once_temp_type(session & s);
    once_temp_type(once_temp_type const & o);
    once_temp_type & operator=(once_temp_type const & o);

    ~once_temp_type() SOCI_NOEXCEPT_FALSE;
```

Then you should again get those exceptions caught.

**Comment by vadz** [comment]
Yes, you definitely have to build SOCI with this switch on when using C++11 compiler. We probably should add a `__cplusplus` check to detect mismatches here, as they're fatal.

But for now I'm closing this one because if it's really due to such mismatch, it's not really a bug in SOCI.
