### ISSUE TITLE
在 vcpkg 中没有 soci[oracle] 的功能选项

### ISSUE THREAD

**Issue by tmiqpl** [SOCI/soci#794]
因此我无法使用基于oracle的后端.

**Comment by tmiqpl** [comment]
soci::session conn("oracle", "server=*** user=**** password=****");

error: Failed to find shared library for backend oracle

**Comment by vadz** [comment]
Sorry, but this is not an issue with the library. Please check that the DLL is somewhere on the PATH.

**Comment by tmiqpl** [comment]
> Sorry, but this is not an issue with the library. Please check that the DLL is somewhere on the PATH.

![image](https://user-images.githubusercontent.com/3240268/75772446-f2e02c80-5d86-11ea-8779-d1d03c32d9ee.png)
没有soci[oracle]的选项, 编译完也没有生成 soci_oracle.dll 
![image](https://user-images.githubusercontent.com/3240268/75772538-1905cc80-5d87-11ea-891a-df5baf08845f.png)

**Comment by vadz** [comment]
I don't read Mandarin but if you don't have Oracle backend, what's surprising about it not being available?

**Comment by tmiqpl** [comment]
是不是在vcpkg中漏掉了oracle后端, 还是不支持故意去掉的?

I don't speak English, I need Google Translate to talk to you
