### ISSUE TITLE
Can't catch `soci::sqlite3_soci_error`

### ISSUE THREAD

**Issue by zyzzyxdonta** [SOCI/soci#795]
Hi,
I'm planning to use SOCI with its SQLite backend to keep track of jobs that have to be executed. There will be multiple workers (instances of a program, so processes) accessing the database. Since I'm not anticipating a lot of parallel access (only every couple of seconds), a locked database should not be a problem since I can just retry after some milliseconds.

I wrote a little program to test out the concepts and syntax of SOCI which uses threads instead of processes. I used a new session object for each thread, as advised [in the documentation](http://soci.sourceforge.net/doc/release/4.0/multithreading/).
Once a thread tries to access the locked database, it throws an exception. I noticed that I can't catch this exception. Apparently it throws `soci::sqlite3_soci_error`.

Here is an example program (renamed to .txt since GitHub doesn't allow .cpp): 
[sqlite-test.txt](https://github.com/SOCI/soci/files/4306929/sqlite-test.txt)

Running it with 20 worker threads gives an output similar to this:
```
$ ./sqlite-test 20
140615183197952 counts 1
140615174805248 counts 2
140615166412544 counts 3
140615158019840 counts 4
140614947567360 counts 5
140614939174656 counts 6
140614930781952 counts 7
140614922389248 counts 8
140614913996544 counts 9
140614905603840 counts 10
140614897211136 counts 11
terminate called after throwing an instance of 'soci::sqlite3_soci_error'
140614343587584 counts 11
  what():  sqlite3_statement_backend::loadOne: database is locked while executing "DELETE FROM num_tid WHERE num = :num" with :num=1.
Abgebrochen (Speicherabzug geschrieben)
```

Here is an example stack trace (starting from the worker function):
```
 #0 raise() in /lib64/libc.so.6
 #1 abort() in /lib64/libc.so.6
 #2 __gnu_cxx::__verbose_terminate_handler() in /usr/src/debug/gcc-9.2.1-1.fc31.x86_64/libstdc++-v3/libsupc++/vterminate.cc:95
 #3 __cxxabiv1::__terminate() in /usr/src/debug/gcc-9.2.1-1.fc31.x86_64/libstdc++-v3/libsupc++/eh_terminate.cc:47
 #4 __cxa_call_terminate() in /usr/src/debug/gcc-9.2.1-1.fc31.x86_64/libstdc++-v3/libsupc++/eh_call.cc:54
 #5 __cxxabiv1::__gxx_personality_v0() in /usr/src/debug/gcc-9.2.1-1.fc31.x86_64/libstdc++-v3/libsupc++/eh_personality.cc:677
 #6 _Unwind_RaiseException_Phase2() in /usr/src/debug/gcc-9.2.1-1.fc31.x86_64/libgcc/unwind.inc:64
 #7 _Unwind_Resume() in /usr/src/debug/gcc-9.2.1-1.fc31.x86_64/libgcc/unwind.inc:241
 #8 soci::details::ref_counted_statement_base::dec_ref()() in /home/<myuser>/.local/lib64/libsoci_core.so.4.0
 #9 soci::details::once_temp_type::~once_temp_type()() in /home/<myuser>/.local/lib64/libsoci_core.so.4.0
#10 worker() in /home/<myuser>/<somepath>/sqlite-test.cpp:51
```

This issue seems to have been detected before, but there was never a solution found. See #768, #701, #529.

**Comment by vadz** [comment]
How do you compile SOCI? When using C++11 compiler (almost a given nowadays), `SOCI_HAVE_CXX11` **must** be defined.

**Comment by zyzzyxdonta** [comment]
Alright, it works by setting `CMAKE_CXX_STANDARD` to 17. I thought the lib knew what my compiler could do, since it uses CMake. Sorry for bothering.

**Comment by Spixmaster** [comment]
Concurrency with SQLite is possible by setting `PRAGMA journal_mode=WAL` once. As it is a database setting this mode persists for all connections. Some reference: https://til.simonwillison.net/sqlite/enabling-wal-mode

**Comment by Spixmaster** [comment]
No, this i right. I just want to help everyone who stumbles upon this issue how to achieve concurrency with SQLite.
