### ISSUE TITLE
[armv7hl] error: cast from 'char*' to 'TIMESTAMP_STRUCT*'

### ISSUE THREAD

**Issue by denisarnaud** [SOCI/soci#812]
Hello,

the build of SOCI v4.0.0 on Fedora for the ARMv7HL architecture has been consistently failing. An example of such a build is https://koji.fedoraproject.org/koji/taskinfo?taskID=45383684

The build log is https://kojipkgs.fedoraproject.org//work/tasks/3727/45383727/build.log
and the error is happening around the middle of that page:
```bash
make[2]: Entering directory '/builddir/build/BUILD/soci-4.0.0/tmpbuild'
[ 16%] Building CXX object src/backends/odbc/CMakeFiles/soci_odbc_static.dir/standard-into-type.cpp.o
cd /builddir/build/BUILD/soci-4.0.0/tmpbuild/src/backends/odbc && /usr/bin/g++  -DBOOST_ALL_NO_LIB -DHAVE_DL=1 -DSOCI_ABI_VERSION=\"4.0\" -I/builddir/build/BUILD/soci-4.0.0/tmpbuild -I/builddir/build/BUILD/soci-4.0.0/include -I/builddir/build/BUILD/soci-4.0.0/tmpbuild/include -I/builddir/build/BUILD/soci-4.0.0/include/private  -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -march=armv7-a -mfpu=vfpv3-d16 -mtune=generic-armv7-a -mabi=aapcs-linux -mfloat-abi=hard -pedantic -Werror -Wno-error=parentheses -Wall -Wextra -Wpointer-arith -Wcast-align -Wcast-qual -Wfloat-equal -Woverloaded-virtual -Wredundant-decls -Wno-long-long -std=gnu++98  -Wno-variadic-macros   -o CMakeFiles/soci_odbc_static.dir/standard-into-type.cpp.o -c /builddir/build/BUILD/soci-4.0.0/src/backends/odbc/standard-into-type.cpp
/builddir/build/BUILD/soci-4.0.0/src/backends/odbc/standard-into-type.cpp: In member function 'virtual void soci::odbc_standard_into_type_backend::post_fetch(bool, bool, soci::indicator*)':
/builddir/build/BUILD/soci-4.0.0/src/backends/odbc/standard-into-type.cpp:176:37: error: cast from 'char*' to 'TIMESTAMP_STRUCT*' {aka 'tagTIMESTAMP_STRUCT*'} increases required alignment of target type [-Werror=cast-align]
  176 |             TIMESTAMP_STRUCT * ts = reinterpret_cast<TIMESTAMP_STRUCT*>(buf_);
      |                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
make[2]: *** [src/backends/odbc/CMakeFiles/soci_odbc_static.dir/build.make:138:
src/backends/odbc/CMakeFiles/soci_odbc_static.dir/standard-into-type.cpp.o] Error 1
make[2]: Leaving directory '/builddir/build/BUILD/soci-4.0.0/tmpbuild'
make[1]: *** [CMakeFiles/Makefile2:677:
src/backends/odbc/CMakeFiles/soci_odbc_static.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

It seems to be somewhat related to issue #777 

Thanks for the great work on SOCI!

Kind regards

Denis

**Comment by vadz** [comment]
I don't think this is the same problem as #777, this is just about the buffer alignment and there are 2 problems here:

1. Avoiding the `-Wcast-align` warning (which is turned into an error by the use of `-Werror`).
1. Ensuring that the buffer is actually aligned properly for `TIMESTAMP_STRUCT`.

I hope that the latter part actually already works as the pointers returned from `new` should be correctly aligned anyhow. So all we need to do is to just get rid of the warning. We could, of course, just suppress it, or we could use `__builtin_assume_aligned` (for gcc only), but before doing it, it would be great to check that the code really works. Do you have the possibility to run SOCI test suite under this ARM platform? If so, please consider removing `-Werror` from `cmake/SociConfig.cmake`, building it (which should succeed now, albeit with some warnings) and do it, to check it. TIA!

**Comment by denisarnaud** [comment]
Thanks!

Well, I don't have access to an ARMv7hl virtual machine or device. From what I understand, Raspberry PI Model 2 have such a CPU: https://elinux.org/RPi_HardwareHistory
(I've only a Raspberry PI 3 at home with already a a Debian on it).
The only thing I can try is to amend the build flags for that specific architecture on the Fedora build specification.

**Comment by vadz** [comment]
I can't test this neither, so I've just suppressed the warning in #813. Please let me know if you have any comments about that.

**Comment by vadz** [comment]
I've fixed the remaining occurrences of the warning from your build without `-Werror` and tagged the commit above with 4.0.1-alpha2, hopefully this fixes the problem.

**Comment by denisarnaud** [comment]
It seems to work: https://koji.fedoraproject.org/koji/taskinfo?taskID=45430206
Thanks!
