### ISSUE TITLE
Mysql backend is not thread safe

### ISSUE THREAD

**Issue by andrewkcorcoran** [SOCI/soci#818]
Creating a new `soci::session` for mysql in different threads is not safe (despite [the documentation](http://soci.sourceforge.net/doc/release/3.2/multithreading.html) saying this is supported by soci).

The reason being that [`mysql_init` is not thread safe](https://dev.mysql.com/doc/refman/8.0/en/mysql-init.html).

**Comment by andrewkcorcoran** [comment]
#349

**Comment by vadz** [comment]
Sorry, I don't know anything about MySQL API and don't use it myself, so I have no idea about how to deal with `mysql_init()` thread unsafety. If anybody has any ideas/PRs to fix it, they're, of course, welcome.

**Comment by avidboarder** [comment]
We've got an idea that seems to fix this. Will create a PR once fully tested.

**Comment by andrewkcorcoran** [comment]
5826e8ce9676b5f40fba1db334f124320e062b92

**Comment by andrewkcorcoran** [comment]
May want to generate a new release with this bug fix?
