### ISSUE TITLE
postgresql_session_backend does not initialize its conn_ data member

### ISSUE THREAD

**Issue by jurko-gospodnetic** [SOCI/soci#822]
`postgresql_session_backend ` class does not initialize its `conn_` data member so that pointer can be left with a non-null garbage initial value. 

The only place this pointer does get initialized is on a successful `postgresql_session_backend::connect()` call, but for instance in `postgresql_session_backend::clean_up()` (called from the session's destructor) we have a `0 != conn_` check to see if the session is currently connected and this can result in us using a garbage pointer.

**Comment by vadz** [comment]
Yes, indeed, this looks wrong to me, thanks for noticing! I believe the simplest fix would be to get rid of `conn` local variable in `postgresql_session_backend::connect()` and just use `conn_` directly instead, as we need to call `PQFinish()` on it if it's non-null even in case of failure.

**Comment by jurko-gospodnetic** [comment]
plus initialize the pointer to `nullptr`? 😄

**Comment by vadz** [comment]
> plus initialize the pointer to `nullptr`?

Well, this isn't really needed, as it would be initialized as the first thing in `connect()`, called from ctor. But it could still be done, I guess...

With the switch to C++11 I'd do it directly in the declaration, but we're not quite there yet.
