### ISSUE TITLE
How to detect a connection loss?

### ISSUE THREAD

**Issue by DVridovic** [SOCI/soci#823]
Hi

I'm using SOCI to connect to a Postgresql database. If the connection is lost (for instance because the database is restarted), a subsequent query attempt causes a segmentation fault. How can I detect that the connection was lost in order to reconnect? I tried setting a failover_callback, overloading all four functions that this interface offers, but none of these functions ever gets called.

**Comment by DVridovic** [comment]
Hi again

It was my mistake: the failover_callback went out of scope and was deleted after it was set. Looking into the SOCI source code I realized that only a pointer to this object is stored. Now I make it static and everything works.

**Comment by vadz** [comment]
Glad to hear that this works for you, but it probably means that it's not necessary to keep this issue open, so closing.
