### ISSUE TITLE
conda-forge package for SOCI

### ISSUE THREAD

**Issue by marimeireles** [SOCI/soci#839]
Hey'all,
I'm creating a package for SOCI in conda-forge and would like to know if any of you are interested in joining as a maintainer of the recipe :)

More info on conda forge: https://conda-forge.org/

**Comment by vadz** [comment]
Sorry, I don't know anything about Conda so I'm not going to do it. Of course, if you have any concrete questions or problems, please post to SOCI mailing list or create issues/PRs for them here. But it doesn't seem useful to keep this one open.
