### ISSUE TITLE
Select after csv import gives wrong values

### ISSUE THREAD

**Issue by stkruse** [SOCI/soci#842]
Hi,
I'm using the sqlite3 backend. When I populate a table from csv and make a select from soci, in the first row are always zeros.
That's how I create the table.
```sql
create table test(
	a double not null,
	b double not null,
	c double not null,
	primary key (a, b)
	);
```

that's the "test.csv":
```
a, b, c
1,1,1
2,2,2
3,3,3
```

and that's how I load the values from the csv into my table:

```sql
.mode csv
.import test.csv test
```
some defines for understanding what's happening

and that's how I make the query (shortend, to be easier to understand ;))

```c++
    soci::rowset<soci::row> rs = db.prepare << "select a, b, c from test";
    std::vector<std::vector<double>> res;
    for (auto& row : rs)
    {
      std::vector<double> rowVec;
      for(size_t i = 0; i != row.size(); ++i)
      {
        const auto& props = row.get_properties(i);
        switch(props.get_data_type())
        {
        case soci::dt_double:
          rowVec.push_back(row.get<double>(i));
          break;
        
        default: 
          break;
        }
      }
    res.push_back(rowVec)
  }
```

If I add some useless `where` clause in the sql statement, like "select a, b, c from test where a < 50"; everything works as expected.

Any idea what may cause the problem?

**Comment by vadz** [comment]
It seems pretty obvious that your import imported zeroes into the database. Please check it using sqlite interactively.

**Comment by stkruse** [comment]
Sorry, but I don't. With the same select in the sqlite3shell I don't get the zeros.

**Comment by stkruse** [comment]
@vadz Unfortunately I can't upload the database directly, but I attached a zip file. It contains a .patch file, with a test case for test-sqlite3.cpp , a data base file with just one table "test" and the csv file I used for importing the data. If you apply the patch file and copy the data base file for example to the bin directory containing the test executable, you can run the test and just make the select on the table in the command line. So it should be easy to verify the bug.
[soci_test.zip](https://github.com/SOCI/soci/files/5674235/soci_test.zip)

**Comment by vadz** [comment]
So is CSV a red herring then? I.e. can you reproduce the problem by doing normal inserts into the database?

Because while I can believe that there is a bug in SOCI rowset API when working with SQLite (still weird that nobody has found it until now, but possible), it seems completely impossible that it usually works but doesn't work when the database was populated via CSV import. IOW, this bug should be reproducible without involving any CSV at all.

**Comment by vadz** [comment]
P.S. I've just realized that your username looked familiar, sorry for not recognizing it initially!

**Comment by stkruse** [comment]
I wasn't able to reproduce it without the csv import. When I fill the table with inserts everything works as expected.
And, as I wrote above, when adjusting the query and add a "where a < 5" for example, it works as well and doesn't return the zeros.

**Comment by vadz** [comment]
Sorry, I just don't see how is it possible. SOCI doesn't care or know how was the database filled, so its behaviour can't possibly depend on it if the database data is really the same in both cases. This is why I was so sure initially that it wasn't, i.e. that CSV import has simply created an extra row of zeroes. If this is not the case, I have no idea what's going on. Looking at your code more carefully now, I wonder what exactly is it supposed to do, i.e. why do you use `row.push_back()`?

I don't use SOCI with SQLite myself, so I'm afraid I don't have time/motivation to investigate this, but something seems really fishy here.

**Comment by stkruse** [comment]
In my code above is a mistake. I used "row" two times. It was a bit too fast copy&paste plus shortening. The example from the zip file is better. I'll edit the code above to correct this.

So, in fact the code has a vector of vectors (I know, it's not the best representation for a table) and I just write the values in a vector.
I the real code it's more type independent to fit in the interface of our application and in all other cases it has worked like a charm. But it's the first time I used a csv import to fill a table. And to make it reproducible, I'll shortened the code to show the essential part here. 

To be  honest, until today I used soci more or less like a black box. Shortly, I tried to debug inside soci today to find the problem myself, but since I'm not familiar with the implementation details I need more time for that.

**Comment by stkruse** [comment]
All right, I'd a deeper look into this today. It seems that soci is right.
It's a mix of my fault and an interesting behavior of sqlite:
First, it would be good, if I had read the sqlite documentation more carefully. If the table already exists, the csv import interprets the first row as content, but I had the column names in it. During the insertion, sqlite doesn't check the types and inserts everything.

In the reading operation in `post_fetch` soci calls `sqlite3_column_double()` which ends in calling `memRealValue` which itselft calls sqlite3AtoF().

What happens here is: sqlite3 tries to interpret the value as double and tries to convert it. Since it cannot convert the value it writes a zero to the value `pResult` field and returns zero to indicate that it couldn't convert the value. But the calling function `memRealValue` ignores the return value so we don't have any information if the conversion was successful. 

It looks like the sqlite3shell uses another functionality for select statements which doesn't ignore the return value of qlite3AtoF() and filters the not convertibles out.

**Comment by vadz** [comment]
I guess SOCI could get the column value as text and perform the conversion itself instead of relying on `sqlite3_column_double()`, but I don't know if it's really worth it. In principle, SOCI attaches more importance to types than SQLite, but I'm not sure if we can really make interface with SQLite typesafe, even if we try...
