### ISSUE TITLE
Installs cmake files into uncommon location ${PREFIX}/cmake

### ISSUE THREAD

**Issue by yurivict** [SOCI/soci#849]
4.0.1 installs these cmake files:
```
cmake/SOCI-%%CMAKE_BUILD_TYPE%%.cmake
cmake/SOCI.cmake
```

```${PREFIX}/cmake``` is an uncommon location for Unix-liks systems and according to cmake docs is only used on Wndows: https://cmake.org/cmake/help/v3.0/command/find_package.html

```
> Each entry is meant for installation trees following Windows (W), UNIX (U), or Apple (A) conventions:
> <prefix>/                                               (W)
> <prefix>/(cmake|CMake)/                                 (W)
> <prefix>/<name>*/                                       (W)
> <prefix>/<name>*/(cmake|CMake)/                         (W)
> <prefix>/(lib/<arch>|lib|share)/cmake/<name>*/          (U)
> <prefix>/(lib/<arch>|lib|share)/<name>*/                (U)
> <prefix>/(lib/<arch>|lib|share)/<name>*/(cmake|CMake)/  (U)
```

**Comment by vadz** [comment]
If you know of a canonical way to install the files in the right location depending on the system, please don't hesitate proposing a PR fixing this. TIA!

**Comment by yurivict** [comment]
```
if (UNIX)
  set (CMAKE_PATH "cmake/lib")
else if (WINDOWS)
  set (CMAKE_PATH "cmake")
else()
  message(FATAL "Unrecognized system")
endif()

**Comment by vadz** [comment]
Sorry, how can this work when `CMAKE_PATH` is never used anywhere? Maybe you could make a PR with the proposed change?

**Comment by vadz** [comment]
P.S. It seems like `${CMAKE_PATH}` should be used as `DESTINATION` argument in `install(EXPORT)` in `src/core/CMakeLists.txt`, is this what you meant?

**Comment by yurivict** [comment]
You asked:

> If you know of a canonical way to install the files in the right location depending on the system

The above snippet shows how to install into directories depending on the system.
You need to add ```CMAKE_PATH``` to the install instruction:

```install(libmy.so ${CMAKE_PATH})```.

**Comment by vadz** [comment]
FWIW I still have no idea what exactly needs to be changed here. We currently use `set_target_properties(... INSTALL_NAME_DIR ${CMAKE_INSTALL_PREFIX}/lib)` and then `install()` is used with `INCLUDEDIR`, `BINDIR` and `LIBDIR`, so I still don't see where does `/cmake` suffix come from.

I also couldn't find any mention of `CMAKE_PATH` anywhere.

**Comment by yurivict** [comment]
https://gitlab.kitware.com/cmake/cmake/-/issues/22004

**Comment by KyleFromKitware** [comment]
The offending code is [here](https://github.com/SOCI/soci/blob/1bb6fbdce77fc3657a982368ab1569e3de2a5ad8/src/core/CMakeLists.txt#L127) and [here](https://github.com/SOCI/soci/blob/1bb6fbdce77fc3657a982368ab1569e3de2a5ad8/cmake/SociBackend.cmake#L232):

```cmake
install(EXPORT SOCI NAMESPACE SOCI:: DESTINATION cmake)
```

It should be:

```cmake
install(EXPORT SOCI NAMESPACE SOCI:: DESTINATION ${LIBDIR}/cmake)
```

As a side note, I would recommend using `${CMAKE_INSTALL_BINDIR}` and `${CMAKE_INSTALL_LIBDIR}` instead of the `${BINDIR}` and `${LIBDIR}` variables that I see being used in the install code.

**Comment by KyleFromKitware** [comment]
You're also not generating and installing a `SociConfig.cmake` (different from the `cmake/SociConfig.cmake` file that I see in this repo), so `find_package()` won't work even if the destination is fixed.

**Comment by KyleFromKitware** [comment]
See https://cmake.org/cmake/help/latest/manual/cmake-packages.7.html for a guide on how to generate an export package correctly.

**Comment by vadz** [comment]
Thanks @KyleFromKitware! Unfortunately this code was written by people who are not active on the project any more and I don't know much about CMake, so I'm very reluctant to touch it, which is why I hoped someone else could fix it.

I'm going to change the `install` argument as this seems the obviously correct thing to do, and will try to look at `SociConfig.cmake` generation at some unspecified later time.

Thanks again for your help!

**Comment by vadz** [comment]
Surely you could just set `SOCI_CFLAGS` or whatever CMake uses to skip the autodetection to work around this, at least for now?

Anyhow, I understand that it's a problem, and I'd gladly merge any fixes. I don't even use CMake myself, so it's hardly a priority for me, personally, to fix this, but as I wrote I'll try to do it before making the next SOCI release.

**Comment by TimB87** [comment]
@yurivict i had to do some trickery for libsoci to work on [CRUX](https://crux.nu/ports/crux-3.6/contrib/libsoci/Pkgfile), I haven't checked what FreeBSD does but maybe it helps

**Comment by yurivict** [comment]
The cmake files installed by the FreeBSD port for SOCI are broken, that's why I am here.

**Comment by Krzmbrzl** [comment]
As a follow-up: #1118 aims at doing it "the proper way" - that includes the entire workflow of generated config and targets files.
