### ISSUE TITLE
postgresql - accessing db from multiple threads

### ISSUE THREAD

**Issue by atari83** [SOCI/soci#855]
Hello there,

I want to access a PostgreSQL tables across a number of threads. So, basically there will be lots of concurrent request to database and its tables, running functions and etc. 

Whats the proper way to insure that concurrency is preserved ?

Current i'm using connection pool, does increasing the connections in connection pool actually helps ?

Also lets say i'm running a query and there is no idle or free connection for running the query, my question is how soci will manages this situation? Does it queue up the requests or just ignore the request ?

**Comment by vadz** [comment]
Not sure what the actual question is here, and I definitely can't know what is the optimal number of connections to use in your case, but I can at least say that trying to get a connection from the pool when all of them are busy will block until one is freed.

If you'd like to discuss this further, I think it would be better to do it on the mailing list or, maybe, using GitHub discussions, but this doesn't really look like an issue, so I'm closing it.

**Comment by atari83** [comment]
Thanks for response :)
