### ISSUE TITLE
Package not discoverable by cmake through installed .cmake files

### ISSUE THREAD

**Issue by yurivict** [SOCI/soci#866]
You install these files:
```
$ pkg info -l soci | grep cmake
	/usr/local/cmake/SOCI-release.cmake
	/usr/local/cmake/SOCI.cmake
```
but this cmake instruction fails find_package(Soci REQUIRED)```:
```
  Could not find a package configuration file provided by "SOCI" with any of
  the following names:

    SOCIConfig.cmake
    soci-config.cmake
```

It appears that ```/usr/local/cmake/``` is a wrong place because ```SOCI``` files are the only files there:
```
$ ls -l /usr/local/cmake/
total 40
-rw-r--r--  1 root  wheel  8656 Mar 21 11:01 SOCI-release.cmake
-rw-r--r--  1 root  wheel  4589 Mar 21 11:01 SOCI.cmake
```

**Comment by vadz** [comment]
The files you show (`SOCI-release.cmake`, `SOCI.cmake`) don't come from SOCI sources and I don't see `/usr/local/cmake` anywhere in them neither. Are you sure you're not looking at some FreeBSD-specific packaging changes?

**Comment by vadz** [comment]
Or perhaps this is the same as #849?

**Comment by yurivict** [comment]
> The files you show (SOCI-release.cmake, SOCI.cmake) don't come from SOCI sources [...]

The FreeBSD port doesn't add any cmake files. They are installed by the project itself.

**Comment by vadz** [comment]
Yes, sorry, I think it's really the same thing as #849, which you also reported. I don't think it makes sense to keep both of them open, so closing this one. Any help with fixing that problem would be still very welcome.
