### ISSUE TITLE
Oracle ORA-01455: converting column overflows integer datatype when dealing TO_NUMBER(TO_CHAR(VALID_DATE, 'YYYYMMDDHH24MISS')) VALID_DATE

### ISSUE THREAD

**Issue by 530967061** [SOCI/soci#872]
src/backends/oracle/statement.cpp:293
For SQL 'TO_NUMBER(TO_CHAR(VALID_DATE, 'YYYYMMDDHH24MISS'))' we got precision = 0, but this can not be put into dt_integer, we should use dt_long_long instead.

When I changed code to:
        if (dbscale > 0)
        {
            if (session_.get_option_decimals_as_strings())
            {
                type = dt_string;
            }
            else
            {
                type = dt_double;
            }
        }
        else if (**dbprec != 0** && dbprec <= std::numeric_limits<int>::digits10)
        {
            type = dt_integer;
        }
        else
        {
            type = dt_long_long;
        }
this error disappear

**Comment by vadz** [comment]
Sorry, I'm not sure what exactly is going on here. Ideal would be to make a PR adding a unit test checking for this problem (and which would fail right now with Oracle) and the proposed fix (with which the unit test would pass). Could you please try to do this? TIA!

**Comment by 530967061** [comment]
I have already made a PR, but I'm not sure whether this modify is enough, please do further check, thanks.
