### ISSUE TITLE
Consistent name for versioning

### ISSUE THREAD

**Issue by marimeireles** [SOCI/soci#878]
Hi!
I noticed that the naming of the versioning is not consistent, e.g:

![image](https://user-images.githubusercontent.com/17600982/116403423-1123aa00-a81d-11eb-8249-906442191530.png)

Sometimes it's called alpha, sometimes it has a `v` in front, sometimes doesn't. 

I ported SOCI to conda-forge a while ago and it has a couple of uses (as of now 1.2k downloads from there https://github.com/conda-forge/soci-feedstock) and conda-forge has an automated system for creating new package versions, but for that to work I need to have a consistent url to point it too, in the past I had 

```
https://github.com/SOCI/soci/archive/{{ version }}.tar.gz
```

but now it changed to

```
https://github.com/SOCI/soci/archive/v{{ version }}.tar.gz
```

I'd like to know if it's possible to have a consistent naming?
Thanks!

**Comment by vadz** [comment]
I prefer using `vN`, so this is what the releases I make use -- but I didn't modify the existing tags. We do have `v` versions for all 4.x releases, so I am not sure what is the actual problem, i.e. why not just use `v{{ version }}`?

Alpha releases are, of course, not "real" release, so this is why they have alpha in their names.

**Comment by marimeireles** [comment]
>Alpha releases are, of course, not "real" release, so this is why they have alpha in their names.

That's right. So, no problem here.

I still don't understand why the 3.2.3 version, for example, doesn't have a v3.2.3.

>We do have v versions for all 4.x releases

You mean that from now own all versions will have a v?
If that is so than no problem, I can just keep using the `v{{ version }}` :)

**Comment by vadz** [comment]
> I still don't understand why the 3.2.3 version, for example, doesn't have a v3.2.3.

They were made by previous maintainers who had their own preferences. If it's really a big problem, I could create `vX` tags matching all the existing `X` tags, but if not, I'd rather not do it.
 
> > We do have v versions for all 4.x releases
> 
> You mean that from now own all versions will have a v?

As long as I'm doing them, yes.

> If that is so than no problem, I can just keep using the `v{{ version }}` :)

OK, then this can be just closed, right?

**Comment by marimeireles** [comment]
It's no problem for the past.
Yes, this can be close, thanks for clearing things!
