### ISSUE TITLE
Unresolved describe_column for sqlite3 backend

### ISSUE THREAD

**Issue by MarcSchaetz** [SOCI/soci#879]
I'm currently trying to compile a project with sqlite3 and soci as a static library. However I get the following Linker error.

~~~
error LNK2019: unresolved external symbol _sqlite3_column_decltype referenced in function "public: virtual void __thiscall soci::sqlite3_statement_backend::describe_column(int,enum soci::data_type &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &)" (?describe_column@sqlite3_statement_backend@soci@@UAEXHAAW4data_type@2@AAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)
~~~

This is my code:
~~~cpp
#include <soci/soci.h>
#include <soci/sqlite3/soci-sqlite3.h>
#include <catch.hpp>

TEST_CASE("do something")
{
    soci::connection_parameters p(soci::sqlite3, ":memory:");
    soci::session sql(p);
    ...
}
~~~

When I substitute `soci::sqlite3` with `"sqlite3"` the compilation is successful but I get an error that the shared library of the sqlite3 backend is not found.

Cmake configuration:
~~~cmake
...
set(SQLite3_INSTALL_DIR C:/SQLite3)
find_package(SQLite3 CONFIG REQUIRED PATHS "${SQLite3_INSTALL_DIR}/cmake")

set(Soci_INSTALL_DIR C:/Soci)
find_package(Soci CONFIG REQUIRED PATHS "${Soci_INSTALL_DIR}/lib/cmake/SOCI")


target_link_libraries(${TARGET_NAME}
    PUBLIC
        ${PROJECT_NAME}
		SQLite::SQLite3
		SOCI::soci_core_static
		SOCI::soci_sqlite3_static
)
...
~~~

Soci was installed with the following configuration:
~~~batch
set install_prefix=C:\Soci
set sqlite3_dir=C:\SQLite3

cmake.exe -DSOCI_CXX11=ON -DSOCI_SHARED=OFF -DSOCI_STATIC=ON -DSOCI_TESTS=OFF -DWITH_BOOST=OFF -DSOCI_DB2=OFF -DSOCIFIREBIRD=OFF -DSOCI_MYSQL=OFF -DWITH_SQLITE3=ON -DCMAKE_PREFIX_PATH=%sqlite3_dir% -DSOCI_POSTGRESQL=OFF -DCMAKE_INSTALL_PREFIX=%install_prefix% -DCMAKE_DEBUG_POSTFIX=d -A Win32 ..

echo -- Install Soci with Configuration 'Debug'
msbuild INSTALL.vcxproj /p:Configuration=Debug

echo -- Install Soci with Configuration 'Release'
msbuild INSTALL.vcxproj /p:Configuration=Release
~~~

Thanks in advance

**Comment by vadz** [comment]
The function definitely is there in `src/backends/sqlite3/statement.cpp`, so it must be some sort of build problem, but I don't see what could it be to be honest, sorry. All I can recommend is to debug it in the usual way, i.e.

1. Check that the linker command line contains the expected library.
2. Check that the library contains the function.

**Comment by MarcSchaetz** [comment]
Ok, so I found a lead.
The part which is responsible for the error is
~~~cpp
char const* declType = sqlite3_column_decltype(stmt_, colNum-1);

if ( declType == NULL )
{
    static char const* s_char = "char";
    declType = s_char;
}

std::string dt = declType;
~~~

I probably clashes with the sqlite version 3.35.5

**Comment by MarcSchaetz** [comment]
I located the error inside the compilation of sqlite3. I used the git repository https://github.com/azadkuh/sqlite-amalgamation which provides a CMakeLists for the amalgamated version of sqlite3 and it seems there the binary is corrupted.
