### ISSUE TITLE
Windows 10 Firebird 3.0 Soci 4.0.2

### ISSUE THREAD

**Issue by robo-loki** [SOCI/soci#881]
Hi all-

Is anyone using fb 3.0 with win 10 on Soci 4.0.2? I'm using command line tool.
Since that post I found out more compiler switches like /link /libpath . It didn't need those anyway.

I posted at soci-users but not many people hang out there? Vadz did you get it to work on windows too?

If not, do you have fb database 3.0 working on Linux?

I compiled and linked code but it didn't seem to work.

Thanks,
Robo-loki

**Comment by vadz** [comment]
Sorry, this is not really an issue because it doesn't say at all what is wrong. Please provide a minimal example of not working code or, ideally, check if the unit tests work for you and modify them to show the problem.

FWIW, yes, Firebird backend does globally work under Windows with SOCI 4.
