### ISSUE TITLE
session::open for sessions from pool need to set backEnd_ again

### ISSUE THREAD

**Issue by 530967061** [SOCI/soci#890]
If we write code like：
`
connection_pool pool(10);
session s(pool);
s.open(...);
s.commit();
`

we will encounter an exception: "Session is not connected."
so we need to reset backEnd_ when we do open for session from pool

void session::open(connection_parameters const & parameters)
{
    if (isFromPool_)
    {
        pool_->at(poolPosition_).open(parameters);
        **_backEnd_ = pool_->at(poolPosition_).get_backend();_**
    }
    else
    {
        if (backEnd_ != NULL)
        {
            throw soci_error("Cannot open already connected session.");
        }

        backend_factory const * const factory = parameters.get_factory();
        if (factory == NULL)
        {
            throw soci_error("Cannot connect without a valid backend.");
        }

        backEnd_ = factory->make_session(parameters);
        lastConnectParameters_ = parameters;
    }
}

**Comment by vadz** [comment]
Could you please open a PR with your changes and add a test case for this bug to `tests/common-tests.h`? TIA!
