### ISSUE TITLE
#error "SOCI must be configured with C++11 support when using C++11"

### ISSUE THREAD

**Issue by mscg-ssxd** [SOCI/soci#893]
Please help me to see what causes this problem.
I haven't found out why.

error:
![Screenshot_select-area_20210630170156](https://user-images.githubusercontent.com/52558920/123934034-7cc4f780-d9c5-11eb-8aec-ff1f7bcdfd9e.png)

makefile:
![Screenshot_select-area_20210630170247](https://user-images.githubusercontent.com/52558920/123934105-8babaa00-d9c5-11eb-943f-c7249a46d72b.png)

**Comment by vadz** [comment]
You're compiling your program with `-std=c++11` but you haven't compiled SOCI with this option. You need to use the same language dialect for both.
