### ISSUE TITLE
std::vector<soci::row>::resize()  The specified type does not meet the requirements of Cpp17MoveInsertable

### ISSUE THREAD

**Issue by kuvaldini** [SOCI/soci#900]
```
      using namespace soci;
      constexpr int BATCH_SIZE = 30;
      std::vector<row> rows(BATCH_SIZE);
      statement st = (sql.prepare << "select * from table", into(rows));
      st.execute();
      while (st.fetch()) {
         std::vector<int>::iterator pos;
         for (pos = valsOut.begin(); pos != valsOut.end(); ++pos) {
            cout << *pos << '\n';
         }
         rows.resize(BATCH_SIZE); //ERROR
      }
```
```
In template: static_assert failed due to requirement '__is_cpp17_move_insertable<std::allocator<soci::row>, false>::value' "The specified type does not meet the requirements of Cpp17MoveInsertable"
```

**Comment by vadz** [comment]
This is clearly related to your `Peer` class which must not be default constructible or something like this. When reporting a bug, please provide a simple self-contained example reproducing the problem, not just some snippet of code.

**Comment by kuvaldini** [comment]
Could you reread the error message once more?

`In template: static_assert failed due to requirement '__is_cpp17_move_insertable<std::allocator<soci::row>, false>::value' "The specified type does not meet the requirements of Cpp17MoveInsertable"`

It tells nothing related to my code. The problem is with `soci::row`!

**Comment by kuvaldini** [comment]
And as you could also see my class Peer existed only in a function parameters, (now removed) and does not participate.

**Comment by vadz** [comment]
Sorry, I didn't notice/realize you used vector of `row`s. We need to make `row` movable to fix this.

**Comment by kuvaldini** [comment]
Yes. Thanks a lot for understanding and attention.
