### ISSUE TITLE
How can I get soci_sqlite3_4_0.dll?

### ISSUE THREAD

**Issue by Jasonzyt** [SOCI/soci#903]
I downloaded and compiled `libsqlite3`,renamed it to `soci_sqlite3_4_0.dll`,and put it in correct directory.  
But when I use `sql.open("sqlite3","data.db")`,soci throws a `soci_error`:   
`Failed to resolve dynamic symbol: factory_sqlite3`  
I think soci_sqlite3_4_0.dll is the cause of the problem  
How can I fix it?

**Comment by Jasonzyt** [comment]
my libsqlite3 is download with vcpkg(command: `vcpkg install sqlite3:x64-windows`)

**Comment by Jasonzyt** [comment]
my soci compiled with cmake
![image](https://user-images.githubusercontent.com/66063199/128301489-0d5729be-87fd-4628-9d83-fc44538ac033.png)
![image](https://user-images.githubusercontent.com/66063199/128301527-134927b1-8512-437a-9072-9ff79347bd6a.png)
![image](https://user-images.githubusercontent.com/66063199/128301615-c0460b97-4903-4675-a71c-74d58bbe1939.png)
![image](https://user-images.githubusercontent.com/66063199/128301678-0884fecb-ce17-49ae-81cb-c5baf2d5ce80.png)

**Comment by vadz** [comment]
You don't seem to have SQLite backend, probably because CMake didn't find SQLite headers/libraries. If you have them in some location not checked by CMake, you can use its options to point it to them, see the [installation instructions](http://soci.sourceforge.net/doc/master/installation/).

**Comment by Jasonzyt** [comment]
it works,but there is a new problem:` Failed to find shared library for backend sqlite3`

**Comment by Jasonzyt** [comment]
![image](https://user-images.githubusercontent.com/66063199/128489277-3c911bdc-305a-4b3c-9c26-88499f022816.png)
is this a bug? i think `std::string::size_type const found = env.find(":", searchFrom);` needs to be replaced with `std::string::size_type const found = env.find(";", searchFrom);`

**Comment by Jasonzyt** [comment]
> it works,but there is a new problem:` Failed to find shared library for backend sqlite3`
![image](https://user-images.githubusercontent.com/66063199/128490334-b6336b55-d85a-482c-b8a7-9fc0a842e446.png)
![image](https://user-images.githubusercontent.com/66063199/128490500-41e73f61-c42e-4f49-98e3-62ec729b6b8f.png)

**Comment by vadz** [comment]
I agree that this code doesn't work well for Windows paths and should use `;` as a separator there (but still `:` under Unix). However it should only be used if you set `SOCI_BACKENDS_PATH` environment variable and normally you don't need to do it, you just need to ensure that the DLLs are in the same directory as your executable. I.e. this doesn't explain why it doesn't work for you, there is probably another dependency problem -- you should use "dependency walker" or a similar tool to check that you have all the required DLLs in `PATH`.

**Comment by Jasonzyt** [comment]
yeah, i used "dependency walker" and check,but it said 
![image](https://user-images.githubusercontent.com/66063199/128535196-1680d417-de22-48c7-9309-a95651e29313.png)

**Comment by Jasonzyt** [comment]
i have no ideas to work out that problem...
