### ISSUE TITLE
Unable to open encrypted sqlite3 database

### ISSUE THREAD

**Issue by atari83** [SOCI/soci#912]
Hello!
Currently, I can open and use sqlite3 database (with no encryption)  without any problem.
However, when I try to open the same database (with encryption) I got errors:
`sqlite3_statement_backend::prepare: file is not a database`

I've encrypted my database via sqlcipher :
```
$ ./sqlcipher plaintext.db
sqlite> ATTACH DATABASE 'encrypted.db' AS encrypted KEY 'newkey';
sqlite> SELECT sqlcipher_export('encrypted');
sqlite> DETACH DATABASE encrypted;
```

And from code-perspective, I already call upon 'pragma key' and pass the key but with no luck:

```
try {
	session sql(sqlite3, "encrypted.db");
        sql << "PRAGMA key = 'newkey';";

        rowset<row> rs = ( sql.prepare << "select type_id, type_name, from diam_type;" );
        // ...
}
catch (const sqlite3_soci_error& e) {
}

```

Can anybody help me with this problem ?
Thanks.

**Comment by sinall** [comment]
> Ok, It was definitely related to my building params. After fixing that calling to: `sql << "PRAGMA key = 'newkey';";` unlocked the database successfully. :)
> 
> Thanks.

Which buiding params then? :)
