### ISSUE TITLE
MySQL backend not support tables with JSON field type

### ISSUE THREAD

**Issue by sirlordt** [SOCI/soci#921]
Where try to select a table with JSON field type i get the error

Error: Unknown data type while executing "Select * From MyTable"

I look in the backend of Mysql. I found this:

![image](https://user-images.githubusercontent.com/4441192/146068661-aa53cf5d-597f-4cde-8f29-002ffb3866cc.png)

One missing entry in the switch needed to avoid the error.

![image](https://user-images.githubusercontent.com/4441192/146068790-dbdcbec0-3d70-4805-bcb8-a3bdfdb25f11.png)

Generally, most nodejs/java/c# drivers treat this type as a normal varchar/string. To perform an insert or update we just put a string in the json field and this works. Mysql server doesn't complain about that, only required the string has the proper json format.

`cmd.insert( "Insert Into MyTable( id, json_field ) Values( 10, '{ \"field\": \"value\" }' )" )`;

Solution:

![image](https://user-images.githubusercontent.com/4441192/146070537-d876336e-df07-432f-a6eb-e066e6004fe1.png)

**Comment by vadz** [comment]
Please don't submit patches as screenshots, this is just cruel. Please make a pull request instead. Thanks!

**Comment by sirlordt** [comment]
But!! is only one line.... You can add in the next release.
