### ISSUE TITLE
Static backend libs not linked to core

### ISSUE THREAD

**Issue by Krzmbrzl** [SOCI/soci#938]
When building SOCI as static libraries, the different backends are not linked against the core library:
https://github.com/SOCI/soci/blob/b8560cca413a370fc7019d18908d5612a8066fe8/cmake/SociBackend.cmake#L199-L201
whereas they are, if they are built as a shared library:
https://github.com/SOCI/soci/blob/b8560cca413a370fc7019d18908d5612a8066fe8/cmake/SociBackend.cmake#L161-L163

Due to the way the cmake files are currently written, when linking only to one of the backend targets, your application will not be linked against the core library. One effect of this is that the respective includes (`#include <soci/soci.h>`) will not be found as the respective include directory appears to not be part of the static library's interface.

Now the question would be: Is there a specific reason to not link against core, when building a static library or was this merely an oversight?

**Comment by vadz** [comment]
I have no idea what does it mean to link a static library with something else for CMake. Normally this doesn't make any sense because a static library is just a collection of object files and doesn't link with anything at all, but it wouldn't be the first time I'm surprised by CMake.

In any case, I do believe that you must link with the core library whenever you use SOCI and not doing it is an error. Why are you not doing this?

**Comment by Krzmbrzl** [comment]
It means that the respective include directories and additional (cmake) dependencies are inherited through the chain of interdependent targets.

I'm not explicitly linking against core as I would expect that the dependencies are automatically resolved by the abovementioned mechanism. 
It seems like SOCI is atm generally not following a strict target relationship that would allow something like this.

If I had the time, I'd offer to revamp the cmake files a bit to streamline it with how cmake users generally expect things to work. 
As it stands though, I'll just have to find my way through everything. In this case, I suppose that means explicitly linking against core as well :+1:

**Comment by vadz** [comment]
I do believe that linking with core SOCI library is the right thing to do, so IMO this is not a bug (if not linking to core works when using shared libraries, _that_ would be a bug, but not a sufficiently important one for me to care about).
