### ISSUE TITLE
Conan Version 4.03 Not support JSON field in mysql.

### ISSUE THREAD

**Issue by sirlordt** [SOCI/soci#943]
I summited a week ago a pull request with the patch to support the MYSQL json field type. But the conan version in 4.0.3 no had support too.

![image](https://user-images.githubusercontent.com/4441192/160472962-3dfea506-94a7-49b1-b68c-87a09ae2b005.png)

**Comment by vadz** [comment]
Sorry, I don't understand what are you trying to say. I've merged your PR (#940), but this was after 4.0.3, so of course 4.0.3 doesn't have it yet. I don't think there is any problem here.

Also, please don't post screenshots. Copy and paste the text instead.

**Comment by sirlordt** [comment]
I mean the package donwloaded by conan from the central conan page is the old version code 4.0.3 with no support for mysql json. You need update the version in the the central conan webpage to maybe the version 4.0.4?

**Comment by vadz** [comment]
There is no version 4.0.4 yet, the last released version is 4.0.3.

**Comment by vadz** [comment]
I don't know, sorry. I don't handle the Conan packages for SOCI.

**Comment by sirlordt** [comment]
Ok thanks.
