### ISSUE TITLE
Get queried value as string

### ISSUE THREAD

**Issue by Krzmbrzl** [SOCI/soci#948]
Is there a way to get a string representation of a generic entry in a `row` object, even if the actual data type is something else (e.g. int)?

So consider the following table
```
| col1 | col2   |
| 1    | "test" |
```
queried via
```cpp
row = sql << "SELECT col1, col2 FROM myTable";

std::cout << row.get<std::string>(0) << " " << row.get<std::string>(1);
```
(Let's ignore for a moment, that `operator<<` is overloaded for all sorts of types besides strings)

At the moment the first `get` seems to always error with a `bad_cast` exception as the actual datatype is integer.

I am kinda looking for something like a `to_string` method as in
```cpp
row.to_string(0) == "1";
row.to_string(1) == "test";
```

Does something like this already exist?

**Comment by vadz** [comment]
No, SOCI tries to be type-safe, so accessing a number as a string will be an error. And I don't think it would be a good idea to change this.

**Comment by Krzmbrzl** [comment]
A to-string method does not destroy type-safety. For an example, see how nlohmmann/json is doing this. It has the `get` methods for accessing the respective fields as the underlying type and an additional `to_string` overload to consistently obtain a string-representation of the stored value. At no point does such an approach violate type-safety.

**Comment by vadz** [comment]
Yes, `to_string()` could be added (but I have no interest in adding it personally, so it would have to be done by somebody else), I was reacting more to `get<std::string>()` part: this will have to remain an error.
