### ISSUE TITLE
cannot link struct soci::sqlite3_backend_factory const soci::sqlite3

### ISSUE THREAD

**Issue by tanbing001** [SOCI/soci#967]
when use static library, it is ok, but when use shared libraries, cannot link struct soci::sqlite3_backend_factory const soci::sqlite3

**Comment by vadz** [comment]
You must not be using the factory directly when using shared libraries, this is the whole point of them -- backends are loaded during run-time, not by referencing their symbols in the code.

I believe the documentation shows the examples of doing this quite clearly, please have a look there.
