### ISSUE TITLE
libsoci_sqlite3_4_0.lib issues

### ISSUE THREAD

**Issue by tanbing001** [SOCI/soci#970]
when build debug version,it is ok in programs,
but when build release version, errors occured,
1.MDd_DynamicDebug and MD_DynamicRelease are matchable.
2a lot of __imp__invalid_parameter when link this library

**Comment by vadz** [comment]
Sorry, it's not a SOCI problem but a problem with your build. Please ensure that you use consistent `/MD[d]` option setting and `SOCI_DLL` definition everywhere.
